### ISSUE TITLE
ROS2.Repos for Foxy v20200807 doesn't use release branches?

### ISSUE THREAD

**Issue by seanyen** [ros2/ros2#1003]
It seems the tag of `release-foxy-20200807` to contain a list of repo with the development branches opposing to the release branches. Is it expected?

https://github.com/ros2/ros2/blob/release-foxy-20200807/ros2.repos

![image](https://user-images.githubusercontent.com/25241284/89928480-bda0fb80-dbbc-11ea-8a44-9816389b9d77.png)

**Comment by jacobperron** [comment]
This was my mistake. The artifacts associated with the release were built with the correct repos file, but I accidentally made the Git tag in the wrong place. I've moved the tag to the correct commit.

Thanks for reporting!
