### ISSUE TITLE
ROS2 zeromq support?

### ISSUE THREAD

**Issue by avinashiitk** [ros2/ros2#1010]
## Bug report

**Required Info:**
Is ROS2 having zeromq support? 
- Operating System:
  - 
 Ubuntu 18.04
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by clalancette** [comment]
Please ask questions like this on https://answers.ros.org.  That way all of the information is in one place, and is searchable in the future.  I'm going to close this out.
