### ISSUE TITLE
 ros2/rosidl_typesupport_connext pointing to nonexistent branch

### ISSUE THREAD

**Issue by rotu** [ros2/ros2#1015]
ros2/rosidl_typesupport_connext points to the missing `master` branch, which results in an error on `vcs import`:

https://github.com/ros2/ros2/blob/91d8a43ed28edbe04f4ea361c493b19758e35877/ros2.repos#L342-L345

```
  === src/ros2/rosidl_typesupport_connext (git) ===
  Could not checkout ref 'master': fatal: invalid reference: master
```

**Comment by ivanpauno** [comment]
Fixed, thanks for reporting the bug!!!
