### ISSUE TITLE
Nightly Platform CI regression on Windows

### ISSUE THREAD

**Issue by caguero** [ros2/ros2#1029]
Potential regression affecting some "Nightly Platform CI" Windows jobs (the `nightly_win_rep` and `nightly_win_rel` jobs).

## Bug report

**Required Info:**

- Operating System:
  Windows

#### Steps to reproduce issue

See https://ci.ros2.org/view/nightly/job/nightly_win_rel/ and https://ci.ros2.org/view/nightly/job/nightly_win_rep/ .

#### Expected behavior

* `nightly_win_rel` was green on Sept 12, then red three days in a row.
* `nightly_win_rep` was yellow with two failing tests on Sept 12, then red three days in a row.

#### Actual behavior

Several test failures.

#### Additional information

This error might be relevant:
```
ImportError for 'pyqt': No module named 'PyQt5.QtCore'
```

**Comment by mjcarroll** [comment]
This was fixed by https://github.com/ros-infrastructure/ros2-cookbooks/pull/13 via https://github.com/ros2/ci/pull/513
