### ISSUE TITLE
Nightly Platform CI regression on OSX

### ISSUE THREAD

**Issue by caguero** [ros2/ros2#1030]
Potential regression affecting some "Nightly Platform CI" OSX jobs (the nightly_osx_release and nightly_osx_repeated).

## Bug report

**Required Info:**

- Operating System:
  - OS X

#### Steps to reproduce issue

See https://ci.ros2.org/view/nightly/job/nightly_osx_release/ and https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/ .

#### Expected behavior
The release job was green 5 days in a row until today and the repeated job was green two days ago.
#### Actual behavior

Two test failures.

#### Additional information

These errors might be relevant:

```
[test_client_scope_consistency_server_cpp-1] [ERROR] [1600173543.018179001] [rclcpp]: failed to create wait set: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/src/ros2/rcl/rcl/src/rcl/wait.c:130
```

```
[ RUN      ] TestMultiThreadedExecutor.timer_over_take
/Users/osrf/jenkins-agent/workspace/nightly_osx_release/ws/src/ros2/rclcpp/rclcpp/test/rclcpp/executors/test_multi_threaded_executor.cpp:91: Failure
Expected: (diff) > (PERIOD - TOLERANCE), actual: 0.649816 vs 0.75
[  FAILED  ] TestMultiThreadedExecutor.timer_over_take (5136 ms)
```

**Comment by mabelzhang** [comment]
Flaky test. Nightly CI for OS X are all passing now.
