### ISSUE TITLE
i can't get colored log in terminal

### ISSUE THREAD

**Issue by mantangL** [ros2/ros2#1048]
my src:
#include <memory>

#include "rclcpp/rclcpp.hpp"

int main(int argc, char * argv[])
{
  // Force flush of the stdout buffer.
  setvbuf(stdout, NULL, _IONBF, BUFSIZ);

  rclcpp::init(argc, argv);
  
  rclcpp::Node::SharedPtr node = std::make_shared<rclcpp::Node>("logging_test");
  RCLCPP_INFO(node->get_logger(), "dsad");
  RCLCPP_WARN(node->get_logger(), "dsad");
  RCLCPP_ERROR(node->get_logger(), "dsad");

  rclcpp::spin(node);

  rclcpp::shutdown();
  return 0;
}

my problem:
when ros2 run this node, the log is colored.  but ros2 launch a .py file include this node, it is no color.
my logging_test.py:
from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package='logging_test',
            node_namespace='logging_test',
            node_executable='logging_test'
        )
    ])

how can i get a color log launched by this .py file

**Comment by iuhilnehc-ynos** [comment]
@mantangL 

You can set `emulate_tty` with `True` for this Node,
```
def generate_launch_description():
return LaunchDescription([
Node(
package='logging_test',
node_namespace='logging_test',
node_executable='logging_test',
emulate_tty=True
)
])
```

or use an environment variable, such as `export RCUTILS_COLORIZED_OUTPUT=1`

**Comment by mantangL** [comment]
> export RCUTILS_COLORIZED_OUTPUT=1

thanks very much, i solve this problem using export RCUTILS_COLORIZED_OUTPUT=1.
and i use 

> emulate_tty=True
a problem arises:

> [ERROR] [launch]: Caught exception in launch (see debug for traceback): __init__() got an unexpected keyword argument 'emulate_tty'

how can i solve it?

**Comment by mantangL** [comment]
> @mantangL
> 
> You can set `emulate_tty` with `True` for this Node,
> 
> ```
> def generate_launch_description():
> return LaunchDescription([
> Node(
> package='logging_test',
> node_namespace='logging_test',
> node_executable='logging_test',
> emulate_tty=True
> )
> ])
> ```
> 
> or use an environment variable, such as `export RCUTILS_COLORIZED_OUTPUT=1`

thanks very much, i solve this problem using export RCUTILS_COLORIZED_OUTPUT=1.
and i use

emulate_tty=True

a problem arises:

[ERROR] [launch]: Caught exception in launch (see debug for traceback): init() got an unexpected keyword argument 'emulate_tty'

how can i solve it?

**Comment by iuhilnehc-ynos** [comment]
> how can i solve it?

I think you need to use ros2 with distro `foxy`(or `eloquent`, which I didn't check) not `dashing` if you want to use `emulate_tty`. It seems this feature doesn't backport for `dashing`.

**Comment by mantangL** [comment]
> > how can i solve it?
> 
> I think you need to use ros2 with distro `foxy`(or `eloquent`, which I didn't check) not `dashing` if you want to use `emulate_tty`. It seems this feature doesn't backport for `dashing`.
> 
> BTW: I suggest that you could create an issue by using the default template next time.

thanks

**Comment by clalancette** [comment]
It looks like this is solved, so I'm going to close this out.  Feel free to reopen if there is still something to be done here.

**Comment by nlgilbert** [comment]
# Functionality Review

1. Source address is taken from the settings file. Good work!
2. When a Request for Address Claim message is sent out, the camera doesn't respond right away. After a few seconds it gives the expected response, but with the following terminal output. This happens both when PeP is enabled and disabled.
![image](https://github.com/ros2/ros2/assets/63371472/d70e7cf8-a723-4672-a51a-4bb7fe8193b6)
3. There's also still the issue where sometimes when starting up we get the following error.
![image](https://github.com/ros2/ros2/assets/63371472/75282031-2f86-437c-bac2-aaa4689d6c53)
