### ISSUE TITLE
Possible regression on test_rcl_lifecycle on arch64

### ISSUE THREAD

**Issue by caguero** [ros2/ros2#1059]
## Bug report

**Required Info:**

- Operating System:
  - Linux arch64
#### Steps to reproduce issue
see https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_repeated/1408/

#### Additional information

----

**Comment by clalancette** [comment]
We haven't seen this issue since it was reported on November 13.  That is now almost a month ago.  While that doesn't guarantee this isn't an extreme flake, I don't think we'll do anything about this unless it comes back.  So I'll close this out for now, and we can reopen if it comes back.
