### ISSUE TITLE
ROS2 (Foxy): "launch" is not working on windows 10.

### ISSUE THREAD

**Issue by naeempnu** [ros2/ros2#1063]
I get this error when used: usage: ros2 [-h] Call ros2 <command> -h for more detailed usage. ... ros2: error: argument Call ros2 <command> -h for more detailed usage.: invalid choice: 'launch' (choose from 'action', 'bag', 'component', 'daemon', 'doctor', 'extension_points', 'extensions', 'interface', 'lifecycle', 'multicast', 'node', 'param', 'pkg', 'run', 'security', 'service', 'test', 'topic', 'trace', 'wtf')

Is there any alternative to launch for windows? Thanks.

**Comment by clalancette** [comment]
Launch should work in Windows.  It looks like it wasn't installed properly somehow.  What version of ROS 2 are you using, and how did you install it?

**Comment by naeempnu** [comment]
I have installed ROS2-Foxy following this: https://index.ros.org/doc/ros2/Installation/Foxy/Windows-Development-Setup/

I also checked the ros2 commands and I get this:

usage: ros2 [-h] Call `ros2 <command> -h` for more detailed usage.

ros2 is an extensible command-line tool for ROS 2.

optional arguments:
  -h, --help            show this help message and exit

Commands:
  action     Various action related sub-commands
  bag        Various rosbag related sub-commands
  component  Various component related sub-commands
  daemon     Various daemon related sub-commands
  doctor     Check ROS setup and other potential issues
  interface  Show information about ROS interfaces
  launch     Run a launch file
  lifecycle  Various lifecycle related sub-commands
  multicast  Various multicast related sub-commands
  node       Various node related sub-commands
  param      Various param related sub-commands
  pkg        Various package related sub-commands
  run        Run a package specific executable
  security   Various security related sub-commands
  service    Various service related sub-commands
  test       Run a ROS2 launch test
  topic      Various topic related sub-commands
  trace      Trace ROS nodes to get information on their execution
  wtf        Use `wtf` as alias to `doctor`

These commands have no "Launch" command.
Please let me know if you need any further information.
Thanks.
  Call `ros2 <command> -h` for more detailed usage.

**Comment by MiguelCompany** [comment]
> I also checked the ros2 commands and I get this:
> ...
> Commands:
> ...
> launch Run a launch file
> ...

I see a `launch` command listed. 

> These commands have no "Launch" command.

Is it possible that you are trying `Launch` instead of `launch`? I guess ros2 CLI is case sensitive.

**Comment by naeempnu** [comment]
Have you checked on windows?
No, I am using launch and it is working fine on Linux.

**Comment by naeempnu** [comment]
So I reinstalled ROS2 and the launch is there. Problem solved. Thanks.
