### ISSUE TITLE
Cmake Error: Could not find a package configuration file provided by "fastrtps"

### ISSUE THREAD

**Issue by xwnb** [ros2/ros2#1071]
## Bug report

**Required Info:**

- Operating System:
  - 
  - Windows 10
- Installation type:
  - 
  - from source
- Version or commit hash:
  - 
  - foxy
- DDS implementation:
  - 
  - Fast-RTPS
- Client library (if applicable):
  - 
  - N/A

#### Steps to reproduce issue

```

```

#### Actual behavior

When I tried to build foxy from source, run the build command following the steps:
> colcon build --merge-install

An error occured, and the error log shows below:

> [11.094s] CMake Error at CMakeLists.txt:26 (find_package):
> [11.094s]   Could not find a package configuration file provided by "fastrtps" with any
> [11.094s]   of the following names:
> [11.094s] 
> [11.094s]     fastrtpsConfig.cmake
> [11.094s]     fastrtps-config.cmake
> [11.094s] 
> [11.094s]   Add the installation prefix of "fastrtps" to CMAKE_PREFIX_PATH or set
> [11.094s]   "fastrtps_DIR" to a directory containing one of the above files.  If
> [11.094s]   "fastrtps" provides a separate development package or SDK, be sure it has
> [11.094s]   been installed.

Can anyone offer help? 
Thanks & Regards.

#### Additional information

----

**Comment by clalancette** [comment]
We kindly ask that you ask these questions on https://answers.ros.org .  That way it is in a centralized, searchable place.  I'm going to close this out for now, but feel free to reopen if you think you have really discovered a bug.
