### ISSUE TITLE
Mark Eloquent End-of-Life

### ISSUE THREAD

**Issue by mjcarroll** [ros2/ros2#1076]
- [x] Update rosdistro: https://github.com/ros/rosdistro/pull/27825
- [x] Update rosindex: https://github.com/ros-infrastructure/rosindex/pull/246
- [x] Update ros2_documentation: https://github.com/ros2/ros2_documentation/pull/967
- [x] https://github.com/ros2/ros2_documentation/pull/973
- [x] Remove eloquent from ros_buildfarm_config: https://github.com/ros2/ros_buildfarm_config/pull/144
- [x] Disable eloquent jobs
- [x] Delete eloquent jobs
- [x] Push final snapshot

**Comment by ipa-mdl** [comment]
In addition the `final` [snapshot](http://snapshots.ros.org/eloquent/) needs to be pushed.

**Comment by clalancette** [comment]
Eloquent jobs have been deleted from the buildfarm, so closing this out.
