### ISSUE TITLE
parameters crash on Node::set_parameters_atomically on Windows

### ISSUE THREAD

**Issue by esteve** [ros2/ros2#109]
This might be caused by the way `std::mutex` is implemented on Windows (recursive mutex), look into converting that code into critical sections using the Windows API.

**Comment by esteve** [comment]
Further investigation seems to indicate that the problem lies in using references to shared pointers, and it's not platform specific, though the issue doesn't seem to occur on Linux.

**Comment by dirk-thomas** [comment]
Where do we still use references to shared pointers? I thought we removed those recently (#94).

**Comment by esteve** [comment]
For example:

https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/service.hpp#L81
https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/parameter_service.hpp#L50

**Comment by esteve** [comment]
#107 seems to be related to this

**Comment by jacquelinekay** [comment]
Does ros2/rclcpp/#112 fix this and #107?

**Comment by esteve** [comment]
@jacquelinekay it should. @wjwwood could you test locally? (i.e. via the examples)

**Comment by wjwwood** [comment]
Sure, I'm building master now.

**Comment by esteve** [comment]
@wjwwood thanks.

**Comment by wjwwood** [comment]
lgtm

**Comment by esteve** [comment]
Fixed via ros2/rclcpp#112
