### ISSUE TITLE
Define the developer parameter API

### ISSUE THREAD

**Issue by tfoote** [ros2/ros2#11]
- [x] Determine developer API
 - [x] What methods are made available
 - [x] callback model 

----

**Comment by wjwwood** [comment]
@esteve should this be in review?

**Comment by esteve** [comment]
@wjwwood not yet, the PR I attached to this only implements the methods needed for accessing the parameter data in a node. I'll attach another PR that exposes this through the `AsyncParametersClient` and `SyncParametersClient` APIs.

**Comment by dirk-thomas** [comment]
Ready to be reviewed.

**Comment by wjwwood** [comment]
Should this be closed now? The connected pr's are merged.

**Comment by esteve** [comment]
Yep, closing now.
