### ISSUE TITLE
An error occurred when compiling in ubuntu20.04 tls

### ISSUE THREAD

**Issue by ysuperGit** [ros2/ros2#1104]
The error output is as follows:

Finished <<< ament_lint [1.94s]                            
Starting >>> ament_flake8
Finished <<< gmock_vendor [0.61s]
Finished <<< urdfdom_headers [0.70s]   
Finished <<< ament_cmake_core [0.73s]   
Starting >>> ament_cmake_libraries
Starting >>> ament_cmake_export_libraries
Starting >>> ament_cmake_python         
Starting >>> ament_cmake_include_directories
Starting >>> ament_cmake_export_definitions
--- stderr: osrf_testing_tools_cpp      
/usr/local/bin/ld: /usr/local/lib/libbfd.a(elf64-x86-64.o): relocation R_X86_64_PC32 against symbol `_bfd_elf_large_com_section' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status
make[2]: *** [src/memory_tools/CMakeFiles/memory_tools.dir/build.make:222：src/memory_tools/libmemory_tools.so] error 1
make[1]: *** [CMakeFiles/Makefile2:1090：src/memory_tools/CMakeFiles/memory_tools.dir/all] error 2

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org , and make sure to give a lot more information about your environment, which ROS distribution you are using, and what commands you ran both to install ROS and get this this error.
