### ISSUE TITLE
ROS2 Galactic build issues

### ISSUE THREAD

**Issue by vidurvij-Unity** [ros2/ros2#1160]
## Bug report

**Required Info:**

- Operating System:
  -MacOS 11.5
- Installation type:
  - From source
- Version or commit hash:
  - Galactic
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue
During Installation, getting a cmake error when running "colcon build" command on the ros2_galactic install files.

#### Actual behavior
Starting >>> ament_package
Starting >>> ament_lint
Starting >>> gtest_vendor
Starting >>> fastcdr
Starting >>> ament_cppcheck
Starting >>> iceoryx_utils
Starting >>> osrf_pycommon
Starting >>> osrf_testing_tools_cpp                                                                     
Starting >>> google_benchmark_vendor
Starting >>> urdfdom_headers
Starting >>> ament_pycodestyle
--- stderr: fastcdr                                                                                            
make: /usr/local/Cellar/cmake/3.18.3/bin/cmake: No such file or directory
make: *** [cmake_check_build_system] Error 1
---
Failed   <<< fastcdr [1.58s, exited with code 2]
--- stderr: urdfdom_headers
make: /usr/local/Cellar/cmake/3.18.3/bin/cmake: No such file or directory
make: *** [cmake_check_build_system] Error 1
---
Failed   <<< urdfdom_headers [1.48s, exited with code 2]
Aborted  <<< gtest_vendor [1.62s]                                                            
Aborted  <<< ament_pycodestyle [1.48s]
Aborted  <<< ament_lint [1.62s]
Aborted  <<< ament_package [1.62s]
Aborted  <<< google_benchmark_vendor [1.51s]
Aborted  <<< ament_cppcheck [1.62s]
Aborted  <<< iceoryx_utils [1.61s]
Aborted  <<< osrf_testing_tools_cpp [1.53s]
Aborted  <<< osrf_pycommon [1.57s]

Summary: 0 packages finished [6.09s]
  2 packages failed: fastcdr urdfdom_headers
  9 packages aborted: ament_cppcheck ament_lint ament_package ament_pycodestyle google_benchmark_vendor gtest_vendor iceoryx_utils osrf_pycommon osrf_testing_tools_cpp
  6 packages had stderr output: fastcdr google_benchmark_vendor gtest_vendor iceoryx_utils osrf_testing_tools_cpp urdfdom_headers
  319 packages not processed
#### Additional information

----

**Comment by clalancette** [comment]
It looks like you probably don't have `cmake` installed, or don't have it installed properly.  I'll suggest running `brew doctor`, making sure there are no issues, and ensuring that you have done `brew install cmake` as in the installation instructions.

In the future, please ask questions like this on https://answers.ros.org, which is our central Question and Answer site.  Closing this one.
