### ISSUE TITLE
How to pause/resume ros2 bag

### ISSUE THREAD

**Issue by liuxw7** [ros2/ros2#1170]
Hi all, In ros1 bag , we use rosbag play xxxx.bag, and we will key-down space key to pause playing, but in ros2 foxy or galastic, I can't find the way to pause the bag playing .  please give me some support to solve the problem . thanks a lot.

**Comment by Kaju-Bubanja** [comment]
Check: https://github.com/ros2/rosbag2/issues/696

**Comment by emersonknapp** [comment]
This feature is in progress and will be released into Humble. [Feature Request Ticket](https://github.com/ros2/rosbag2/issues/55) - see https://github.com/ros2/rosbag2/pull/847 for the in-progress implementation work. 

In Galactic, this feature was exposed via a Service on the playback node, so a simple custom "remote-control" client could be created. See a sample implementation of such a client here https://github.com/ros2/rosbag2/pull/729#issuecomment-819747652

I don't have Triage access on this repository to close this issue, but I recommend the maintainers do so as this is not a global ROS2 issue and is tracked locally on rosbag2

**Comment by liuxw7** [comment]
I got it, thanks a lot!

**Comment by GPrathap** [comment]
In Humble: Pause the playback: Press the Spacebar to pause the playback
