### ISSUE TITLE
release-foxy-20210902 has wrong file extension for windows

### ISSUE THREAD

**Issue by wmmc88** [ros2/ros2#1192]
## Bug report

**Required Info:**

- Operating System:
  - Windows 
- Version or commit hash:
  - release-foxy-20210902

#### Steps to reproduce issue
The binaries for windows released [here](https://github.com/ros2/ros2/releases/tag/release-foxy-20210902) are listed as `.tar.bz2`, but when you try to extract them, there's an error saying that the file is actually a zip, not a bz2 archive. I noticed this when trying to update `action/setup-ros` to use the latest binary releases for windows.

7zip GUI:
![image](https://user-images.githubusercontent.com/16629657/134791442-f6734851-a709-4585-8fc8-c8af77db9cdb.png)

7zip CLI:
![image](https://user-images.githubusercontent.com/16629657/134791454-f4ea2153-f50b-4df3-a1c9-1874e66bd567.png)

#### Expected behavior
Windows binary releases are zips, and should be named as such.

#### Actual behavior
Windows binary releases wrongfully have `.tar.bz2` extensions.

#### Additional information
@jacobperron you seem to be the one doing the releases for foxy

**Comment by jacobperron** [comment]
Thank you for the report! I've renamed the files to have the `.zip` suffix. Let me know if there are further issues.
