### ISSUE TITLE
Failed to fetch http://repo.ros2.org/ubuntu/main/dists/focal/InRelease

### ISSUE THREAD

**Issue by solid-sinusoid** [ros2/ros2#1216]
After last updates for ROS2 Foxy i have some warnings when run `sudo apt update`
```
W: Failed to fetch http://repo.ros2.org/ubuntu/main/dists/focal/InRelease  Could not connect to repo.ros2.org:80 (99.83.154.118). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by gavanderhoorn** [comment]
Perhaps [ROS2.org down?](https://discourse.ros.org/t/ros2-org-down/23005)?

**Comment by solid-sinusoid** [comment]
As I understand it, I need to wait for the servers to work. Thanks for the quick response. I will track the topic on ROS Discourse

**Comment by Jimmy030219** [comment]
wait until it feedback is ok
