### ISSUE TITLE
Question about preallocation for sensor_msgs/Image

### ISSUE THREAD

**Issue by advancenOO** [ros2/ros2#1217]
I could use uint8[<=N] in ros2 IDL to preallocate memory for arrays.
And I am wondering if I can preallocate for data(uint8[]) field of sensor_msgs/Image?

**Comment by advancenOO** [comment]
I am using ROS2 eloquent with fastrtps, and I find preallocation for sensor_msgs/Image is 0 according to int8_multi_array__type_support.cpp.

**Comment by clalancette** [comment]
As it stands, no that is not possible.  If you want a preallocated Image-like message, you'll have to define your own `.msg` file that has the appropriate amount of space for the image you want to transfer.

In the future, please open questions like this on https://answers.ros.org .  That's our central questions-and-answers site, and will archive the answer for future searching.  I'm going to close this one out for now.
