### ISSUE TITLE
 i got the following error

### ISSUE THREAD

**Issue by VanThanBK** [ros2/ros2#1218]
i got the following error: 
Summary: 120 packages finished [1min 28s]
  1 package failed: rviz_rendering
  3 packages aborted: rcutils rosidl_generator_dds_idl test_launch_testing
  27 packages had stderr output: ament_clang_format ament_clang_tidy ament_copyright ament_cppcheck ament_cpplint ament_flake8 ament_index_python ament_lint ament_lint_cmake ament_mypy ament_package ament_pclint ament_pep257 ament_pycodestyle ament_pyflakes ament_uncrustify ament_xmllint domain_coordinator launch launch_testing launch_xml launch_yaml osrf_pycommon rosidl_cli rpyutils tracetools_read tracetools_trace
  207 packages not processed

When: run "colcon build --merge-install" on windown 10
Sincere thanks when someone helps me fix it

**Comment by clalancette** [comment]
For questions like this, please post them on https://answers.ros.org, which is our centralized questions-and-answers site.  Github tickets should only be for known issues.  For that reason, I'm going to close this out.  Thanks for your understanding.
