### ISSUE TITLE
Transition Rolling to Ubuntu 22.04

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/ros2#1221]
Continuing from the broad announcement on Discourse. Here's a detailed checklist of items to take care of for the Rolling transition to Ubuntu 22.04.
- [x] Create bootstrap repositories for `jammy` and `bullseye`
- [x] Create ROS 2 repositories for `jammy` and `bullseye`
- [ ] Create osrf qemu-user-static images https://github.com/osrf/multiarch-docker-image-generation/pull/40
  - [x] osrf/ubuntu_arm64:jammy
  - [x] osrf/debian_arm64:bullseye 
- [x] Add Ubuntu Jammy support to [ros2/ci](https://github.com/ros2/ci) https://github.com/ros2/ci/pull/598
  - [x] Use ConnextDDS 6 on Jammy and Windows when targeting Rolling https://github.com/ros2/ci/pull/614
- [ ] ~~Prepare a Nightly Ubuntu Jammy debug build for the ROS 2 build farm in [ros2/ros_buildfarm_config](https://github.com/ros2/ros_buildfarm_config)~~
  - CI and devel jobs currently require a ros-$rosdistro-workspace package to be present unconditionally.
- [x] Prepare updates to rosdep database to make sure that dependencies are met on Ubuntu Jammy
- [x] Perform a test migration of ROS 2 Rolling to its new target platforms
- [x] Perform the migration of ROS 2 Rolling to its new target platforms https://github.com/ros/rosdistro/pull/32036
- [x] Update target platforms for build farm jobs: https://github.com/ros2/ros_buildfarm_config/issues/207
- [x] Update the default platforms for Rolling jobs in [ros2/ci](https://github.com/ros2/ci) https://github.com/ros2/ci/pull/616

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-ros-2-rolling-for-the-transition-to-ubuntu-22-04/23124/1

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2021-11-18/23209/1

**Comment by nbbrooks** [comment]
What is the latest (rough) timeline for this? The original discourse post talked about end of January, is this going to end up happening closer to the Humble release?

**Comment by clalancette** [comment]
> What is the latest (rough) timeline for this? The original discourse post talked about end of January, is this going to end up happening closer to the Humble release?

Still shooting for the end of January.  Given the work we had to do, this may end up slipping into the first week of February, but likely no longer than that.

**Comment by nbbrooks** [comment]
Thanks Chris, I just realized I was looking at the Dec notes, not Jan, where this was all written up. https://discourse.ros.org/t/ros-2-tsc-meeting-january-20th-2022/23986

**Comment by nuclearsandwich** [comment]
I opened this issue and completely forgot to update it as I went. Some bootstrapping challenges with the Jammy debug job have arisen and devel jobs can't run without binary jobs at the foundation so the last several tasks will all tick over to Jammy in a short fell swoop.

**Comment by clalancette** [comment]
@nuclearsandwich Can we close this one out now?

**Comment by clalancette** [comment]
Rolling is well and truly on Jammy now (despite some lingering jobs left on Focal).  As such, I'm going to close this out, but feel free to reopen if this issue is still needed.
