### ISSUE TITLE
ROS 2 Galactic : Problems with security plugins

### ISSUE THREAD

**Issue by piaopiaohu123** [ros2/ros2#1223]
## Bug report

**Required Info:**

- Operating System:
  Ubuntu 16.04
- Installation type:
  source
- Version or commit hash:
  ROS2 Galactic
- DDS implementation:
  Fast-RTPS
- Client library (if applicable):
  rcljava

#### Steps to reproduce issue
 i`m doing some development on android ,  and found rcljava lib missed, so when i integrade rcljava and the example on android, and set security from OFF to ON, but Fast-RTPS need to build openssl again on arm64-v8 for android10  NDK21.3,
 offer course, miss description in doc.

#### Expected behavior
  do we have any plan to integrade rcljava? and improve the description for android, thanks.
  refer to: https://github.com/ros2-java/ros2_java

**Comment by clalancette** [comment]
We're no planning to integrate rcljava into the main repositories, no.  For better Android support in general in rcljava, please open an issue on https://github.com/ros2-java/ros2_java
