### ISSUE TITLE
How to generate  installation packages (eg: ros-rolling-desktop.deb, ros-rolling-common.deb,  or whl, rpm etc..) for linux 

### ISSUE THREAD

**Issue by lasyka** [ros2/ros2#1226]
Hi guys:
  - Operating System:
       kali-rolling on an arm board machine
- Installation type:
  -  from source 
  - 
  The offical supported OS like ubuntu,debian can install from package,
  just use this command:
       ```sudo apt install ros-rolling-desktop```  
 
 But others os are not so lucky, they have to build and install ros2 from souce code,  
 this porject is so big,  compile it is a hard and slowly job.

 How to generate setup packages from source code (eg: deb, whl  etc..) for linux 
 then it can be install to the same machine,  avoid to compile it again and again.
  
 Is there a commad like:   ```colcon package deb```   for  generate a deb installer package.
 then use : dpkg -i xxxx.deb  to install it on other machines.
 like the offical does : ```sudo apt install ros-rolling-desktop``` ?

**Comment by tfoote** [comment]
In general please ask questions on https://answers.ros.org it's the best place for people to find and get answers from the whole community. I'm going to close this out but you can see that there's already a bunch of questions there relevant. If they don't answer your question please ask a new one there with as much detail as possible. 

Building the packages for different targets is a long process which takes a lot of maintenance and attention. The tools that we use to generate the debian packages are all open source. The main repository is here: https://github.com/ros-infrastructure/ros_buildfarm 

We very carefully curate what platforms we target to balance the effort versus the benefits. You can see the current state here: https://www.ros.org/reps/rep-2000.html

If you want a quick solution that just works from your workspace there are tools like [checkinstall](https://wiki.debian.org/CheckInstall) which can capture the output of installation actions and build packages. 

There are also a lot of Q&A questions like this: 

* https://answers.ros.org/question/192419/how-to-setup-bloom-to-generate-a-local-deb-outside-of-rosorg-buildfarm/
* https://answers.ros.org/question/356310/how-to-build-ros-deb-packages-by-myself/
* https://stackoverflow.com/questions/37249417/how-to-generate-deb-from-catkin-workspace-in-ros
* https://answers.ros.org/question/163281/how-do-i-build-deb-for-a-ros-package/

And there are many alternative approaches too. 
* https://github.com/mikepurvis/ros-bundling

Or you can switch to alternative installers: 
* https://discourse.ros.org/t/robostack-using-ros-alongside-the-conda-and-jupyter-ecosystems-on-any-linux-macos-windows-arm/20250
