### ISSUE TITLE
I can't save a recording of a topic in .bag

### ISSUE THREAD

**Issue by alvaropascuaI** [ros2/ros2#1251]
## Bug report
I'm trying to save a ros topic and by default it saves it in a .db3 file, I've tried changing the -s but I only get the sqlite3 and my_test_plugin option, I've also seen that there is an option to pass it to ros1 but I It's scary to have two versions of ros on the same computer, and I want the .bag so I can later generate a 3d model, could I do it with the .db3 or how do I get it to save in .bag with ros foxy and ubuntu 20.04?

**Required Info:**

- Operating System:
   Ubuntu 20.04
- Installation type:
   Ros Version: foxy-release

**Comment by clalancette** [comment]
For usage questions like this, please as on https://answers.ros.org, which is our central questions and answers site. You'll be more likely to get an answer there, and it will be searchable in the future.  Make sure to give lots of details on what you have installed (which you've done here), as well as which commands you are running.
