### ISSUE TITLE
Interface packages on ROS buildfarm aren't inheriting exported dependencies from rosidl generators

### ISSUE THREAD

**Issue by sloretz** [ros2/ros2#1252]
I think this is the root cause of https://build.ros2.org/job/Rbin_uJ64__rmw_cyclonedds_cpp__ubuntu_jammy_amd64__binary/23/console

`rmw_cyclonedds` has a build dependency that's only expressed through group dependencies. Bloom doesn't support those, so it can't be built on the buildfarm.

## Detailed description

As a consequence of the rosidl pipeline structure, `rmw_cyclonedds` needs to `find_package(fastrtps_cmake_module)` at build time. Here's why

* [`rmw_cyclone_dds` calls `find_package(rmw_dds_common REQUIRED)`](https://github.com/ros2/rmw_cyclonedds/blob/f9f211f34151bb4bbaf4fae17072537559b4dab7/rmw_cyclonedds_cpp/CMakeLists.txt#L52)
* [`rmw_dds_common` calls `rosidl_generate_interfaces`](https://github.com/ros2/rmw_dds_common/blob/4e58ec507cca906fe2ce323bb0fb91b5df4bf550/rmw_dds_common/CMakeLists.txt#L25-L30)
* ...skipping a lot of CMake that causes all rosidl generators to get invoked...
* First looking at the `rosidl_typesupport_fastrtps_c` generator:
  * [`rosidl_typesupport_fastrtps_c` generates a library `...__rosidl_typesupport_fastrtps_c`](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/89b19c15d615fc07479707e6584e29b1f67f5e23/rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake#L104-L105)
  * That library [includes `fastcdr/Cdr.h`](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/89b19c15d615fc07479707e6584e29b1f67f5e23/rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em#L33)
  * so [the generated library must link against `fastcdr`](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/89b19c15d615fc07479707e6584e29b1f67f5e23/rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake#L116)
    * note: it could be a `PRIVATE` dependency in this generator, but it wouldn't make a difference because CMake would still reference it with [`$<LINK_ONLY:fastcdr>`](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#genex:LINK_ONLY)
  * The [generated target gets exported](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/89b19c15d615fc07479707e6584e29b1f67f5e23/rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake#L163-L165)
  * Since the exported target links with `fastcdr`, the export file for the generated target will set `INTERFACE_LINK_LIBRARIES` to contain `fastcdr`. CMake will check for the `fastcdr` target's existence. If it doesn't exist, CMake fails the build. The only way around that is to make sure the target exists by `find_package()`ing it before referencing it. The `rosidl_typesupport_fastrtps_cpp` generator does that by [calling `ament_export_dependencies()` on `fastrtps_cmake_module` and `fastcdr`](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/89b19c15d615fc07479707e6584e29b1f67f5e23/rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake#L175-L176)
*  `rosidl_typesupport_fastrtps_cpp` generator is very similar, except it includes `fastcdr/Cdr.h` in a public header of the generated target

The dependency is expressed by group dependencies, but bloom doesn't support those. If bloom did, this is how it would work.

* [`rmw_cyclonedds` `<depend>`'s on `rmw_dds_common`](https://github.com/ros2/rmw_cyclonedds/blob/f9f211f34151bb4bbaf4fae17072537559b4dab7/rmw_cyclonedds_cpp/package.xml#L19)
* [`rmw_dds_common` `<buildtool_depend>`'s on `rosidl_default_generators`](https://github.com/ros2/rmw_dds_common/blob/4e58ec507cca906fe2ce323bb0fb91b5df4bf550/rmw_dds_common/package.xml#L12)
* [`rosidl_default_generators` `<group_depend>`'s on `rosidl_typesupport_c_packages` and `rosidl_typesupport_cpp_packages`](https://github.com/ros2/rosidl_defaults/blob/6665e8848389f2c67d7c68ce7c53ca957ebcc97e/rosidl_default_generators/package.xml#L29-L30)
* [`rosidl_typesupport_fastrtps_c` is a `<member_of_group>` `rosidl_typesupport_c_packages`](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/89b19c15d615fc07479707e6584e29b1f67f5e23/rosidl_typesupport_fastrtps_c/package.xml#L51)
  * [`rosidl_typesupport_fastrtps_c` `<buildtool_export_depend>`'s `fastrtps_cmake_module`](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/89b19c15d615fc07479707e6584e29b1f67f5e23/rosidl_typesupport_fastrtps_c/package.xml#L22) - therefore `rmw_cyclonedds` has a build-time dependency on `fastrtps_cmake_module` and it should be installed
* [`rosidl_typesupport_fastrtps_cpp` is a `<member_of_group>` `rosidl_typesupport_cpp_packages`](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/89b19c15d615fc07479707e6584e29b1f67f5e23/rosidl_typesupport_fastrtps_cpp/package.xml#L51)
  * [`rosidl_typesupport_fastrtps_cpp` `<buildtool_export_depend>`'s `fastrtps_cmake_module`](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/89b19c15d615fc07479707e6584e29b1f67f5e23/rosidl_typesupport_fastrtps_cpp/package.xml#L19) - therefore `rmw_cyclonedds` has a build-time dependency on `fastrtps_cmake_module` and it should be installed

### Make bloom support group dependencies

I have no idea how much work it would take.

### Unroll the group dependency in a package the interface packages will depend on

It looks like [`rosidl_typesupport` already has a workaround  in it's `package.xml` for bloom not supporting group dependencies](https://github.com/ros2/rosidl_typesupport/blob/1e5560a46a9dee79cec7815c35020b97008ea379/rosidl_typesupport_c/package.xml#L20-L25)

```xml
  <!--
  Bloom does not support group_depend so entries below duplicate the group rosidl_typesupport_c_packages.
  This ensures that binary packages have support for all of these rmw impl. enabled.
  -->
  <build_depend>rosidl_typesupport_introspection_c</build_depend>
  <!-- end of group rosidl_typesupport_c_packages for bloom -->
```

Maybe the same trick could be done by adding `rosidl_typesupport_fastrtps_c` and `rosidl_typesupport_fastrtps_cpp` to [`rosidl_default_generators` and `rosidl_default_runtime`](https://github.com/ros2/rosidl_defaults/blob/master/rosidl_default_generators/package.xml)?

### Move the interface generation out of rmw_dds_common and into the rmw packages

Since `rmw_dds_common` generates messages it depends on all typesupports. That means every rmw implementation has a build dependency on every other's typesupports. Maybe each rmw implementation could generate its own messages instead, using just its own type support's generators.

**Comment by sloretz** [comment]
> Before giving some opinions on the options, let me ask a question. Prior to https://github.com/ros2/rmw_dds_common/pull/57 being merged, this wasn't an issue. Do you understand why that PR caused this?

That was the previous issue, the one where `rmw_cyclonedds_cpp` failed to build because the target `rosidl_typesupport_c::rosidl_typesupport_c` didn't exist. The new release of `rosidl_typesupport` fixed that. [`rosidl_typesupport_c` needed to be `ament_export_dependencies()`'d so `rmw_cyclonedds_cpp` would automatically `find_package()` it and the target would exist](https://github.com/ros2/rosidl_typesupport/blob/1e5560a46a9dee79cec7815c35020b97008ea379/rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp_generate_interfaces.cmake#L159).

**Comment by clalancette** [comment]
After discussing this, we decided to go with option 2, which is unrolling group dependencies in rosidl_default_generators.  That should make this work for now, and future work should improve the situation in general.

**Comment by clalancette** [comment]
Since we ended up merging this for Humble, I'm going to close.  We still have the longer-term issue of really supporting group dependencies, but I don't think we should track it in this issue.  Feel free to reopen if you disagree.
