### ISSUE TITLE
How to query the existing ROS in the current LAN_ DOMAIN_ ID to ensure the newly generated ROS_ DOMAIN_ ID will not be repeated.

### ISSUE THREAD

**Issue by TreeGrow** [ros2/ros2#1255]

**Comment by fujitatomoya** [comment]
We have a right place to ask questions like this at [https://answers.ros.org](https://urldefense.com/v3/__https:/answers.ros.org__;!!JmoZiZGBv3RvKRSx!ujQsY6yh-oZpHN7gUK0EtP0o3CLrEK3iGjaFfOcT-e-ECJIgcD6fQ_ZALg70O_9y34I$), which is our central question and answers site.
That way it will be saved and searchable in the future.
Closing this out for now.

**Comment by clalancette** [comment]
Closing based on previous comment.
