### ISSUE TITLE
BUILD ERROR: the following packages/stacks could not have their rosdep keys resolved

### ISSUE THREAD

**Issue by WolfTom34** [ros2/ros2#1260]
Debian 11 bullseye 
Ros2 Galactic

when I run "rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y"  it's return this error 

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
ros2doctor: No definition of [python3-ifcfg] for OS version [bullseye]

How can I resolve it 
Thanks

**Comment by clalancette** [comment]
Please don't open the same issue on multiple repositories.  Closing as a duplicate of https://github.com/ros2/ros2_documentation/issues/2408
