### ISSUE TITLE
Galactic fails to build from source. Undefined variable __malloc_hook

### ISSUE THREAD

**Issue by git-user44** [ros2/ros2#1265]
## Bug report
Attempting to build ROS2 from source fails. __malloc_hook is undefined. Looking at the code, there are comments about ignoring warnings about deprecated code. Well, ignore it no longer. It has gone, or at least, it no longer exists in Fedora Linux

Appears to be referenced in two source files.
~/ros2_galactic/src/ros2/realtime_support/tlsf_cpp/test/test_tlsf.cpp
~/ros2_galactic//src/ros2/demos/pendulum_control/src/pendulum_demo.cpp

- Operating System:
 Fedora 35

- Installation type:
 Build from source (at least - attempting to.)

- Version or commit hash:

#### Steps to reproduce issue

mkdir -p ~/ros2_galactic/src
cd ~/ros2_galactic
wget https://raw.githubusercontent.com/ros2/ros2/galactic/ros2.repos
vcs import src < ros2.repos
sudo rosdep init
rosdep update
rosdep install --from-paths src --ignore-src -y --skip-keys "fastcdr rti-connext-dds-5.3.1 urdfdom_headers"
colcon build --symlink-install

#### Expected behaviour
I would expect the source code to build cleanly.

#### Actual behaviour
`--- stderr: tlsf_cpp                                                              
/home/mike/ros2_galactic/src/ros2/realtime_support/tlsf_cpp/test/test_tlsf.cpp: In function ‘void* testing_malloc(size_t, const void*)’:
/home/mike/ros2_galactic/src/ros2/realtime_support/tlsf_cpp/test/test_tlsf.cpp:72:3: error: ‘__malloc_hook’ was not declared in this scope; did you mean ‘prev_malloc_hook’?
   72 |   __malloc_hook = prev_malloc_hook;
      |   ^~~~~~~~~~~~~
      |   prev_malloc_hook
/home/mike/ros2_galactic/src/ros2/realtime_support/tlsf_cpp/test/test_tlsf.cpp: In function ‘void init_malloc_hook()’:
/home/mike/ros2_galactic/src/ros2/realtime_support/tlsf_cpp/test/test_tlsf.cpp:89:22: error: ‘__malloc_hook’ was not declared in this scope; did you mean ‘prev_malloc_hook’?
   89 |   prev_malloc_hook = __malloc_hook;
      |                      ^~~~~~~~~~~~~
      |                      prev_malloc_hook
/home/mike/ros2_galactic/src/ros2/realtime_support/tlsf_cpp/test/test_tlsf.cpp: In function ‘void* operator new(std::size_t)’:
/home/mike/ros2_galactic/src/ros2/realtime_support/tlsf_cpp/test/test_tlsf.cpp:218:3: error: ‘__malloc_hook’ was not declared in this scope; did you mean ‘prev_malloc_hook’?
  218 |   __malloc_hook = prev_malloc_hook;
      |   ^~~~~~~~~~~~~
      |   prev_malloc_hook
/home/mike/ros2_galactic/src/ros2/realtime_support/tlsf_cpp/test/test_tlsf.cpp: In function ‘void operator delete(void*)’:
/home/mike/ros2_galactic/src/ros2/realtime_support/tlsf_cpp/test/test_tlsf.cpp:235:3: error: ‘__malloc_hook’ was not declared in this scope; did you mean ‘prev_malloc_hook’?
  235 |   __malloc_hook = prev_malloc_hook;
      |   ^~~~~~~~~~~~~
      |   prev_malloc_hook
gmake[2]: *** [CMakeFiles/test_tlsf__rmw_cyclonedds_cpp.dir/build.make:76: CMakeFiles/test_tlsf__rmw_cyclonedds_cpp.dir/test/test_tlsf.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:188: CMakeFiles/test_tlsf__rmw_cyclonedds_cpp.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< tlsf_cpp [32.2s, exited with code 2]
`

**Comment by clalancette** [comment]
Yes, this has been fixed in Humble, but not in Galactic.  I guess we could backport the fixes that are in https://github.com/ros2/realtime_support/pull/109 .  I *think* there was another fix somewhere else in the ROS 2 stack, but I can't remember at the moment.  If you'd like to open a PR backporting those fixes, I'd be happy to review.

**Comment by git-user44** [comment]
Sorry. I will wait for the next release - any day soon I guess.

I will close this issue.
