### ISSUE TITLE
ROS2 SERVICE CALL QUESTION

### ISSUE THREAD

**Issue by GrozaGabriel** [ros2/ros2#1273]
Hello, I have a question about the ros2 service call.
I could call the servomotors degrees from a code line
i have 4 servomotors and i want all servomotors to be called from one line
this is what I use now
![unknown](https://user-images.githubusercontent.com/79835978/169162986-ebc77a32-56dc-411b-8991-6f629d0439bb.png)
 I want to  make a service that sets all 4 motors instead of creating one service per motor

**Comment by fujitatomoya** [comment]
Please ask questions like this at [https://answers.ros.org](https://urldefense.com/v3/__https:/answers.ros.org__;!!JmoZiZGBv3RvKRSx!ujQsY6yh-oZpHN7gUK0EtP0o3CLrEK3iGjaFfOcT-e-ECJIgcD6fQ_ZALg70O_9y34I$), which is our central question and answers site. That way it will be saved and searchable in the future.
