### ISSUE TITLE
Can ros 1 package access the robot description launched by ros 2?

### ISSUE THREAD

**Issue by Yitian-Xian** [ros2/ros2#1276]
Hi all, I am very new to ROS 2. Our research group is currently using the KUKA Med 7 version, and I found a nice package to control it in ROS 2: https://github.com/RViMLab/lbr_fri_ros2_stack. I am wondering when I launch the robot in ROS 2, can my ROS 1 package get the robot description data? Thanks a lot!

**Comment by fujitatomoya** [comment]
@Yitian-Xian Please open a question on [https://answers.ros.org](https://answers.ros.org/questions/), which is our central question and answer site. You should be able to get help there.

**Comment by Yitian-Xian** [comment]
@fujitatomoya Thank you for your reply!
