### ISSUE TITLE
Galactic can support cyclone-dds 0.9.1?

### ISSUE THREAD

**Issue by fengtuo58** [ros2/ros2#1281]
hi,  I use Galactic with cyclone-dds 0.8.0 and want to upgrade to cyclone-dds 0.9.1, are there problems ?
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by clalancette** [comment]
For questions like this, please ask on https://answers.ros.org, which is our central question and answer site.  You'll get a better answer there, and it will be searchable in the future.

Closing this one out.
