### ISSUE TITLE
Service Introspection

### ISSUE THREAD

**Issue by jacobperron** [ros2/ros2#1285]
This is a ticket to track work related to the service introspection feature proposed in https://github.com/ros-infrastructure/rep/pull/360

The high-level idea is to introduce service event messages that are published whenever a request or response is sent or received. Having service events available from topics makes it easy for users to inspect data flowing between services, aiding in debugging and validation. Please refer to the REP for details.

Here's a roadmap to implement the feature:
- [x] Add new event message types in code generation for services
  - [x] Add `service_msgs` package (https://github.com/ros2/rcl_interfaces/pull/143)
  - [x] Add dependency on `service_msgs` in `rosidl_defaults` for convenience (https://github.com/ros2/rosidl_defaults/pull/24)
  - Additions to code generation packages:
    - [x] https://github.com/ros2/rosidl/pull/700
    - [x] https://github.com/ros2/rosidl_typesupport_fastrtps/pull/92
    - [x] https://github.com/ros2/rosidl_typesupport/pull/127
    - [x] https://github.com/ros2/rosidl_python/pull/178
- [x] Integration with client libraries
  - [x] Add event message publishers to rcl services and clients (https://github.com/ros2/rcl/pull/997)
  - [x] rclcpp (https://github.com/ros2/rclcpp/pull/1985)
  - [x] rclpy (https://github.com/ros2/rclpy/pull/988)
  - [x] demos (https://github.com/ros2/demos/pull/602)
- [x] Add support to ros2service to echo service requests and responses (https://github.com/ros2/ros2cli/pull/745)
- [ ] Update existing tutorials (or add a new tutorial) related to services to use the new feature (https://github.com/ros2/ros2_documentation/pull/2981)

Related to https://github.com/ros2/rosbag2/issues/773 https://github.com/ros2/rosbag2/pull/1063

**Comment by ihasdapie** [comment]
Some initial prototyping work has been done in https://github.com/ros2/rcl/pull/990 which logs out serialized service introspection messages to `<service_name>/_service_event`. Limitations to this prototype are discussed in that PR.

Everything is under the `service_introspection-serialized` branch
- `rosidl_typesupport` (https://github.com/ros2/rosidl_typesupport/pull/125)
- `rcl_interfaces` (https://github.com/ros2/rcl_interfaces/pull/141)
- `rcl` (https://github.com/ros2/rcl/pull/990)

To test/reproduce:
1. Check out the corresponding branches
2. Build. If you're trying to run anything built with the client libraries you'll need to rebuild them too, i.e. `colcon build --packages-up-to rclcpp rclpy`
3. Run a service and inspect
    - `ros2 run demo_nodes_cpp add_two_ints_client`
    - `ros2 run demo_nodes_cpp add_two_ints_server`
    - `ros2 topic echo /add_two_ints/_service_event`
  
I've also made a fork of `demo_nodes_cpp`'s  add_two_ints demo which implements the trivial change of putting the client call in a `while true` loop [here](https://github.com/ihasdapie/ros2_demos/tree/loop_addtwoints_client) which may be handy while testing/debugging.

**Comment by ihasdapie** [comment]
Comment here to track related PRs:

Dependencies
- https://github.com/ros2/rosidl_defaults/pull/22
  -  https://github.com/ros2/rcl_interfaces/pull/144
  - https://github.com/ros2/unique_identifier_msgs/pull/23
  - https://github.com/ros2/geometry2/pull/547
  - https://github.com/ros2/example_interfaces/pull/16
  -  https://github.com/ros2/demos/pull/580
  - https://github.com/ros2/ros2cli/pull/743
  - https://github.com/ros2/ros2_documentation/pull/2913
 - 

Service Introspection PRs

-

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-9-15/27394/1

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-12-15/28840/1

**Comment by ivanpauno** [comment]
The following set of PRs are almost ready to get merged together:

- https://github.com/ros2/rosidl/pull/700
- https://github.com/ros2/rosidl_typesupport/pull/127
- https://github.com/ros2/rosidl_typesupport_fastrtps/pull/92
- https://github.com/ros2/rosidl_defaults/pull/24
- https://github.com/ros2/rcl_interfaces/pull/143

There's still [one comment](https://github.com/ros2/rcl_interfaces/pull/143#discussion_r1054821369) to be addressed before merging them.

After this round of PRs is merged, some minor changes will be needed in the remaining PRs, as there were some minor [API changes](https://github.com/ros2/rosidl/pull/700#discussion_r1054831129) (see [here](https://github.com/ros2/ros2/issues/1285#issuecomment-1209997582) for the complete list of PRs).

**Comment by clalancette** [comment]
I did some additional work on that set of PRs that Ivan pointed out.  Here's full CI with just those 5 PRs:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17988)](http://ci.ros2.org/job/ci_linux/17988/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12518)](http://ci.ros2.org/job/ci_linux-aarch64/12518/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18623)](http://ci.ros2.org/job/ci_windows/18623/)
* RHEL [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=299)](http://ci.ros2.org/job/ci_linux-rhel/299/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18624)](http://ci.ros2.org/job/ci_windows/18624/)

**Comment by Crola1702** [comment]
Some of these PRs are producing a build regression in Rci__nightly-cyclonedds_ubuntu_jammy_amd64:

Reference build: [Rci-cyclonedds#343](https://build.ros2.org/view/Rci/job/Rci__nightly-cyclonedds_ubuntu_jammy_amd64/343/)

Log output: 
```
--- stderr: action_msgs
In file included from /tmp/ws/install_isolated/rosidl_runtime_c/include/rosidl_runtime_c/rosidl_runtime_c/message_type_support_struct.h:19,
                 from /tmp/ws/build_isolated/action_msgs/rosidl_typesupport_cpp/action_msgs/srv/cancel_goal__type_support.cpp:6:
/tmp/ws/build_isolated/action_msgs/rosidl_typesupport_cpp/action_msgs/srv/cancel_goal__type_support.cpp: In function ‘const rosidl_message_type_support_t* rosidl_typesupport_cpp::get_message_type_support_handle() [with T = action_msgs::srv::CancelGoal_Event_<std::allocator<void> >; rosidl_message_type_support_t = rosidl_message_type_support_t]’:
/tmp/ws/build_isolated/action_msgs/rosidl_typesupport_cpp/action_msgs/srv/cancel_goal__type_support.cpp:100:60: error: ‘rosidl_typesupport_introspection_cpp__get_message_type_support_handle__action_msgs__srv__CancelGoal_Event’ was not declared in this scope; did you mean ‘rosidl_typesupport_introspection_cpp__get_message_type_support_handle__action_msgs__srv__CancelGoal_Request’?
  100 |   return ROSIDL_TYPESUPPORT_INTERFACE__MESSAGE_SYMBOL_NAME(rosidl_typesupport_introspection_cpp, action_msgs, srv, CancelGoal_Event)();
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/action_msgs__rosidl_typesupport_cpp.dir/build.make:144: CMakeFiles/action_msgs__rosidl_typesupport_cpp.dir/rosidl_typesupport_cpp/action_msgs/srv/cancel_goal__type_support.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:337: CMakeFiles/action_msgs__rosidl_typesupport_cpp.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< action_msgs [11.8s, exited with code 2]
```

It seems `...__action_msgs__srv__CancelGoal_Event` was not declared, so I think the problem might be related to the definition of EVENT message being [imported from rosidl_parser.definition](https://github.com/ros2/rosidl_typesupport_fastrtps/commit/19626742ef92c7bb55afed3e996cb004dc409e64#diff-22c7afd7e2af24d06549bb2de6f13a9bbb587987d8867226c73d8169b5d04340R11-R13) but not being added to [this conditional](https://github.com/ros2/rosidl_typesupport_fastrtps/pull/92/files#diff-22c7afd7e2af24d06549bb2de6f13a9bbb587987d8867226c73d8169b5d04340R91-R96) (related to https://github.com/ros2/rosidl_typesupport_fastrtps/pull/92). 

What do you think @clalancette ?

**Comment by clalancette** [comment]
> What do you think @clalancette ?

That could be the problem.  I'll take a look today.

**Comment by clalancette** [comment]
All right, I've now gone ahead and done a substantial rewrite of the next batch of PRs.  This batch adds in support for service introspection at the rcl, rclpy, and rclcpp layers, while also adding demos showing how to use it.  As such, the following PRs are ready for review (and must all be merged together):

* https://github.com/ros2/rcl/pull/997
* https://github.com/ros2/rclpy/pull/988
* https://github.com/ros2/rclcpp/pull/1985
* https://github.com/ros2/demos/pull/602

Here's CI for the lot of them:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18091)](http://ci.ros2.org/job/ci_linux/18091/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12623)](http://ci.ros2.org/job/ci_linux-aarch64/12623/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18735)](http://ci.ros2.org/job/ci_windows/18735/)

@mjcarroll FYI when you have a chance

**Comment by clalancette** [comment]
The yellow tests here are all from different sources, so as far as this PR is concerned, everything is clean.  Also, all of the PRs in the previous comment are now approved.  So I'm going to go ahead and merge that batch in.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-03-16/30432/1

**Comment by fujitatomoya** [comment]
https://github.com/ros2/ros2_documentation/pull/4199 to close this issue, adding CLI tutorial and Service Introspection tutorial.

**Comment by clalancette** [comment]
We finally finished this issue, so closing this out.
