### ISSUE TITLE
moveit-setup-assisant 

### ISSUE THREAD

**Issue by andy2990** [ros2/ros2#1290]
## Bug report

**Required Info:**

- Operating System:ubuntu22.04
  - 
- Installation type:binaries
  - 
- Version or commit hash:humble
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```
i have installed the ros-humble-moveit-setup-assisant using "sudo apt install ros-humble-moveit-setup-assisant".
then i ran the command "ros2 launch moveit-setup-assistant setup-assistan.launch"
```

#### Expected behavior
show the moveit-setup-assistant interface
#### Actual behavior
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [launch]: Error trying to process rule "substitution":
Unknown substitution: arg
#### Additional information

----

**Comment by fujitatomoya** [comment]
I think this issue should be moved to https://github.com/ros-planning/moveit/tree/master/moveit_setup_assistant.

**Comment by fujitatomoya** [comment]
CC: @clalancette

**Comment by clalancette** [comment]
Yes, agreed.  Please open an issue on https://github.com/ros-planning/moveit .  Closing this out.
