### ISSUE TITLE
How to properly include static library and header files in package.

### ISSUE THREAD

**Issue by chriseyhorn** [ros2/ros2#1299]
My project structure is currently the following with precompiled libs and header files in the root of the workspace.

```
📦ros2_workspace
 ┣ 📂include
 ┃ ┣ 📂bar
 ┃ ┃ ┗ 📜bar-header-a.h
 ┃ ┗ 📂foo
 ┃ ┃ ┣ 📜foo-header-a.h
 ┃ ┃ ┗ 📜foo-header-b.h
 ┣ 📂lib
 ┃ ┣ 📜libbar.so
 ┃ ┗ 📜libfoo.a
 ┗ 📂src
      ┗ 📂my_package
          ┣ 📂include
          ┃ ┗ 📂my_package
          ┣ 📂src
          ┃ ┗ 📜my_node.cpp
          ┣ 📜CMakeLists.txt
          ┗ 📜package.xml
```
What is the proper Ros2 way of registering these with cmake, ament and package.xml files so they can be linked and the headers are found during development?

Many thanks in advance!

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.
