### ISSUE TITLE
Configure and Enable clang_format QA tool

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#13]
We have a tools for checking our code with `clang_format` but it is not configured to our liking yet.

Acceptance Criteria:
- [ ] Decide on a configuration with the team
- [ ] Reenable the linter
- [ ] Create tasks for fixing failing packages

**Comment by dirk-thomas** [comment]
A `clang_format` linter is available now but collides with uncrustify and therefore hasn't been activated yet: ament/ament_lint/issues/146

Closing this ticket in favor of the more specific one on `ament_lint`.
