### ISSUE TITLE
ROS2 python does not find modules of local workspace

### ISSUE THREAD

**Issue by fnobis** [ros2/ros2#1307]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - apt installation
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue
I have a ros2 python package which I call `package1. I want to import a function of it to another python ros2 package which I call 'package2`.

So in my python script in package2 I have the line:
`from package1.helpers import helper_function`

When running package2, I get the message `No module named 'package1.helpers`.

I would expect ros takes care of these dependencies. When I do a manual: pip install -e `package1` The module is found. But when sources the ros workspace it does not work. Is there a way for ros to handle this automatically? Not sure if this is a bug and should function in ros already or a feature request, but I did not find anything in the documentation about this.

**Comment by clalancette** [comment]
Yes, this will all work as expected if you setup the package properly and source your workspace.  I'll suggest you repost this question to https://answers.ros.org, with exact details on how you have the package setup.  Someone there will be able to help you setup your Python package properly, and it will be saved and searchable in the future.
