### ISSUE TITLE
Migrating ROS2 Foxy project to Humble

### ISSUE THREAD

**Issue by im-renpei** [ros2/ros2#1309]
Hi, can I directly switch the ROS2 environment of our project from Foxy to the Humble (Ubuntu 20.04, Python 3.8.10)?

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
