### ISSUE TITLE
Alpha 2 release (2015-10-30)

### ISSUE THREAD

**Issue by esteve** [ros2/ros2#131]
- [x] Support for custom allocators in rclcpp
 - [x] Useful for real-time messaging
- [x] Feature parity of Windows with Linux/OSX
 - [x] Workspace management
 - [x] Services:
    - [x] OpenSplice https://github.com/ros2/system_tests/pull/42
    - [x] RTI Connext
 - [x] Parameters:
    - [x] OpenSplice https://github.com/ros2/system_tests/pull/44
    - [x] RTI Connext
- [ ] rclcpp API improvements
  - [x] `std::unique_ptr` and `std::shared_ptr` unified API for `create_subscription` https://github.com/ros2/rclcpp/pull/131
  - [ ] Change `create_publisher`/`create_subscription` to `advertise`/`subscribe` https://github.com/ros2/design/issues/56#issuecomment-149368132
 - [ ] Change instances of `Subscription` to `Subscriber` (no pr or issue comment to link to)
- [x] FreeRTPS improvements:
 - [x] Fragmentation of large messages (on the sending side)
 - [x] Camera demo

--

Moved to the next alpha:

- [ ] Support for FastRTPS
 - [ ] At least on Linux
 - Missing support for large message fragmentation
- [ ] Refactor rclcpp into a library
 - [ ] Requires resolution of Windows lazy symbolism

**Comment by flobotics** [comment]
hi,
is 2016-10-30 really true ?


flo

**Comment by dirk-thomas** [comment]
No, it should be 2015.
