### ISSUE TITLE
Error building on windows 10 with Cmake 3.24.0

### ISSUE THREAD

**Issue by GiladRobee** [ros2/ros2#1311]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10 IOT
- Installation type:
  - binaries
- Version or commit hash:
  - [ros2-humble-20220523-windows-release-amd64.zip](https://github.com/ros2/ros2/releases/download/release-humble-20220523/ros2-humble-20220523-windows-release-amd64.zip)
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
followed installation steps: https://docs.ros.org/en/humble/Installation/Windows-Install-Binary.html then built by:
```
 colcon build --event-handlers console_cohesion+
```

#### Expected behavior
build complete successfully
#### Actual behavior
Call Stack (most recent call first):
  C:/dev/release/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:48 (include)
  C:/dev/release/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:286 (ament_execute_extensions)
  CMakeLists.txt:15 (rosidl_generate_interfaces)
#### Additional information
this problem was solved after i reverted the cmake version from 3.24.0 to 3.23.0 and was able to successfully build all packages.
please advise in installation page to download the specific cmake version or modify colcon build to fit new versions.

Best regards

**Comment by clalancette** [comment]
This was already reported on https://github.com/ament/ament_cmake/issues/396 and will be fixed by https://github.com/ament/ament_cmake/pull/395 , so closing this as a duplicate.
