### ISSUE TITLE
Foxy. Messages. Bug. Is header reserved word?! 

### ISSUE THREAD

**Issue by DrShIkIgAmy** [ros2/ros2#1324]
I've found some interesting behavior in message field processing.
For instance, I have some custom message (lets call it **_FirstMsg_**) and I would like to create another custom msg (_**SecondMsg**_). And I'm dying to make **_SecondMsg_** contains field "_FirstMsg header_". Guess what? I'm not permitted to do this, 'cause it leads to an error **"const auto stamp = m.header.stamp;"**.
It happens because "**ros_foxy/include/libstatistics_collector/topic_statistics_collector/received_message_age.hpp**" triggers on field name "**header**".
![image](https://user-images.githubusercontent.com/62403955/190167692-b0056207-e09e-4252-bbc5-1059e6294f3c.png)
That way, I must make field named "header" to contain member "stamp" or I have to rename the field.
The bug was discovered, while I was trying to create subscription on custom msg, which header is not std header.

**Comment by jacobperron** [comment]
Thanks for the bug report. I think this is a duplicate report of https://github.com/ros-tooling/libstatistics_collector/issues/51, which I suspect affects all supported ROS 2 distributions (not only Foxy).

There's a PR open to fix the issue, but it seems to have lost momentum: https://github.com/ros-tooling/libstatistics_collector/pull/54

I'm going to close this ticket in favor of keeping discussion on the above referenced tickest.
