### ISSUE TITLE
issue in installing humble RPM packages in RHEL 8.6

### ISSUE THREAD

**Issue by cwrx777** [ros2/ros2#1325]
## Bug report

**Required Info:**

- Operating System:
  - RHEL 8.6
- Installation type:
  - [RPM](https://docs.ros.org/en/humble/Installation/RHEL-Install-RPMs.html#install-ros-2-packages)

#### Steps to reproduce issue
```bash
sudo dnf install ros-humble-desktop
```

#### Expected behavior
Successful installation.

#### Actual behavior
```
Error:
 Problem: package ros-humble-desktop-0.10.0-1.el8.20220808.171503.x86_64 requires ros-humble-pcl-conversions, but none of the providers can be installed
  - conflicting requests
  - nothing provides pcl-devel needed by ros-humble-pcl-conversions-2.4.0-4.el8.20220729.172910.x86_64
```

#### Steps to reproduce issue
```bash
sudo dnf install ros-humble-ros-base
```

#### Expected behavior
Successful installation.

#### Actual behavior
```
Error:
 Problem: package ros-humble-ros-base-0.10.0-1.el8.20220808.153211.x86_64 requires ros-humble-urdf, but none of the providers can be installed
  - package ros-humble-urdf-2.6.0-2.el8.20220727.055146.x86_64 requires ros-humble-urdfdom, but none of the providers can be installed
  - conflicting requests
  - nothing provides console-bridge-devel needed by ros-humble-urdfdom-3.0.2-2.el8.20220726.195637.x86_64
  - nothing provides tinyxml-devel needed by ros-humble-urdfdom-3.0.2-2.el8.20220726.195637.x86_64
```

**Comment by cottsay** [comment]
All of the missing packages listed here are part of the EPEL repository.

Please ensure that epel and CRB/PowerTools are enabled on your system, as described int he installation instructions: https://docs.ros.org/en/humble/Installation/RHEL-Install-RPMs.html#setup-sources

**Comment by cwrx777** [comment]
I was not able to install power tools by following this instruction:
```
$ sudo dnf install 'dnf-command(config-manager)' epel-release -y
No match for argument: epel-release
```


and i followed [this ](https://access.redhat.com/discussions/5417621#comment-1986291)to install codeready.

**Comment by cwrx777** [comment]
update:
I managed to install epel-release by following [this](https://www.cyberciti.biz/faq/install-epel-repo-on-an-rhel-8-x/).
however, power-tools installation failed
```
$ sudo dnf config-manager --set-enabled powertools
Error: No matching repo to modify: powertools.
```

**Comment by cottsay** [comment]
We're tracking an update to the RHEL installation instructions already with this PR: ros2/ros2_documentation#2954
