### ISSUE TITLE
Installation under windows_Why should install vcredist2013 while next step installing VS2019?

### ISSUE THREAD

**Issue by fengweichangzi** [ros2/ros2#1326]
https://docs.ros.org/en/humble/Installation/Windows-Install-Binary.html

For the "Installation - Windows(binary)", why should we have to install vcredist2013? 

`choco install -y vcredist2013 vcredist140`

Because I saw the next step is "Install Install Visual Studio" with VS2019, then no need to install vcredist2013 anymore?

**Comment by clalancette** [comment]
I can't remember exactly why, but I do think it is necessary to install vcredist2013.

That said, if you give it a shot and it works without it, we'd like to hear about it.  Once you test it out, feel free to open a PR to https://github.com/ros2/ros2_documentation and we can discuss it.
