### ISSUE TITLE
macOS with ROS 2

### ISSUE THREAD

**Issue by AnasAltarazi1998** [ros2/ros2#1345]
I was following the ROS 2 documentation for macOS [documentation](https://docs.ros.org/en/crystal/Installation/macOS-Install-Binary.html), but when I reached to the section when I should download the ROS release for macOS I could not find any release for the macOS.
what should I do to find the release ?

**Comment by clalancette** [comment]
Crystal is long End-of-Life, and we don't provide binary packages for macOS anymore.  If you follow some more [up-to-date instructions](https://docs.ros.org/en/rolling/Installation/Alternatives/macOS-Development-Setup.html), you can attempt to build from source.
