### ISSUE TITLE
pinned memory

### ISSUE THREAD

**Issue by KevenLee** [ros2/ros2#1347]
I want to use cudaHostMalloc to malloc page locked memory and then send it as a message. How can I achieve this functionality? How to avoid explicit memory management and avoid memory leaks?

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
