### ISSUE TITLE
Ubuntu 22.04(jammy) various Errors in ROS2(humble) install HELP ME 

### ISSUE THREAD

**Issue by gitpass1** [ros2/ros2#1352]
![ERROR1](https://user-images.githubusercontent.com/119548895/204952954-81cb7453-ce12-49e1-ac77-c161d2f9f7a0.jpg)
![ERROR2](https://user-images.githubusercontent.com/119548895/204952959-89d5f1ff-3e1c-4582-9d8e-0dd5055d0263.jpg)

it's been a long time to struggling this hardship
I am trying to install ROS2(humble) in ubuntu 22.04.
while following ROS2 install manual. (copying some code in termial)    libc-bin error etc. keep blocking me.
already searched google and did some method but i couldn't solve the problem(even seems there aren't distinct solution)

( ↓ my fails)
apt-get -f install     →  error message can't open files
sudo apt-get reinstall libc-bin    →    E : Internal Error, No file name for libc-bin:arm64
root) rm /var/cache/ldconfig/aux-cache   →  No such file or directory

------------------------------------------------------------
I am beginner of beginner 
github Heros please help me

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
