### ISSUE TITLE
Improve handling of dynamic discovery

### ISSUE THREAD

**Issue by gbiggs** [ros2/ros2#1359]
In ROS 2 Iron Irwini, we hope to improve how discovery is managed by ROS 2. In brief:

- Broadcast discovery "distance" will be controllable by the user, in terms of off, localhost-only, and subnet-only.
- Discovery static peers will be easily specified by the user, allowing specific hosts to be discovered even when broadcast discovery is off.

For the full details, please see [this Discourse post](https://discourse.ros.org/t/proposed-changes-to-how-ros-performs-discovery-of-nodes/27640).

Below are the individual PRs that make up this feature.

- https://github.com/ros2/rcl/pull/1023
- https://github.com/ros2/rmw/pull/338
- https://github.com/ros2/rmw_fastrtps/pull/653
- https://github.com/ros2/rmw_cyclonedds/pull/429
- https://github.com/ros2/rmw_connextdds/pull/108
- https://github.com/ros/ros_environment/pull/37
- https://github.com/ros2/system_tests/pull/512

Current status - stuff that needs to be done
- Pre-RMW freeze
  - [x] Fast-DDS ignore_participant implementation merged: https://github.com/eProsima/Fast-DDS/pull/3412
    - Not needed with @sloretz's changes to how things work in rmw_fastrtps_cpp
  - [x] Add comments to rcl test: https://github.com/ros2/rcl/pull/1023#discussion_r1149555613
    - https://github.com/ros2/rcl/pull/1023#discussion_r1151446852
  - [x] Decide where IP addresses should be validated (What does it mean for an IP to be validated?) https://github.com/ros2/rcl/pull/1023#discussion_r1149927417
    - Not going to validate in rcl, leave to middleware, documented
  - [x] Decide if we should keep or delete `RMW_AUTOMATIC_DISCOVERY_RANGE_DEFAULT` https://github.com/ros2/rmw/pull/338#discussion_r1093863765
    - @sloretz addressed this
  - [x] Make sure all changes build on windows (checking rmw_fastrtps here: https://github.com/ros2/rmw_fastrtps/pull/653#issuecomment-1487762501)
  - [x] Maybe make error message more informative: https://github.com/ros2/rmw_cyclonedds/pull/429#discussion_r1150044394
  - [x] Address William's feedback on rmw_connextdds PR https://github.com/ros2/rmw_connextdds/pull/108#pullrequestreview-1360235720
  - [x] Resolve why ConnextDDS implementation not behaving as expected: https://github.com/ros2/rmw_connextdds/pull/108#issue-1618699773
    - @asorbini made a patch that should address this we think (thanks!)
- Post-RMW freeze
  - ROS 2 documentation about discovery options
  - ROS Iron release notes for discovery change
  - test_discovery - Add README for how to run root tests
  - test_discovery - add rosdep keys for pytest, mininet, etc.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-12-15/28840/1

**Comment by arjo129** [comment]
Work for this is going on here: https://github.com/osrf/iron_irwini_discovery_modes_prototype/pull/2

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2023-03-16/30432/1

**Comment by wjwwood** [comment]
- Decide if we should keep or delete RMW_AUTOMATIC_DISCOVERY_RANGE_DEFAULT https://github.com/ros2/rmw/pull/338#discussion_r1093863765
  - decision from @sloretz and I speaking off-line, we'll make a new `SYSTEM_DEFAULT` enum which delegates configuration to the xml config of the middleware you're using, and if no enum is set, then we'll use `LOCALHOST` (which is set at the `rcl` level if no env var is set and/or options in the discovery options struct passed to context init)
- Fast-DDS ignore_participant implementation merged: https://github.com/eProsima/Fast-DDS/pull/3412
  - @sloretz try an idea to not need `ignore_participant`, if that doesn't pan out...
  - @wjwwood to try running without Fast-DDS patch, to see what doesn't work, in the hope that we could merge with these known issues and get this Fast-DDS change later to fix them
  - If neither are ok, then we just try to get the Fast-DDS stuff merged

**Comment by sloretz** [comment]
Windows canary - building and testing all packages up to rcl (this build excludes rmw_connextdds and test_discovery) [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19031)](https://ci.ros2.org/job/ci_windows/19031/)

**Comment by sloretz** [comment]
Another Windows canary - testing `test_discovery`
[![Build Status](https://ci.ros2.org/job/ci_windows/19042/badge/icon)](https://ci.ros2.org/job/ci_windows/19042/)

GIST:  https://gist.github.com/sloretz/37e0a5eeecda22b56f5ca70874e6281e

**Comment by sloretz** [comment]
Full CI excluding connext

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18372)](http://ci.ros2.org/job/ci_linux/18372/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12909)](http://ci.ros2.org/job/ci_linux-aarch64/12909/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19043)](http://ci.ros2.org/job/ci_windows/19043/)

**Comment by sloretz** [comment]
Another full build excluding connext - this time seeing the affect of some improvements to rmw_fastrtps_*

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18373)](http://ci.ros2.org/job/ci_linux/18373/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12910)](http://ci.ros2.org/job/ci_linux-aarch64/12910/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19044)](http://ci.ros2.org/job/ci_windows/19044/)

**Comment by sloretz** [comment]
Targeted windows CI looking for more info on CycloneDDS test failures (build: `--packages-up-to test_communication test_discovery` test: `--packages-select test_communication test_discovery`, special repos file, only cyclonedds): [![Build Status](https://ci.ros2.org/job/ci_windows/19050/badge/icon)](https://ci.ros2.org/job/ci_windows/19050/)

Full CI (first one with connext changes!) to see where everything is after today's changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18379)](http://ci.ros2.org/job/ci_linux/18379/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12920)](http://ci.ros2.org/job/ci_linux-aarch64/12920/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19051)](http://ci.ros2.org/job/ci_windows/19051/)

**Comment by sloretz** [comment]
Full CI re-run with changes to rmw_cyclonedds

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18381)](http://ci.ros2.org/job/ci_linux/18381/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12922)](http://ci.ros2.org/job/ci_linux-aarch64/12922/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19053)](http://ci.ros2.org/job/ci_windows/19053/)

**Comment by sloretz** [comment]
Rurun again with changes to rmw_connextdds
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18382)](http://ci.ros2.org/job/ci_linux/18382/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12923)](http://ci.ros2.org/job/ci_linux-aarch64/12923/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19054)](http://ci.ros2.org/job/ci_windows/19054/)

**Comment by sloretz** [comment]
After making connext change, full CI excluding Cyclone since I'm seeing strange errors on windows with Cyclone

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18384)](http://ci.ros2.org/job/ci_linux/18384/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12926)](http://ci.ros2.org/job/ci_linux-aarch64/12926/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19056)](http://ci.ros2.org/job/ci_windows/19056/)

**Comment by sloretz** [comment]
Full CI, this time with all three RMW implementations, after making the change of the maximum participant ID to 32.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18424)](http://ci.ros2.org/job/ci_linux/18424/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12970)](http://ci.ros2.org/job/ci_linux-aarch64/12970/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19108)](http://ci.ros2.org/job/ci_windows/19108/)

**Comment by clalancette** [comment]
Just as an FYI, we also need https://github.com/ros/ros_environment/tree/gbiggs/discovery-peers-specification so we don't get a warning on every command:

```
[WARN] [1680633323.129234187] [rcl]: ROS_LOCALHOST_ONLY is deprecated. Use ROS_AUTOMATIC_DISCOVERY_RANGE and ROS_STATIC_PEERS instead.
```

I'll go ahead and open a PR with that change.

**Comment by clalancette** [comment]
I did some testing here with RMW_IMPLEMENTATION=rmw_connextdds and the set of PRs listed.  In my particular case, I had two different containers, with two different IP addresses on the same bridged network (subnet).  I then ran a talker in each container, and used the `ros2` command-line tools to do various pieces of introspection.

For the most part, things work as advertised.  By default, neither container could see the topics and nodes from the other one.  Adding in `ROS_STATIC_PEERS` for the IP address of the other container made them be able to discover each other and transfer data.

However, there is some weirdness around the `ros2daemon`.  In particular, when it initially launches, it launches with the environment of whichever command first needed it.  So, for instance, if you run `ros2 node list` with `ROS_STATIC_PEERS` unset initially, then it won't find nodes from the other container (as expected).  But if you then do `ROS_STATIC_PEERS=<IP> ros2 node list`, it *still* won't find nodes from the other container until you do a `ros2 daemon stop`, and then run the command again.  The problem happens in reverse as well.

I think we need a follow-up here where we have `ros2daemon` detect if the `ROS_STATIC_PEERS` and `ROS_AUTOMATIC_DISCOVERY_RANGE` are different from when it started, and restart itself if needed.

**Comment by sloretz** [comment]
test_launch_ros tests are hanging with rmw_fastrtps (increasing maxAutoParticipantIndex for rmw_fastrtps fixes it, but neither Cyclone nor Connext need the same increase), so tonight's CI is with Cyclone and connext, with Cyclone on the 0.10.x branch to see if that resolves the issues on windows

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18437)](http://ci.ros2.org/job/ci_linux/18437/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12983)](http://ci.ros2.org/job/ci_linux-aarch64/12983/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19121)](http://ci.ros2.org/job/ci_windows/19121/)

**Comment by sloretz** [comment]
Full CI tonight
* [repos file](https://gist.githubusercontent.com/sloretz/37e0a5eeecda22b56f5ca70874e6281e/raw/2ffd0ef6d9c95635d29b3520a3619cef65e370e5/test_discovery_oobe.repos)
* Includes https://github.com/eProsima/Fast-DDS/pull/3437
* Includes https://github.com/ros2/ros2/pull/1402


Jobs

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18451)](http://ci.ros2.org/job/ci_linux/18451/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12997)](http://ci.ros2.org/job/ci_linux-aarch64/12997/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19142)](http://ci.ros2.org/job/ci_windows/19142/)

**Comment by sloretz** [comment]
There are still some issues with the discovery range being Localhost
* With Fast-DDS, creating and deleting participants causes the participant ID to climb without limit https://github.com/eProsima/Fast-DDS/pull/3437
   * This is probably only a problem with large amounts of unit tests in a single process that create/delete contexts with overlap - like test_launch_ros
* With CycloneDDS, even after bumping to 0.10.x, there are lots of test failures on Windows where Cyclone can no longer send unicast discovery messages

As a workaround I've changed the default discovery range to SUBNET - which is the same as the current behavior, but with the ability to set static peers. I'm going to try full CI to see if that would be an option to get these changes in.
*  ros_environment: https://github.com/ros/ros_environment/pull/37/commits/c5d513f6b9ab560cb1a25c8ad0cb8df0099ab804
* rcl: https://github.com/ros2/rcl/pull/1023/commits/ee00c56c7a230520e1965c3e9528b7fef8af2a99

Jobs

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18462)](http://ci.ros2.org/job/ci_linux/18462/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13008)](http://ci.ros2.org/job/ci_linux-aarch64/13008/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19155)](http://ci.ros2.org/job/ci_windows/19155/)

**Comment by sloretz** [comment]
RHEL and Windows Debug full CI

* RHEL: [![Build Status](https://ci.ros2.org/job/ci_linux-rhel/367/badge/icon)](https://ci.ros2.org/job/ci_linux-rhel/367/)
* Windows Debug: [![Build Status](https://ci.ros2.org/job/ci_windows/19157/badge/icon)](https://ci.ros2.org/job/ci_windows/19157/)

**Comment by clalancette** [comment]
> As a workaround I've changed the default discovery range to SUBNET - which is the same as the current behavior, but with the ability to set static peers. I'm going to try full CI to see if that would be an option to get these changes in.

Just as a follow-up; @sloretz and I talked about this in-person, and I think getting this code in but leaving it as SUBNET is a good compromise for now.  Then we can consider fixing the issues for J-Turtle, and at that point changing the default to LOCALHOST.

**Comment by sloretz** [comment]
Full CI plus after pulling rolling changes and fixing warning on windows in rmw_connextdds_common

[repos file](https://gist.githubusercontent.com/sloretz/bdeaeba4134b79309dff7b3302114940/raw/8048fe8429416f5138e2c7caeefbbf23fad048fd/test_dds_oobe_pre_rmw_freeze.repos)


* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18468)](http://ci.ros2.org/job/ci_linux/18468/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13015)](http://ci.ros2.org/job/ci_linux-aarch64/13015/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19176)](http://ci.ros2.org/job/ci_windows/19176/)
* RHEL: [![Build Status](https://ci.ros2.org/job/ci_linux-rhel/373/badge/icon)](https://ci.ros2.org/job/ci_linux-rhel/373/)
* Windows debug: [![Build Status](https://ci.ros2.org/job/ci_windows/19175/badge/icon)](https://ci.ros2.org/job/ci_windows/19175/)

**Comment by sloretz** [comment]
Full CI - this time with Fast-DDS 2.10.x

[repos file](https://gist.githubusercontent.com/sloretz/bdeaeba4134b79309dff7b3302114940/raw/75e29892de53a792c61b7efda3edc7eb445de5c8/test_dds_oobe_pre_rmw_freeze.repos)

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18473)](http://ci.ros2.org/job/ci_linux/18473/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13020)](http://ci.ros2.org/job/ci_linux-aarch64/13020/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19184)](http://ci.ros2.org/job/ci_windows/19184/)
* RHEL [![Build Status](https://ci.ros2.org/job/ci_linux-rhel/378/badge/icon)](https://ci.ros2.org/job/ci_linux-rhel/378/)
* Windows Debug: Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19185)](http://ci.ros2.org/job/ci_windows/19185/)

**Comment by sloretz** [comment]
The only windows test [failure appears to be flaky on the nightly jobs](https://ci.ros2.org/view/nightly/job/nightly_win_rep/2951/testReport/junit/launch_testing_examples.launch_testing_examples/check_multiple_nodes_launch_test/launch_testing_examples_check_multiple_nodes_launch_test/history/) CI LGTM :tada:

**Comment by clalancette** [comment]
@sloretz @gbiggs @mxgrey @arjo129 Thank you so much for all of your work getting this in!

If I can make two more requests:
1. Add a release note to https://github.com/ros2/ros2_documentation/blob/rolling/source/Releases/Release-Iron-Irwini.rst explaining what this work is and what the changes are from Humble.
2. Close this issue, and open up a new one explaining the follow-up work to be done to make this work with LOCALHOST as the default.

**Comment by fujitatomoya** [comment]
> ROS 2 documentation about discovery options

https://github.com/ros2/ros2_documentation/pull/3596

> ROS Iron release notes for discovery change

https://github.com/ros2/ros2_documentation/pull/3519

**Comment by fujitatomoya** [comment]
@Yadunund i think we can close this.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/proposal-restrict-dds-to-localhost-by-default/36018/4
