### ISSUE TITLE
Writing an odometry publisher node in ros2 python

### ISSUE THREAD

**Issue by kleanbotmk2** [ros2/ros2#1363]
Hi,

I would like to know how to create an odometry publisher node in python ros2 that can publish on the topic nav_msgs/Odometry and TFs (base_link with respect to the Odom frame).

Could someone tell me how to do this?

Thanks in advance,

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
