### ISSUE TITLE
how should I install these packages from source?

### ISSUE THREAD

**Issue by RandyChen233** [ros2/ros2#1365]
After installing the packages mentioned from source ( [libsdl2.0.20+dfsg-2ubuntu1.22.04.1](https://launchpad.net/ubuntu/+source/libsdl2/2.0.20+dfsg-2ubuntu1.22.04.1) & [libsdl2-dev 2.0.20+dfsg-2ubuntu1.22.04.1 (arm64 binary)](https://launchpad.net/ubuntu/jammy/arm64/libsdl2-dev/2.0.20+dfsg-2ubuntu1.22.04.1) ), ROS 2 was installed successfully. The 2 packages are both proposed version, hence the dependency issue.

_Originally posted by @Bon-1900 in https://github.com/ros2/ros2/issues/1287#issuecomment-1170028168_

**Comment by clalancette** [comment]
I'm not sure what you are asking here.  For questions where you need help with installation, please open it on https://answers.ros.org, which is our central question and answer site.  Please make sure to include the platform you are working on, the steps you took, and what you are trying to accomplish.

I'm going to close this for now.
