### ISSUE TITLE
Multiple Lifecycle nodes are mutually exclusive in ROS2 Humble

### ISSUE THREAD

**Issue by JoJoest4r** [ros2/ros2#1379]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  -  Source, distro: ROS2 HUMBLE
- Client library:
  -  rclcpp

#### Expected behavior
All nodes successfully launched, configured and activated
#### Actual behavior
Nodes launched, but not configured and activated due to missing node
#### Additional information
I launch three lifecycle nodes sequentially and configure and activate them manually.
Although the creation of the nodes is successful, when I try to configure the third node, the terminal returns "Node not Found"

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
