### ISSUE TITLE
missing header in transmission interface

### ISSUE THREAD

**Issue by GiladRobee** [ros2/ros2#1384]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - binaries

- DDS implementation:
  - not relevant
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
#include "transmission_interface/transmission_loader.hpp"

#### Expected behavior
successful compilation
#### Actual behavior
```
/opt/ros/humble/include/transmission_interface/transmission_loader.hpp:34:27: error: ‘Transmission’ was not declared in this scope; did you mean ‘TransmissionLoader’?
   34 |   virtual std::shared_ptr<Transmission> load(
      |                           ^~~~~~~~~~~~
      |                           TransmissionLoader
/opt/ros/humble/include/transmission_interface/transmission_loader.hpp:34:39: error: template argument 1 is invalid
   34 |   virtual std::shared_ptr<Transmission> load(
```
#### Additional information

after adding the line:
#include "transmission_interface/transmission.hpp" to the include in:
/opt/ros/humble/include/transmission_interface/transmission_loader.hpp
**the bug was fixed** 
----
#### Feature description
please add said line to the source files

#### Implementation considerations
I don't think that there is any reason not to.

**Comment by clalancette** [comment]
This looks like it is a bug in ros2_control.  Please file a bug over at https://github.com/ros-controls/ros2_control
