### ISSUE TITLE
Configure and Enable the uncrustify

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#14]
We have a tools for checking our code with `uncrustify` but it is not configured to our liking yet.

Acceptance Criteria:

- [x] Decide on a configuration with the team
- [x] Reenable the linter
- [x] Create tasks for fixing failing packages

**Comment by dirk-thomas** [comment]
Configured:

* the `code_width` to be 100 characters
* forced newlines between:
  * `namespace` and open curly brace
  * `template<...>` and class / function declaration
  * `class` and open curly brace
  * `function signature and open curly brace
