### ISSUE TITLE
file 'robot_state_publisher.launch.py' was not found 

### ISSUE THREAD

**Issue by dvogureckiy99** [ros2/ros2#1401]
I use ubuntu 20.04
I compiled ros2 humble from source. 
After command `ros2 launch robot_state_publisher robot_state_publisher.launch.py urdf:=~/git/robot_programming_course/catkin_ws/src/solo12dof_quadruped/urdf/solo12dof_quadruped.urdf`:
```
file 'robot_state_publisher.launch.py' was not found in the share directory of package 'robot_state_publisher' which is at '/home/dvogureckiy99/ros2_humble/install/robot_state_publisher/share/robot_state_publisher'
```

**Comment by clalancette** [comment]
> After command `ros2 launch robot_state_publisher robot_state_publisher.launch.py urdf:=~/git/robot_programming_course/catkin_ws/src/solo12dof_quadruped/urdf/solo12dof_quadruped.urdf`:

That's right, there is no `robot_state_publisher.launch.py` file.  The files that are available are in the listed directory.

Where did you get the instruction to use `robot_state_publisher.launch.py`?

**Comment by clalancette** [comment]
No response in over a month, so I'm going to close this out.
