### ISSUE TITLE
Build warnings on nightly_linux-aarch64_release: string_fortified.h

### ISSUE THREAD

**Issue by Yadunund** [ros2/ros2#1408]
gcc, clang and clang-tidy producing warning of 
`writing 16 bytes into a region of size 0 `

* https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_release/2288
* https://ci.ros2.org/view/nightly/job/nightly_linux_release/2614/

**Comment by clalancette** [comment]
I'm actually going to close this one, as it is a dup of #1409.
