### ISSUE TITLE
Build warnings on nightly_linux-rhel_release: dds_serdata_builtintopic.c:468

### ISSUE THREAD

**Issue by Yadunund** [ros2/ros2#1409]
Same warning as #1408 but this time for `dds_serdata_builtintopic.c:468`
* https://ci.ros2.org/view/nightly/job/nightly_linux-rhel_release/1470/

Specifically it seems to be with this line in `cyclonedds`: https://github.com/eclipse-cyclonedds/cyclonedds/blob/224e56eb09e21a1314c7916bfc3e98aa93a26a61/src/core/ddsc/src/dds_serdata_builtintopic.c#L468

**Comment by clalancette** [comment]
https://github.com/eclipse-cyclonedds/cyclonedds/pull/1653

**Comment by clalancette** [comment]
And the PR was merged.  This should be fixed on the nightlies, so closing this out.
