### ISSUE TITLE
The Humble version of TurtleSim is not functional

### ISSUE THREAD

**Issue by ArFFy1314** [ros2/ros2#1412]
## Bug report
I originally installed the dashing version, but now I switched to the humble version for Unity reasons, and I stumbled upon some minor issues with the turtlesim feature pack. After I started turtlesim, I wanted to draw a rectangle to start the draw_square, and then found that the program executed slowly, like stuck, tried a few more times, and found that the best case is that the baby turtle moves a short distance, and the subsequent program cannot be executed. Due to technical and time reasons, I reinstalled ROS several times, all of which were this problem, and I did not do too many tests, I hope that the engineers can test it
**Required Info:**

- Operating System:
  - ubuntu 22.04
- Installation type:
  - build from source
- Version or commit hash:
  - humble

#### Steps to reproduce issue

```
ros2 run turtlesim turtlesim_node
ros2 run turtlesim draw_square
```

#### Expected behavior
The little turtle draws a rectangle
#### Actual behavior
The little turtle moves forward a short distance and the program freezes

I installed this version on Windows environment today and tested it. ROS2 indeed has some problems here.

**Comment by clalancette** [comment]
Thanks for the report.  This is a bug in the draw_square code, over in https://github.com/ros/ros_tutorials.

Unfortunately, GitHub doesn't allow me to move issues between organizations.  But I've opened up https://github.com/ros/ros_tutorials/pull/152 which fixes the issue for me.  I'll close this out for now, thanks again for the report.
