### ISSUE TITLE
Check that the values in the QoS profile structure are valid

### ISSUE THREAD

**Issue by esteve** [ros2/ros2#142]
The `showimage` demo on Windows crashed because the structure was not properly initialized. See https://github.com/ros2/demos/pull/40

**Comment by wjwwood** [comment]
@esteve is this still an issue? Should we bump it into the ready queue?

**Comment by clalancette** [comment]
This is very old now, so I'm going to close it out.  Feel free to reopen (or better, open a new one) if there is something we should do here.
