### ISSUE TITLE
Colcon build error

### ISSUE THREAD

**Issue by nicolal01** [ros2/ros2#1443]
Every time i use 'colcon build' this error occurs 

![image](https://github.com/ros2/ros2/assets/137066379/7b969510-936e-484e-8d61-ec624873db94)

Does anyone know how to solve this issue?

**Comment by clalancette** [comment]
This looks like a problem with your Python installation.  I'll suggest going back to the system version of Python and not using a custom one in `/usr/local/lib`.

In the future, please open questions like this on https://answers.ros.org, which is our central question and answer site.  That way it will be searchable in the future.

**Comment by nicolal01** [comment]
And how do i do that?
