### ISSUE TITLE
Build binary packages in nightly jobs

### ISSUE THREAD

**Issue by jacquelinekay** [ros2/ros2#146]
In addition to running all automated tests.

**Comment by wjwwood** [comment]
Just to clarify are the "automated tests" separate tests for the packaging or the tests within the normal packages (the same tests we run in CI)? Currently I think the packaging job doesn't build tests, but I could be wrong about that.

**Comment by jacquelinekay** [comment]
"automated tests" refers to the CI job that runs ctests. I am trying to communicate the takeaway I got from our meeting, which is that we should run packaging jobs nightly *in addition* to the current tests that are run nightly.

**Comment by wjwwood** [comment]
Roger.

**Comment by dirk-thomas** [comment]
Done in #157.
