### ISSUE TITLE
PYTHONPATH= is in one of my packages?

### ISSUE THREAD

**Issue by OmerWolfon** [ros2/ros2#1475]
- Operating System:
  - Ubuntu 22.04
- Installation type:
  - installed ros2 humble with the commands from the website (humble-desktop)

#### Steps to reproduce issue
input in terminal is :  printenv | grep -i ros     

returns:
ROS_VERSION=2
ROS_PYTHON_VERSION=3
AMENT_PREFIX_PATH=/home/omerwolf/ros2_ws/install/yolo_test_pkg:/home/omerwolf/ros2_ws/install/cv_test_pkg:/opt/ros/humble
COLCON_PREFIX_PATH=/home/omerwolf/ros2_ws/install
PYTHONPATH=/home/omerwolf/ros2_ws/build/yolo_test_pkg:/home/omerwolf/ros2_ws/install/yolo_test_pkg/lib/python3.10/site-packages:/home/omerwolf/ros2_ws/build/my_first_pkg:/home/omerwolf/ros2_ws/install/my_first_pkg/lib/python3.10/site-packages:/home/omerwolf/ros2_ws/build/cv_test_pkg:/home/omerwolf/ros2_ws/install/cv_test_pkg/lib/python3.10/site-packages:/opt/ros/humble/lib/python3.10/site-packages:/opt/ros/humble/local/lib/python3.10/dist-packages
LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:/opt/ros/humble/opt/rviz_ogre_vendor/lib:/opt/ros/humble/lib/x86_64-linux-gnu:/opt/ros/humble/lib
ROS_LOCALHOST_ONLY=0
PATH=/opt/ros/humble/bin:/home/omerwolf/anaconda3/bin:/home/omerwolf/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
ROS_DISTRO=humble

In PYTHONPATH I can see the directory includes one of my packages?
that probably happened when I tried using --symlink-install so I can skip rebuilding the package after every change.

how do I fix this? Should I just uninstall and reinstall ros2 again?

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
