### ISSUE TITLE
Rosdep - installing as sudo results in dependency errors

### ISSUE THREAD

**Issue by RnoldR** [ros2/ros2#1478]
## Bug report
My robot needs a lot of Adafruit and Sparkfun sensors and I am experimenting installing new drivers into my ROS2 humble installtion. rosdistro was forked and imported and python.yaml adjusted accordingly. The changes are recognized and installed by rosdep. During these installs I noticed that rosdep installs the libraries (in this case Adafruit-Blinka` with `sudo pip`. The result does not work, with `import board` module `hid` is not found. I can reproduce this behavior in my own environment. installing as sudo causes the error, when I install as normal user everything is ok. 

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - ROS2-humble
- Version or commit hash:
  - 9c23c70f8a9dc8afe5a6b14f73708fe258300097
  - rosedep version 0.22.2
- DDS implementation:
  - 
- Client library (if applicable):
  - rclpy
  - 
#### Steps to reproduce issue

```
I added adafruit-blinka to package.xml. There is already a rule for it in python.yaml.

<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sensor_vl53l1x</name>
  <version>0.0.1</version>
  <description>Distance sensor publisher</description>
  <maintainer email="arnold@todo.todo">arnold</maintainer>
  <license>MIT 2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>time</exec_depend>
  <exec_depend>python3-adafruit-blinka-pip</exec_depend>
  <exec_depend>python3-adafruit-circuitpython-bno055-pip</exec_depend>
  
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>

The module vl53l1x.py

import rclpy
from rclpy.node import Node
from std_msgs.msg import Int32

import board
import adafruit_vl53l1x
import adafruit_bno055


class Vl53l1x_publisher(Node):
    def __init__(self):
        super().__init__("Vl53l1x_publisher")

        i2c = board.I2C()  # uses board.SCL and board.SDA

        self.sensor = adafruit_vl53l1x.VL53L1X(i2c)

        # OPTIONAL: can set non-default values
        self.sensor.distance_mode = 1
        self.sensor.timing_budget = 100


        # self.sensor = Vl53l1xSensor()
        self.publisher_ = self.create_publisher(Int32, 'topic', 10)
        timer_period = 0.5  # seconds
        self.timer = self.create_timer(timer_period, self.timer_callback)
        self.i = 0
        self.start()

        return
    
    ### __init__ ###


    def timer_callback(self):
        # create an integer message
        msg = Int32()

        # assign data
        msg.data = self.sensor.distance

        # publish the data
        self.publisher_.publish(msg)

        # show what you have seen
        self.get_logger().info(f'Distance published: {msg.data} cm.')
        self.i += 1

        return
    
    ### timer_callback ###


    def start(self):
        # self.sensor.start()

        return
    
    ### start ###


    def stop(self):
        # self.sensor.stop()

        return
    
    ### stop ###

### Class: Vl53l1xWrapper ###

        
def main(args=None):
    rclpy.init(args=args)

    sensor = Vl53l1x_publisher()
    rclpy.on_shutdown(Vl53l1x_publisher.stop)
    rclpy.spin(sensor)

    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    sensor.destroy_node()
    rclpy.shutdown()

    return

### main ###


if __name__ == '__main__':
    main()

And then run:

    rosdep install --from-paths src -y --ignore-src
    . install/local_setup.bash
     ros2 run sensor_vl53l1x talker
```

#### Expected behavior

A running vl53l1x publisher module.

#### Actual behavior

$ conda activate rpi
(rpi) arnold@ockeghem:/media/i-files/home/arnold/development/ros2/bottie
$ . install/local_setup.bash
(rpi) arnold@ockeghem:/media/i-files/home/arnold/development/ros2/bottie
$ ros2 run sensor_vl53l1x talker
Traceback (most recent call last):
  File "/media/i-files/home/arnold/development/ros2/bottie/install/sensor_vl53l1x/lib/sensor_vl53l1x/talker", line 33, in <module>
    sys.exit(load_entry_point('sensor-vl53l1x==0.0.0', 'console_scripts', 'talker')())
  File "/media/i-files/home/arnold/development/ros2/bottie/install/sensor_vl53l1x/lib/sensor_vl53l1x/talker", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/i-files/home/arnold/development/ros2/bottie/install/sensor_vl53l1x/lib/python3.10/site-packages/sensor_vl53l1x/vl53l1x_publisher.py", line 5, in <module>
    import board
  File "/usr/local/lib/python3.10/dist-packages/board.py", line 22, in <module>
    from adafruit_blinka.agnostic import board_id, detector
  File "/usr/local/lib/python3.10/dist-packages/adafruit_blinka/agnostic/__init__.py", line 21, in <module>
    chip_id = detector.chip.id
  File "/usr/local/lib/python3.10/dist-packages/adafruit_platformdetect/chip.py", line 90, in id
    import hid
ModuleNotFoundError: No module named 'hid'
[ros2run]: Process exited with failure 1

#### Additional information

I am not sure it is a bug. However, installing as root is warned against by pip during install. Fact is that when I run the install of Adafruit-Blinka myself as root I get exactly the same error. When I do this without sudo everything works fine. Is there a reason to install as root? As far as I can see it breaks as well the environments which are needed manging all these libraries.

**Comment by gavanderhoorn** [comment]
`rosdep` installs as the super user by default, as that's what most (all?) of the installers it depends on require.

However, you can ask it to not do that for certain installers, by passing the `--as-root pip:no` command line argument:

```shell
$ rosdep --help
[..]
  --as-root=INSTALLER_KEY:<bool>
                        Override whether sudo is used for a specific
                        installer, e.g. '--as-root pip:false' or '--as-root
                        "pip:no homebrew:yes"'. Can be specified multiple
                        times.
[..]
```
