### ISSUE TITLE
Component Container process has died ROS2 galactic RCLCPP

### ISSUE THREAD

**Issue by NamanMM** [ros2/ros2#1495]
Hello everyone,

I have been getting the following error (In the callback function of the node) resulting in the crash. It is sporadic and slightly tricky to reproduce but here is the error message:

1699879254.0570445 [ERROR] [component_container-1]: process has died [pid 597648, exit code -11, cmd '/opt/ros/galactic/lib/rclcpp_components/component_container --ros-args -r __node:=crop_spec_container -r __ns:=/'].

I have gone through the log files and nothing pops out immediately; the node seemed to be running well till this crash happens.

Any pointers or suggestion will be appreciated.
Thank you in advance.

**Comment by clalancette** [comment]
Please don't open the same issue on multiple repositories. Closing this one in favor of https://github.com/ros2/rclcpp/issues/2368
