### ISSUE TITLE
Disable poorly configured linters

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#15]
Until we get them properly configured (#12, #13, #14) we should disable them.

AC:

- [ ] Disable the `uncrustify`, `cpplint`, and `clang_format` linters.

**Comment by dirk-thomas** [comment]
I disabled `clang_format` and `cpplint` for now (https://github.com/ament/ament_lint/commit/dc4a6e57f349d6ddd44faba8a08e335c332a0cc8).

I kept `uncrustify` since I didn't see any failing tests for it. I think I chose a minimal configuration which only tests stuff we obviously follow already.
