### ISSUE TITLE
python version of ros foxy

### ISSUE THREAD

**Issue by Chortine** [ros2/ros2#1503]
Hi Team,

When I download the binary file of ros2 foxy, e.g. the [ros2-foxy-20230620-linux-focal-amd64.tar.bz2](https://github.com/ros2/ros2/releases/download/release-foxy-20230620/ros2-foxy-20230620-linux-focal-amd64.tar.bz2), in the lib/ folder there is already python3.8/ folder. However, I want to use the ros python in python 3.9 version, how can I instead have the python3.9 dependencies? 

Thanks.

**Comment by clalancette** [comment]
In general, if you want to use a different Python version, you have to recompile ROS 2 from sources.  You can follow the instructions at http://docs.ros.org/en/foxy/Installation/Alternatives/Ubuntu-Development-Setup.html , but we don't have any resources to help if it doesn't work for you.

Further, Foxy is End-of-Life.  I'll suggest trying a newer distribution, like Humble, which is still supported.
