### ISSUE TITLE
ROS 2 Foxy Timer Glitch

### ISSUE THREAD

**Issue by Vitus012** [ros2/ros2#1504]
## Bug report
I was doing a project in summer of 2022 and was using a timer for a control loop. I started the loop with an action and when necessary I would cancel the action and stop the timer. 
Problem was, that after an uncertain amount of time has passed, the timer would refuse to start up again.
The "time passed since the last call" would increase as normal.
I could not figure out what caused the issue or how to reproduce it, as it would sometimes come up after hours of testing and sometimes after a few on-off cycles.

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries from August 2022
- Version or commit hash:
  - (unsure where I can find it in the binaries)
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclpy

#### Expected behavior
Timer can be started and stopped at will, as often as needed.
#### Actual behavior
Timer can not be started again after an uncertain amount of starts and stops.

**Comment by clalancette** [comment]
This isn't much to go on, unfortunately.  And Foxy is End-of-Life now, so this would be difficult to reproduce.

My suggestion here is that you try this again with Humble or Iron, and see if you still have the problem.  If so, please feel free to open a new bug with the relevant information, and we can try to debug from there.
