### ISSUE TITLE
 Unable to correct problems, you have held broken packages.

### ISSUE THREAD

**Issue by Melki123shi** [ros2/ros2#1520]
## **sudo apt install ros-humble-slam-toolbox**
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-humble-slam-toolbox : Depends: libceres2 (>= 2.0.0+dfsg1) but it is not installable
                           Depends: libgoogle-glog0v5 (>= 0.5.0+really0.4.0) but it is not installable
                           Depends: libceres-dev but it is not installable
                           Depends: libsuitesparse-dev but it is not installable
                           Depends: ros-humble-nav2-map-server but it is not going to be installed
# E: Unable to correct problems, you have held broken packages.
please anyone who can solve this problem I have trie to install the dependencies but the result is ....

## **sudo apt install libceres2 libgoogle-glog0v5 libceres-dev libsuitesparse-dev ros-humble-nav2-map-server**
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libceres2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libgoogle-glog0v5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libceres-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libsuitesparse-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

# E: Package 'libceres2' has no installation candidate
E: Package 'libgoogle-glog0v5' has no installation candidate
E: Package 'libceres-dev' has no installation candidate
E: Package 'libsuitesparse-dev' has no installation candidate

**Comment by Yadunund** [comment]
hello,

This repository is concerned with core ROS 2 packages as listed in the [ros2.repos](https://github.com/ros2/ros2/blob/rolling/ros2.repos) file. `slam_toolbox` is not part of the core. Please open a ticket in the [slam_toolbox](https://github.com/SteveMacenski/slam_toolbox) repository or ask this question on https://robotics.stackexchange.com/.
