### ISSUE TITLE
Incorrect version used for eProsima/Fast-DDS in iron-release

### ISSUE THREAD

**Issue by thomasmoore-torc** [ros2/ros2#1522]
The version "2.10.2" used for eProsima/Fast-DDS in `iron-release` is a branch and not a tag. The correct version for the tag is `v2.10.2`.

https://github.com/ros2/ros2/blob/d7829505df93798fd6ae595e831dae17e182d5d9/ros2.repos#L34-L37

**Comment by Yadunund** [comment]
This ticket very timely! Thanks for pointing out the issue. I've updated the version to reference the tag https://github.com/ros2/ros2/pull/1521/commits/4d0baf402d40fb64055739d4b2c1c7a72448187f

**Comment by clalancette** [comment]
This was fixed in #1521, so closing.
