### ISSUE TITLE
Unknown CMake command "list_append_unique"

### ISSUE THREAD

**Issue by arghyamukherjee007** [ros2/ros2#1525]
Base path: /Users/arghymu/my-robotics-system/catkin_ws
Source space: /Users/arghymu/my-robotics-system/catkin_ws/src
Build space: /Users/arghymu/my-robotics-system/catkin_ws/build
Devel space: /Users/arghymu/my-robotics-system/catkin_ws/devel
Install space: /Users/arghymu/my-robotics-system/catkin_ws/install
####
####
CMake Error at /Users/arghymu/miniconda3/envs/ROS/share/catkin/cmake/catkinConfig.cmake:95 (list_append_unique):
  Unknown CMake command "list_append_unique".
Call Stack (most recent call first):
  CMakeLists.txt:20 (find_package)
-- Configuring incomplete, errors occurred!
See also "/Users/arghymu/my-robotics-system/catkin_ws/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:268: cmake_check_build_system] Error 1

**Comment by clalancette** [comment]
This looks to be a problem with building ROS 1, not ROS 2.

Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
