### ISSUE TITLE
typo in warning message: "Be aware that are nodes ..."

### ISSUE THREAD

**Issue by VladimirFokow** [ros2/ros2#1541]
Required info:

- Operating System:
  -  Ubuntu 22.04
- Installation type:
  - binaries
- Version or commit hash:
  - humble-desktop
- DDS implementation:
  - cyclonedds-cpp

#### Steps to reproduce issue

- run 2 nodes that share the same name, e.g.:
  ```bash
  ros2 run turtlesim turtlesim_node  # in one terminal
  ```
  ```bash
  ros2 run turtlesim turtlesim_node  # in another terminal
  ```
- run `ros2 node list`

#### Expected behavior

no typo in the warning message: "there are"

#### Actual behavior

typo: "that are"

#### Additional information

Example of the error message that I'm talking about can be found [across github](https://github.com/search?q=%22Be+aware+that+are+nodes+in+the+graph%22&type=code)

**Comment by fujitatomoya** [comment]
this has been fixed with https://github.com/ros2/ros2cli/pull/775

**Comment by clalancette** [comment]
> @fujitatomoya oh, so this is not the kind of change to be backported to [humble](https://github.com/ros2/ros2cli/blob/humble/ros2node/ros2node/verb/list.py#L45) as I understand?

Yeah, this one could possibly break anything downstream that is expecting that exact string.  For that reason, we won't backport this to Humble.
