### ISSUE TITLE
How to set joint angles when spawning robot in gazebo

### ISSUE THREAD

**Issue by scybd** [ros2/ros2#1552]
In ROS I can use -J option in [spawn_model.py](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/noetic-devel/gazebo_ros/scripts/spawn_model#L78) to set joints' angle at beginning. However in ROS2, spawn_entity.py doesn't have the -J option.

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
