### ISSUE TITLE
When to support Ubuntu24. 04 pls

### ISSUE THREAD

**Issue by tungchiahui** [ros2/ros2#1553]

**Comment by clalancette** [comment]
ROS 2 Rolling is already on Ubuntu 24.04.  The next ROS 2 release (Jazzy) will also be on Ubuntu 24.04.

**Comment by tungchiahui** [comment]
@clalancette May I ask when ROS Jazzy will be released？pls.

**Comment by Yadunund** [comment]
> @clalancette May I ask when ROS Jazzy will be released？pls. May I ask It is LTS?

Tentative release date is 23rd May 2024. See https://docs.ros.org/en/jazzy/Releases/Release-Jazzy-Jalisco.html#release-timeline

**Comment by tungchiahui** [comment]
@Yadunund  Thank you for your answer. Can you ask you another question? Is it possible to publish the APT binary package of Debian 12 in the future?
