### ISSUE TITLE
ros-rolling-pcl-conversions : Depends: libpcl-common1.13 but it is not installable

### ISSUE THREAD

**Issue by aarambhpatil** [ros2/ros2#1554]
## Bug report

I recently encountered an issue while trying to install ROS2 Rolling to my Raspberry Pi 5 with Ubuntu 24.04 Noble Numbat LTS. There is a missing package in Ubuntu 24.04 named libpcl-common1.13 as it is not installed. The package ros-rolling-pcl-conversions depends on this specific package to be installed and it cannot be installed from the apt sources. Would be glad if anyone has found any solutions to the issue

**Required Info:**

- Operating System:
  - Ubuntu 24.04 Noble Numbat
- Installation type:
  - Trying installation from Source
- Version or commit hash:
  - ROS2 Rolling

#### Steps to reproduce issue
Use Noble Numbat to recreate the issue on a Raspberry Pi 5

```
https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Debians.html
```

#### Additional information

----

**Comment by clalancette** [comment]
> I recently encountered an issue while trying to install ROS2 Rolling to my Raspberry Pi 5 with Ubuntu 24.04 Noble Numbat LTS. There is a missing package in Ubuntu 24.04 named libpcl-common1.13 as it is not installed. The package ros-rolling-pcl-conversions depends on this specific package to be installed and it cannot be installed from the apt sources. Would be glad if anyone has found any solutions to the issue

It is fixed in `ros2-testing`; we'll be doing an update to fix it shortly.

**Comment by clalancette** [comment]
This was fixed in the latest sync, so closing.
