### ISSUE TITLE
catkin_make failed

### ISSUE THREAD

**Issue by Flaneuroo** [ros2/ros2#1571]
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target dynamic_reconfigure_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target std_srvs_generate_messages_nodejs
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target actionlib_msgs_generate_messages_cpp
[  0%] Built target dynamic_reconfigure_generate_messages_nodejs
[  0%] Built target std_srvs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target actionlib_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target std_srvs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target roscpp_generate_messages_py
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target std_srvs_generate_messages_py
[  0%] Built target std_srvs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target dynamic_reconfigure_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target dynamic_reconfigure_generate_messages_eus
[  0%] Built target tf2_msgs_generate_messages_cpp
[  0%] Built target tf2_msgs_generate_messages_eus
[  0%] Built target dynamic_reconfigure_gencfg
[  0%] Built target tf2_msgs_generate_messages_lisp
[  0%] Built target tf2_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target actionlib_msgs_generate_messages_eus
[  0%] Built target dynamic_reconfigure_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_nodejs
[  0%] Built target actionlib_msgs_generate_messages_py
[  0%] Built target actionlib_generate_messages_eus
[  0%] Built target actionlib_generate_messages_nodejs
[  0%] Built target tf2_msgs_generate_messages_py
[  0%] Built target actionlib_generate_messages_py
[  0%] Built target actionlib_generate_messages_cpp
[  0%] Built target _orbbec_camera_generate_messages_check_deps_GetInt32
[  0%] Built target _orbbec_camera_generate_messages_check_deps_SetBool
[  0%] Built target _orbbec_camera_generate_messages_check_deps_GetBool
[  0%] Built target _orbbec_camera_generate_messages_check_deps_Extrinsics
[  0%] Built target _orbbec_camera_generate_messages_check_deps_DeviceInfo
[  0%] Built target _orbbec_camera_generate_messages_check_deps_SetInt32
[  0%] Built target _orbbec_camera_generate_messages_check_deps_SetString
[  0%] Built target _orbbec_camera_generate_messages_check_deps_Metadata
[  0%] Built target _orbbec_camera_generate_messages_check_deps_GetString
[  0%] Built target _orbbec_camera_generate_messages_check_deps_GetCameraParams
[  0%] Built target _orbbec_camera_generate_messages_check_deps_GetDeviceInfo
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target learn_urdf_xacro_generated_to_devel_space_
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target _orbbec_camera_generate_messages_check_deps_GetCameraInfo
[  2%] Built target yahboomcar_bringup_gencfg
[  2%] Generating dynamic reconfigure files from cfg/laserAvoidancePID.cfg: /home/jetson/yahboomcar_ws/devel/include/yahboomcar_laser/laserAvoidancePIDConfig.h /home/jetson/yahboomcar_ws/devel/lib/python2.7/dist-packages/yahboomcar_laser/cfg/laserAvoidancePIDConfig.py
[  3%] Built target yahboomcar_linefollw_gencfg
[  5%] Built target base_node
[  5%] Built target _yahboomcar_msgs_generate_messages_check_deps_Position
[  5%] Built target _yahboomcar_msgs_generate_messages_check_deps_TargetArray
Generating reconfiguration files for laserAvoidPID in yahboomcar_laser
Wrote header file in /home/jetson/yahboomcar_ws/devel/include/yahboomcar_laser/laserAvoidPIDConfig.h
[  5%] Built target _yahboomcar_msgs_generate_messages_check_deps_Image_Msg
[  6%] Linking CXX shared library /home/jetson/yahboomcar_ws/devel/lib/libkcftracker.so
[  6%] Built target _yahboomcar_msgs_generate_messages_check_deps_Target
[  6%] Built target _yahboomcar_msgs_generate_messages_check_deps_PointArray
[  8%] Built target yahboomcar_laser_gencfg
[  9%] Generating dynamic reconfigure files from cfg/KCFTracker.cfg: /home/jetson/yahboomcar_ws/devel/include/yahboomcar_astra/KCFTrackerConfig.h /home/jetson/yahboomcar_ws/devel/lib/python2.7/dist-packages/yahboomcar_astra/cfg/KCFTrackerConfig.py
[ 10%] Built target yahboomcar_multi_gencfg
[ 11%] Built target mediapipe_point
[ 12%] Built target save
Generating reconfiguration files for KCFTrackerPID in yahboomcar_astra
Wrote header file in /home/jetson/yahboomcar_ws/devel/include/yahboomcar_astra/KCFTrackerPIDConfig.h
[ 15%] Built target rrt_save_map
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `FFTTools::fftd(cv::Mat, bool)':
kcftracker.cpp:(.text+0x1f8): multiple definition of `FFTTools::fftd(cv::Mat, bool)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x1f8): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `FFTTools::real(cv::Mat)':
kcftracker.cpp:(.text+0x464): multiple definition of `FFTTools::real(cv::Mat)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x464): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `FFTTools::imag(cv::Mat)':
kcftracker.cpp:(.text+0x550): multiple definition of `FFTTools::imag(cv::Mat)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x550): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `FFTTools::magnitude(cv::Mat)':
kcftracker.cpp:(.text+0x63c): multiple definition of `FFTTools::magnitude(cv::Mat)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x63c): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `FFTTools::complexMultiplication(cv::Mat, cv::Mat)':
kcftracker.cpp:(.text+0x844): multiple definition of `FFTTools::complexMultiplication(cv::Mat, cv::Mat)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x844): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `FFTTools::complexDivision(cv::Mat, cv::Mat)':
kcftracker.cpp:(.text+0xc80): multiple definition of `FFTTools::complexDivision(cv::Mat, cv::Mat)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0xc80): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `FFTTools::rearrange(cv::Mat&)':
kcftracker.cpp:(.text+0x1274): multiple definition of `FFTTools::rearrange(cv::Mat&)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x1274): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `FFTTools::normalizedLogTransform(cv::Mat&)':
kcftracker.cpp:(.text+0x1550): multiple definition of `FFTTools::normalizedLogTransform(cv::Mat&)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x1550): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o:(.data+0x0): multiple definition of `data'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:(.data+0x0): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::KCFTracker(bool, bool, bool, bool)':
kcftracker.cpp:(.text+0x1654): multiple definition of `KCFTracker::KCFTracker(bool, bool, bool, bool)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x1654): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::KCFTracker(bool, bool, bool, bool)':
kcftracker.cpp:(.text+0x1654): multiple definition of `KCFTracker::KCFTracker(bool, bool, bool, bool)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x1654): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::init(cv::Rect_<int> const&, cv::Mat)':
kcftracker.cpp:(.text+0x1a20): multiple definition of `KCFTracker::init(cv::Rect_<int> const&, cv::Mat)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x1a20): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::getFeatures(cv::Mat const&, bool, float)':
kcftracker.cpp:(.text+0x3550): multiple definition of `KCFTracker::getFeatures(cv::Mat const&, bool, float)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x3550): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::createGaussianPeak(int, int)':
kcftracker.cpp:(.text+0x3358): multiple definition of `KCFTracker::createGaussianPeak(int, int)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x3358): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::train(cv::Mat, float)':
kcftracker.cpp:(.text+0x2670): multiple definition of `KCFTracker::train(cv::Mat, float)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x2670): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::update(cv::Mat)':
kcftracker.cpp:(.text+0x1c48): multiple definition of `KCFTracker::update(cv::Mat)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x1c48): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::detect(cv::Mat, cv::Mat, float&)':
kcftracker.cpp:(.text+0x22bc): multiple definition of `KCFTracker::detect(cv::Mat, cv::Mat, float&)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x22bc): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::gaussianCorrelation(cv::Mat, cv::Mat)':
kcftracker.cpp:(.text+0x29d8): multiple definition of `KCFTracker::gaussianCorrelation(cv::Mat, cv::Mat)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x29d8): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::subPixelPeak(float, float, float)':
kcftracker.cpp:(.text+0x43e4): multiple definition of `KCFTracker::subPixelPeak(float, float, float)'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x43e4): first defined here
CMakeFiles/kcftracker.dir/kcftracker.cpp.o: In function `KCFTracker::createHanningMats()':
kcftracker.cpp:(.text+0x402c): multiple definition of `KCFTracker::createHanningMats()'
CMakeFiles/kcftracker.dir/.ipynb_checkpoints/kcftracker-checkpoint.cpp.o:kcftracker-checkpoint.cpp:(.text+0x402c): first defined here
collect2: error: ld returned 1 exit status
yahboomcar_astra/include/yahboomcar_astra/CMakeFiles/kcftracker.dir/build.make:205: recipe for target '/home/jetson/yahboomcar_ws/devel/lib/libkcftracker.so' failed
make[2]: *** [/home/jetson/yahboomcar_ws/devel/lib/libkcftracker.so] Error 1
CMakeFiles/Makefile2:4552: recipe for target 'yahboomcar_astra/include/yahboomcar_astra/CMakeFiles/kcftracker.dir/all' failed
make[1]: *** [yahboomcar_astra/include/yahboomcar_astra/CMakeFiles/kcftracker.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 16%] Built target astra_depth_image
[ 17%] Built target pointcloud_mapping
[ 18%] Built target yahboomcar_astra_gencfg
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.

Additionally, this is for ROS 1, not ROS 2, so make sure to state that.
