### ISSUE TITLE
E: Unable to locate package ros-jazzy-desktop

### ISSUE THREAD

**Issue by MickeyTso** [ros2/ros2#1580]
The following error message is reported during installing ROS2 Jazzy on the development board: `E: Unable to locate package ros-jazzy-desktop`, what should I do?The installed system is Ubuntu 20.04.

**Comment by gavanderhoorn** [comment]
> The installed system is Ubuntu 20.04.

please post these kinds of questions on Robotics Stack Exchange in the future, but just to help you out: Jazzy doesn't support Ubuntu `20.04`. Only Ubuntu Noble (ie: `24.04`).

**Comment by MickeyTso** [comment]
My development board contacted the manufacturer and only supports 22.04, can I install the fox version of 20.04 and 22.04? Later, we will change to the latest version during the testing phase.
