### ISSUE TITLE
Cross-machine communication cannot receive big data

### ISSUE THREAD

**Issue by slp12138** [ros2/ros2#1584]
## Bug report

**Required Info:**

- Operating System:
  - ubuntu22.04
- Installation type:
  - binaries
- Version or commit hash:
  - humble
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp, rclpy

Prepare two computers that use wireless network communication, and pass the iperf test, and the communication bandwidth between the two computers is 5 M/s on average. One computer publishes a topic at 10Hz and the other receives it, but the receiver can receive the message at the beginning and will no longer receive it after a while. I've tried increasing the buffer size, but it didn't work

**Comment by Yadunund** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site. You'll get a better answer there, and it will be searchable for the future.

Or in this case, perhaps a ticket on [rmw_fastrtps](https://github.com/ros2/rmw_fastrtps)
