### ISSUE TITLE
Octomap Plugin for ros2 humble

### ISSUE THREAD

**Issue by NikolaRaicevic2001** [ros2/ros2#1593]
OccupancyGrid
The class required for this display, 'octomap_rviz_plugins/OccupancyGrid', could not be loaded.
Error:
Failed to load library /opt/ros/humble/lib/liboctomap_rviz_plugins.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library dlopen error: /opt/ros/humble/lib/liboctomap_rviz_plugins.so: undefined symbol: _ZTIN7octomap13OcTreeStampedE, at ./src/shared_library.c:99

I have received this error when trying to load octomap-plugins and it seems like the issue goes deeper as to not transmiting the octomap message correctly which disables the communication between the octomap server and other nodes. 

The way that the octomap-plugins were installed was sudo apt-get install ros-humble-octomap-rviz-plugins

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
