### ISSUE TITLE
How to use source to compile the ros2 

### ISSUE THREAD

**Issue by lix19937** [ros2/ros2#1594]
There are related repos in https://github.com/ros2/ros2/blob/rolling/ros2.repos, but no cmakelist file to unified serial compile.

**Comment by christophebedard** [comment]
The information you need is in the README: https://github.com/ros2/ros2/blob/rolling/README.md. That points to the documentation here: https://docs.ros.org/.

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
