### ISSUE TITLE
hello gays,How to solve this problem? when i am to colcon build PX4 offborad  in ros2 noetic version 

### ISSUE THREAD

**Issue by Yang-Youngster** [ros2/ros2#1599]
when i am to exe this :
------->
root@LuoYang:/home/luoyang/ros2_ws# colcon build
Starting >>> px4_msgs
--- stderr: px4_msgs
CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cmake", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake" with
  any of the following names:

    ament_cmakeConfig.cmake
    ament_cmake-config.cmake

  Add the installation prefix of "ament_cmake" to CMAKE_PREFIX_PATH or set
  "ament_cmake_DIR" to a directory containing one of the above files.  If
  "ament_cmake" provides a separate development package or SDK, be sure it
  has been installed.

---
 currently , i have to exe this method ,but it not good

1. change this workspace file permission
   sudo chmod 777 -R .
   and 
  colcon build 

2. reload this
  source opt/ros/noetic/setup.bash
 but it also

please , any gays have answer to resolve this.

**Comment by arjo129** [comment]
Which version of ros did you install? You need to `source /opt/ros/<YOUR ROS DISTRO>/setup.bash`. Noetic is not ros2 and does not support ament. Also in future please post questions like this on https://robotics.stackexchange.com/ .
