### ISSUE TITLE
ros2 galactic  publishes and subscribes using different types of messages ? 

### ISSUE THREAD

**Issue by lix19937** [ros2/ros2#1600]
```
If nodeA pub msg is A, 
   nodeB sub msg is B, the sizeof(A) == sizeof(B),  use the same topic name.  
```   
can nodeB sub the A ?

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
