### ISSUE TITLE
ubuntu20 安装ros2-humlbe ( Jeston orin nx)

### ISSUE THREAD

**Issue by 2805651606** [ros2/ros2#1608]
Starting >>> rosbag2_cpp
[Processing: diagnostic_msgs, rclpy, rosbag2_cpp, shape_msgs]             
--- stderr: rclpy                                                             
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `_Py_DECREF':
test_python_allocator.cpp:(.text+0x94): undefined reference to `_Py_Dealloc'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::str::str(char const*)':
test_python_allocator.cpp:(.text._ZN8pybind113strC2EPKc[_ZN8pybind113strC5EPKc]+0x30): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::str::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const':
test_python_allocator.cpp:(.text._ZNK8pybind113strcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv[_ZNK8pybind113strcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv]+0x68): undefined reference to `PyUnicode_AsUTF8String'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZNK8pybind113strcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv[_ZNK8pybind113strcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv]+0xd8): undefined reference to `PyBytes_AsStringAndSize'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::detail::get_internals()':
test_python_allocator.cpp:(.text._ZN8pybind116detail13get_internalsEv[_ZN8pybind116detail13get_internalsEv]+0x200): undefined reference to `PyThread_tss_alloc'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZN8pybind116detail13get_internalsEv[_ZN8pybind116detail13get_internalsEv]+0x228): undefined reference to `PyThread_tss_create'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZN8pybind116detail13get_internalsEv[_ZN8pybind116detail13get_internalsEv]+0x264): undefined reference to `PyThread_tss_set'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::detail::instance::allocate_layout()':
test_python_allocator.cpp:(.text._ZN8pybind116detail8instance15allocate_layoutEv[_ZN8pybind116detail8instance15allocate_layoutEv]+0x180): undefined reference to `PyMem_Calloc'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::detail::error_string[abi:cxx11]()':
test_python_allocator.cpp:(.text._ZN8pybind116detail12error_stringB5cxx11Ev[_ZN8pybind116detail12error_stringB5cxx11Ev]+0x184): undefined reference to `PyException_SetTraceback'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::detail::get_thread_state_unchecked()':
test_python_allocator.cpp:(.text._ZN8pybind116detail26get_thread_state_uncheckedEv[_ZN8pybind116detail26get_thread_state_uncheckedEv]+0x8): undefined reference to `_PyThreadState_UncheckedGet'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::detail::type_caster<bool, void>::load(pybind11::handle, bool)':
test_python_allocator.cpp:(.text._ZN8pybind116detail11type_casterIbvE4loadENS_6handleEb[_ZN8pybind116detail11type_casterIbvE4loadENS_6handleEb]+0x84): undefined reference to `_Py_FalseStruct'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZN8pybind116detail11type_casterIbvE4loadENS_6handleEb[_ZN8pybind116detail11type_casterIbvE4loadENS_6handleEb]+0x88): undefined reference to `_Py_FalseStruct'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::detail::make_static_property_type()':
test_python_allocator.cpp:(.text._ZN8pybind116detail25make_static_property_typeEv[_ZN8pybind116detail25make_static_property_typeEv]+0x34): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11_meta_getattro':
test_python_allocator.cpp:(.text.pybind11_meta_getattro[pybind11_meta_getattro]+0x2c): undefined reference to `PyInstanceMethod_Type'
/usr/bin/ld: test_python_allocator.cpp:(.text.pybind11_meta_getattro[pybind11_meta_getattro]+0x30): undefined reference to `PyInstanceMethod_Type'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::detail::make_default_metaclass()':
test_python_allocator.cpp:(.text._ZN8pybind116detail22make_default_metaclassEv[_ZN8pybind116detail22make_default_metaclassEv]+0x34): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::detail::make_object_base_type(_typeobject*)':
test_python_allocator.cpp:(.text._ZN8pybind116detail21make_object_base_typeEP11_typeobject[_ZN8pybind116detail21make_object_base_typeEP11_typeobject]+0x38): undefined reference to `PyUnicode_FromString'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::cpp_function::initialize_generic(pybind11::detail::function_record*, char const*, std::type_info const* const*, unsigned long)':
test_python_allocator.cpp:(.text._ZN8pybind1112cpp_function18initialize_genericEPNS_6detail15function_recordEPKcPKPKSt9type_infom[_ZN8pybind1112cpp_function18initialize_genericEPNS_6detail15function_recordEPKcPKPKSt9type_infom]+0x8d4): undefined reference to `PyInstanceMethod_Type'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZN8pybind1112cpp_function18initialize_genericEPNS_6detail15function_recordEPKcPKPKSt9type_infom[_ZN8pybind1112cpp_function18initialize_genericEPNS_6detail15function_recordEPKcPKPKSt9type_infom]+0x8d8): undefined reference to `PyInstanceMethod_Type'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZN8pybind1112cpp_function18initialize_genericEPNS_6detail15function_recordEPKcPKPKSt9type_infom[_ZN8pybind1112cpp_function18initialize_genericEPNS_6detail15function_recordEPKcPKPKSt9type_infom]+0xcc8): undefined reference to `PyCMethod_New'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZN8pybind1112cpp_function18initialize_genericEPNS_6detail15function_recordEPKcPKPKSt9type_infom[_ZN8pybind1112cpp_function18initialize_genericEPNS_6detail15function_recordEPKcPKPKSt9type_infom]+0x1178): undefined reference to `PyInstanceMethod_New'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::gil_scoped_acquire::gil_scoped_acquire()':
test_python_allocator.cpp:(.text._ZN8pybind1118gil_scoped_acquireC2Ev[_ZN8pybind1118gil_scoped_acquireC5Ev]+0x30): undefined reference to `PyThread_tss_get'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZN8pybind1118gil_scoped_acquireC2Ev[_ZN8pybind1118gil_scoped_acquireC5Ev]+0xc8): undefined reference to `PyThread_tss_set'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::gil_scoped_acquire::dec_ref()':
test_python_allocator.cpp:(.text._ZN8pybind1118gil_scoped_acquire7dec_refEv[_ZN8pybind1118gil_scoped_acquire7dec_refEv]+0xc4): undefined reference to `PyThread_tss_set'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::detail::string_caster<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false>::decode_utfN(char const*, long)':
test_python_allocator.cpp:(.text._ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE11decode_utfNEPKcl[_ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE11decode_utfNEPKcl]+0x30): undefined reference to `PyUnicode_DecodeUTF8'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `pybind11::detail::string_caster<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false>::load(pybind11::handle, bool)':
test_python_allocator.cpp:(.text._ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE4loadENS_6handleEb[_ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE4loadENS_6handleEb]+0xb4): undefined reference to `PyUnicode_AsEncodedString'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE4loadENS_6handleEb[_ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE4loadENS_6handleEb]+0x108): undefined reference to `PyBytes_AsString'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE4loadENS_6handleEb[_ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE4loadENS_6handleEb]+0x11c): undefined reference to `PyBytes_Size'
/usr/bin/ld: CMakeFiles/test_python_allocator.dir/test/test_python_allocator.cpp.o: in function `bool pybind11::detail::string_caster<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false>::load_bytes<char>(std::enable_if<(sizeof (char))==(1), pybind11::handle>::type)':
test_python_allocator.cpp:(.text._ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE10load_bytesIcEEbNSt9enable_ifIXeqstT_Li1EENS_6handleEE4typeE[_ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE10load_bytesIcEEbNSt9enable_ifIXeqstT_Li1EENS_6handleEE4typeE]+0x60): undefined reference to `PyBytes_AsString'
/usr/bin/ld: test_python_allocator.cpp:(.text._ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE10load_bytesIcEEbNSt9enable_ifIXeqstT_Li1EENS_6handleEE4typeE[_ZN8pybind116detail13string_casterINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEELb0EE10load_bytesIcEEbNSt9enable_ifIXeqstT_Li1EENS_6handleEE4typeE]+0x80): undefined reference to `PyBytes_Size'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test_python_allocator.dir/build.make:87: test_python_allocator] Error 1
make[1]: *** [CMakeFiles/Makefile2:186: CMakeFiles/test_python_allocator.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< rclpy [1min 42s, exited with code 2]
Aborted  <<< shape_msgs [1min 22s]                        
Aborted  <<< diagnostic_msgs [1min 29s]                  
Aborted  <<< rosbag2_cpp [3min 7s]                                             

Summary: 194 packages finished [6min 14s]
  1 package failed: rclpy
  3 packages aborted: diagnostic_msgs rosbag2_cpp shape_msgs
  4 packages had stderr output: diagnostic_msgs rclpy rosbag2_cpp shape_msgs
  147 packages not processed
请问，这个应该怎么解决

**Comment by fujitatomoya** [comment]
@2805651606 please fill in the issue template to report the issue, that helps us to understand the issue.

Humble's official supported platform is ubuntu 22.04, see more details for https://docs.ros.org/en/humble/Installation.html#installation

**Comment by fujitatomoya** [comment]
@2805651606 we recommend that you could use https://robotics.stackexchange.com/ for the question like this, where is our centralized QA site.
