### ISSUE TITLE
ROS2 installation for a begineer

### ISSUE THREAD

**Issue by abdullah-zmoosa** [ros2/ros2#1610]
Im getting the issue below , and i cant install ros2 humble, it throws soo many dependency issues, i run an ASUS TUF A16 advantage edtion (all amd laptop) however , i cant install it why? 

when i tried fixing the packages my Ubuntu died and was left with a ttyl1 screen

The following packages have unmet dependencies:
 libdrm-dev : Depends: libdrm2 (= 2.4.113-2~ubuntu0.22.04.1) but 2.4.122+git2407120500.11cafd~oibaf~j is to be installed
              Depends: libdrm-intel1 (= 2.4.113-2~ubuntu0.22.04.1) but 2.4.122+git2407120500.11cafd~oibaf~j is to be installed
              Depends: libdrm-radeon1 (= 2.4.113-2~ubuntu0.22.04.1) but 2.4.122+git2407120500.11cafd~oibaf~j is to be installed
              Depends: libdrm-amdgpu1 (= 2.4.113-2~ubuntu0.22.04.1) but 2.4.122+git2407120500.11cafd~oibaf~j is to be installed
 libgbm-dev : Depends: libgbm1 (= 23.2.1-1ubuntu3.1~22.04.2) but 24.3~git2407250600.76ae27~oibaf~j is to be installed
E: Unable to correct problems, you have held broken packages.

- Operating System:
Ubuntu 22.04
- Installation type:
  sudo apt install ros-humble-desktop

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
