### ISSUE TITLE
Feature request: Duration multiplication

### ISSUE THREAD

**Issue by Timple** [ros2/ros2#1625]
#### Feature description
Duration multiplication should be possible:

```python
total_duration = Duration(seconds=47)
progress = 0.20
time_left = total_duration * (1 - progress)
```

#### Implementation considerations
Workaround the limitation:

```python
total_duration = Duration(seconds=47)
progress = 0.20
time_left = Duration(nanoseconds=total_duration.nanoseconds * (1 - progress))
```
Which is not as readable.

_I get why addition of floats to durations is not possible because of types. But i.m.o. multiplication is valid._

**Comment by fujitatomoya** [comment]
@Timple IMO this is nice to have.

**Comment by MichaelOrlov** [comment]
We discussed this request on today's weekly triage meeting and concluded that it is good to have. However, help here from the community is needed.

**Comment by fujitatomoya** [comment]
rclcpp already has the assignment operator for multiplication, https://github.com/ros2/rclcpp/blob/rolling/rclcpp/src/rclcpp/duration.cpp#L225-L246

**Comment by fujitatomoya** [comment]
https://github.com/ros2/rclpy/pull/1387 is merged.
