### ISSUE TITLE
create cross vendor tests

### ISSUE THREAD

**Issue by tfoote** [ros2/ros2#163]
Re #99

Approach TBD

**Comment by wjwwood** [comment]
@tfoote can you put some more details here (if you can remember them). AFAICT, #99 doesn't have anything to do with this, unless you mean that we need cross vendor tests for Windows.

Either way maybe this is resolved by @dirk-thomas's work to duplicate binaries for multiple vendors even on Windows.

**Comment by tfoote** [comment]
I think this is covered by the duplicate binaries. At the time we were only supporting one vendor at a time on Windows.

**Comment by wjwwood** [comment]
Ok, then I'll close unless someone comments differently.
