### ISSUE TITLE
install jazzy

### ISSUE THREAD

**Issue by alifazeli00** [ros2/ros2#1631]
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.42
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'

C:\Windows\System32> cd C:\dev\ros2_ws

C:\dev\ros2_ws>call ..\ros2_jazzy\local_setup.bat

C:\dev\ros2_ws>colcon build --symlink-install --merge-install
Starting >>> examples_rclcpp_async_client
Starting >>> examples_rclcpp_cbg_executor
Starting >>> examples_rclcpp_minimal_action_client
Starting >>> examples_rclcpp_minimal_action_server
Starting >>> examples_rclcpp_minimal_client
Starting >>> examples_rclcpp_minimal_composition
Starting >>> examples_rclcpp_minimal_publisher
Starting >>> examples_rclcpp_minimal_service
--- stderr: examples_rclcpp_async_client
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

Traceback (most recent call last):
  File "C:/dev/ros2_jazzy/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py", line 21, in <module>
    from ament_package.templates import get_environment_hook_template_path
ModuleNotFoundError: No module named 'ament_package'
CMake Error at C:/dev/ros2_jazzy/share/ament_cmake_core/cmake/ament_cmake_package_templates-extras.cmake:41 (message):
  execute_process(C:/Python38/python.exe
  C:/dev/ros2_jazzy/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py
  C:/dev/ros2_ws/build/examples_rclcpp_async_client/ament_cmake_package_templates/templates.cmake)
  returned error code 1
Call Stack (most recent call first):
  C:/dev/ros2_jazzy/share/ament_cmake_core/cmake/ament_cmake_coreConfig.cmake:41 (include)
  C:/dev/ros2_jazzy/share/ament_cmake/cmake/ament_cmake_export_dependencies-extras.cmake:15 (find_package)
  C:/dev/ros2_jazzy/share/ament_cmake/cmake/ament_cmakeConfig.cmake:41 (include)
  CMakeLists.txt:14 (find_package)

---
Failed   <<< examples_rclcpp_async_client [16.8s, exited with code 1]
Aborted  <<< examples_rclcpp_minimal_action_client [16.7s]
Aborted  <<< examples_rclcpp_minimal_publisher [16.6s]
Aborted  <<< examples_rclcpp_minimal_service [16.5s]
Aborted  <<< examples_rclcpp_minimal_action_server [16.7s]
Aborted  <<< examples_rclcpp_cbg_executor [16.8s]
Aborted  <<< examples_rclcpp_minimal_client [16.7s]
Aborted  <<< examples_rclcpp_minimal_composition [16.9s]

Summary: 0 packages finished [17.4s]
  1 package failed: examples_rclcpp_async_client
  7 packages aborted: examples_rclcpp_cbg_executor examples_rclcpp_minimal_action_client examples_rclcpp_minimal_action_server examples_rclcpp_minimal_client examples_rclcpp_minimal_composition examples_rclcpp_minimal_publisher examples_rclcpp_minimal_service
  8 packages had stderr output: examples_rclcpp_async_client examples_rclcpp_cbg_executor examples_rclcpp_minimal_action_client examples_rclcpp_minimal_action_server examples_rclcpp_minimal_client examples_rclcpp_minimal_composition examples_rclcpp_minimal_publisher examples_rclcpp_minimal_service
  14 packages not processed
WNDPROC return value cannot be converted to LRESULT
TypeError: WPARAM is simple, so must be an int object (got NoneType)

C:\dev\ros2_ws>

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
