### ISSUE TITLE
Colcon build error in windows 10 ros2 Jazzy

### ISSUE THREAD

**Issue by meqdad-ROS** [ros2/ros2#1632]
Hello everyone.
I am trying to install and run ROS 2 Jazzy on windows 10 latest update by following the long and uncomfortable nonsense steps as descried by the installation guide here "https://docs.ros.org/en/jazzy/Installation/Alternatives/Windows-Development-Setup.html"
after invoking the last install command "colcon build --merge-install" I face the following error: 

"
 warnings.warn(msg)
--- stderr: ament_clang_tidy
C:\Python312\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
---
Finished <<< ament_clang_tidy [12.3s]
Starting >>> ament_pclint
C:\Python312\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
C:\Python312\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
--- stderr: tinyxml2_vendor
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

CMake Error at C:/Program Files/CMake/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find TinyXML2 (missing: TINYXML2_LIBRARY TINYXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindTinyXML2.cmake:60 (find_package_handle_standard_args)
  CMakeLists.txt:7 (find_package)

---
Failed   <<< tinyxml2_vendor [46.8s, exited with code 1]
Aborted  <<< ament_pclint [5.01s]
Aborted  <<< eigen3_cmake_module [49.8s]
Aborted  <<< shared_queues_vendor [49.6s]
Aborted  <<< ament_cmake_vendor_package [3min 37s]
Aborted  <<< fastcdr [1min 7s]
Aborted  <<< iceoryx_posh [2min 3s]
Aborted  <<< foonathan_memory_vendor [4min 55s]

Summary: 63 packages finished [8min 18s]
  1 package failed: tinyxml2_vendor
  7 packages aborted: ament_cmake_vendor_package ament_pclint eigen3_cmake_module fastcdr foonathan_memory_vendor iceoryx_posh shared_queues_vendor
  45 packages had stderr output: ament_clang_format ament_clang_tidy ament_cmake_clang_format ament_cmake_copyright ament_cmake_cppcheck ament_cmake_cpplint ament_cmake_flake8 ament_cmake_gen_version_h ament_cmake_lint_cmake ament_cmake_mypy ament_cmake_pep257 ament_cmake_xmllint ament_copyright ament_cppcheck ament_cpplint ament_flake8 ament_index_python ament_lint ament_lint_auto ament_lint_cmake ament_mypy ament_package ament_pep257 ament_pycodestyle ament_pyflakes ament_xmllint domain_coordinator eigen3_cmake_module gmock_vendor google_benchmark_vendor gtest_vendor launch launch_testing launch_xml launch_yaml osrf_pycommon osrf_testing_tools_cpp ros_environment rosidl_cli rpyutils shared_queues_vendor test_interface_files tinyxml2_vendor tracetools_read urdfdom_headers
  293 packages not processed
WNDPROC return value cannot be converted to LRESULT
TypeError: WPARAM is simple, so must be an int object (got NoneType)
" 

my python version is 12. with the least pip updated version.  
my cmake version is 3.30.1
I changed the required minimum version of cmake to be {version 10 ... 30}

the following is the stderr.txt  log file for   tinyxml_vendor package. 
"CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

CMake Error at C:/Program Files/CMake/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find TinyXML2 (missing: TINYXML2_LIBRARY TINYXML2_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindTinyXML2.cmake:60 (find_package_handle_standard_args)
  CMakeLists.txt:7 (find_package)
" 
and the stdout.txt loog file for the same package is 
"-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.29.30154.0
-- The CXX compiler identification is MSVC 19.29.30154.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 2.5.2 (C:/jazzy/install/share/ament_cmake/cmake)
-- Found Python3: C:/Python312/python.exe (found version "3.12.6") found components: Interpreter
-- Configuring incomplete, errors occurred!
"

kindly guid me to solve this issue. 
attached the loog files for other aborted 7 packages.
[stdout_stderr.log](https://github.com/user-attachments/files/17982618/stdout_stderr.log)
[stdout_stderr.log](https://github.com/user-attachments/files/17982627/stdout_stderr.log)
[stdout_stderr.log](https://github.com/user-attachments/files/17982629/stdout_stderr.log)
[stdout_stderr.log](https://github.com/user-attachments/files/17982645/stdout_stderr.log)
[stdout_stderr.log](https://github.com/user-attachments/files/17982648/stdout_stderr.log)
[stdout_stderr.log](https://github.com/user-attachments/files/17982653/stdout_stderr.log)

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
