### ISSUE TITLE
Required disk space to build ROS 2 from source? 

### ISSUE THREAD

**Issue by danzimmerman** [ros2/ros2#1635]
## Issue Report

**Required Info:**

- Operating System:
  - Raspberry Pi OS with 6.12 PREEMPT_RT Kernel
- Hardware
  - Raspberry Pi 5
  - 32GB SD Card 
- Installation type:
  - Source
- Version or commit hash:
  - https://github.com/ros2/ros2/blob/jazzy/ros2.repos
- DDS implementation:
  - N/A
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue

Follow build instructions at https://docs.ros.org/en/jazzy/Installation/Alternatives/Ubuntu-Development-Setup.html with maybe 20GB free disk space on a 32GB SD card.

#### Expected behavior

Unknown

#### Actual behavior

Uses remaining 20GB of space and build fails.

#### Additional Information

Opening this because I don't know what to expect. `/opt/ros/jazzy` on an Ubuntu machine with a fresh binary install of ROS 2 Jazzy Desktop uses a little over 300MB, but I'm running out of disk space building ROS 2 Jazzy from source on a Raspberry Pi on a 32GB SD card. ~I don't know exactly but pretty sure I had >25GB free space when I kicked off the build.~ EDIT: there was about 20GB in my workspace when the build failed.

I'd like to make a PR for the docs about system requirements at https://docs.ros.org/en/jazzy/Installation/Alternatives/Ubuntu-Development-Setup.html#system-requirements that suggests a reasonable minimum free disk space. I'm rebuilding on a 128GB card shortly and can communicate whatever number I come up with. However, I wanted to ask if someone has better guidance, maybe buildfarm statistics?

I'm building ROS 2 from source on the Raspberry Pi 5 because I need the kernel support for the RP1 chip that runs a lot of the GPIO/peripheral interface hardware. I'd imagine a lot of people are using smaller disks here.

I'm invoking the build with 

```
colcon build --symlink-install --merge-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

I've done this before successfully on a 32GB card but it's possible it was borderline with some new package releases or other software I installed. It occurs to me that building in release mode without debug symbols should produce smaller binaries, but I'd rather have the debug info.

Obviously "buy a bigger SD card" is an easy workaround but a mention in the source install docs seems like something that would probably save others a bit of time and effort.

**Comment by Yadunund** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took including the terminal output describing the failure.
