### ISSUE TITLE
Push on console_bridge changes upstream

### ISSUE THREAD

**Issue by tfoote** [ros2/ros2#164]
Prioritize deboostifying, windows compile and 

And deconflicting API. need to go through tick-tock re: https://github.com/ros/console_bridge/issues/18

**Comment by wjwwood** [comment]
Boost has been removed and the Windows fixes were also merged by @scpeters.

I'll ping on ros/console_bridge#18, but it looks at least partially done. Can we close this?

**Comment by dirk-thomas** [comment]
The only pending issue I am aware of is ros/console_bridge#32. But we can close this already.

**Comment by wjwwood** [comment]
Ok, thanks.
