### ISSUE TITLE
Restructure Jenkins jobs

### ISSUE THREAD

**Issue by gerkey** [ros2/ros2#167]
Merge Windows jobs into a single job, with parameters to choose rmw implementation.

**Comment by dirk-thomas** [comment]
I merged the Windows jobs in this commit https://github.com/ros2/ros2/commit/4260cacd3562037de1182a14e261ccdca95d981c and already deployed the configuration. The opensplice jobs have been renamed, all the other jobs have an "old_" prefix. Also modrewrite rules are in place to redirect the old urls.
