### ISSUE TITLE
Document how to set up Git-LFS

### ISSUE THREAD

**Issue by esteve** [ros2/ros2#173]
For our OSX and Windows CI slaves.

See https://github.com/ros2/ros2/pull/165

**Comment by wjwwood** [comment]
Is this something we want to get done this alpha? Should we move it to the ready queue?

**Comment by esteve** [comment]
Yes, it's ok to move it to the ready queue.

**Comment by mikaelarguedas** [comment]
not needed now the :hamburger:  :hamburger: demo  is working (https://github.com/ros2/demos/issues/83)
