### ISSUE TITLE
consider adding date to our vendor packages

### ISSUE THREAD

**Issue by tfoote** [ros2/ros2#194]
It's a c++11 header only library designed to make chrono much easier to use. 

In looking around for platform independent c++ date/time solutions for the last warnings from https://github.com/ros/geometry_experimental/pull/153 I found date_v2. 

https://github.com/HowardHinnant/date

http://howardhinnant.github.io/date_v2.html

**Comment by clalancette** [comment]
We haven't done this until now, so I'm going to assume we aren't.  I'll close this out until there is a real need for a new date library.
