### ISSUE TITLE
Setup batch CI for Linux

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#2]
Acceptance Criteria: 

- [x] Create a batch script type CI testing to be batch run
- [x] report test result in jenkins job (# passed/failed)

**Comment by tfoote** [comment]
Basic scripts working here: https://github.com/tfoote/ros2_batch_ci
Jenkins job on the test farm here: http://54.183.26.131:8080/job/ros2_batch_ci/

Just need to switch back to master from pre_api_review branches.

**Comment by dirk-thomas** [comment]
Permission / ownership problem prevents to read the test results in the workspace: see http://54.183.26.131:8080/job/ros2_batch_ci/ws/ros2_ws/build/osrf_pycommon/

**Comment by tfoote** [comment]
@dirk-thomas The scripts are in a repo here for now: filed as in issue: https://github.com/tfoote/ros2_batch_ci/issues/3

**Comment by tfoote** [comment]
Job setup [here](http://54.183.26.131:8080/job/ros2_batch_ci/), and collecting test results. [ci job source](https://github.com/tfoote/ros2_batch_ci)
