### ISSUE TITLE
OpenSplice and FastRTPS are (sometimes) incompatible

### ISSUE THREAD

**Issue by gerkey** [ros2/ros2#211]
At least on OSX:

* `talker__rmw_opensplice_cpp` won't communicate with `listener__rmw_fastrtps` and
* `talker__rmw_fastrtps` won't communicate with `listener__rmw_opensplice_cpp`

Service calls between the two also don't work, probably on all platforms, but that is a known issue due to the underlying implementations of services.

**Comment by gerkey** [comment]
When this is fixed, revert the change in https://github.com/ros2/system_tests/pull/135.

**Comment by dirk-thomas** [comment]
Fixed by eProsima/ROS-RMW-Fast-RTPS-cpp#40.
