### ISSUE TITLE
Demonstrate depth camera running w/ ROS2

### ISSUE THREAD

**Issue by tfoote** [ros2/ros2#218]
Needed for Alpha 6

**Comment by simuloid** [comment]
Which depth camera are you using, Tully?

**Comment by tfoote** [comment]
That's specifically left unspecified, it will be either Kinect, Xtion, or Astra.

**Comment by simuloid** [comment]
Thanks.  I asked because I am using a product from IFM efector
http://www.ifm.com/ifmus/web/3d-ind-tools.htm

**Comment by dhood** [comment]
See https://github.com/ros2/turtlebot2_demo
