### ISSUE TITLE
Add coverage builds

### ISSUE THREAD

**Issue by gerkey** [ros2/ros2#230]
Start with gcov/lcov, reporting through a Jenkins plugin (e.g., Clover).

**Comment by dirk-thomas** [comment]
We might want to try the `Cobertura` plugin first since we already use that for Python coverage. And use `gcovr` since that generates coberture compatible result files.

**Comment by wjwwood** [comment]
Should this be closed or remain open until the follow up issues are resolved?

**Comment by gerkey** [comment]
The basics are there; we'll ticket problems and enhancements separately.
