### ISSUE TITLE
Add testing to Batch CI for Windows

### ISSUE THREAD

**Issue by tfoote** [ros2/ros2#24]
AC: 

- [x] Tests are run
- [x] Test results are summarized in jenkins

----

Follow up to ros2/ros2#6

**Comment by tfoote** [comment]
It's there and turning over and trying to test. I'd failing to build the tests at the moment. re: ament/ament_tools#23

It's configured to collect the tests, but they aren't being generated yet.

**Comment by wjwwood** [comment]
The windows job is turning over now, I propose we close this one.

@dirk-thomas @esteve @tfoote

**Comment by esteve** [comment]
@wjwwood Agreed.

**Comment by dirk-thomas** [comment]
The current job does not have a single successfully running test. Therefore I don't think this should be closed yet.

**Comment by wjwwood** [comment]
> The current job does not have a single successfully running test.

The `osrf_common` tests are running and being captured.

> Therefore I don't think this should be closed yet.

I would have preferred to open a new issue rather than continuously extend the criteria of this issue, but since we've already done it, we can leave it I guess.

**Comment by dirk-thomas** [comment]
Done.
