### ISSUE TITLE
FastRTPS rmw settings are not applied

### ISSUE THREAD

**Issue by adamdbrw** [ros2/ros2#247]
QoS settings currently do not work in rmw_fastrtps_cpp

QoS settings have default values (default for containing structs) instead of what is set. Input settings are ignored due to error in value/reference semantics in function signature.

Fix for the issue: https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/pull/42

**Comment by dirk-thomas** [comment]
Thank you for the fix.
