### ISSUE TITLE
Make test reporting optional in CI jobs

### ISSUE THREAD

**Issue by gerkey** [ros2/ros2#249]
For the coverage build, we want to run tests and report on coverage, but not report the test results. At the moment, I've manually deleted the xUnit section of the configuration for that job. The right fix is make the job configuration infrastructure flexible enough to allow xUnit reporting to be turned on/off per job during deployment.

**Comment by dirk-thomas** [comment]
I don't think we need to disable the xUnit reporting for the coverage job. By now we have all tests passing (at least when retrying for flaky tests).
