### ISSUE TITLE
lost of ROS2 dependency in tutorial

### ISSUE THREAD

**Issue by shengwen1997** [ros2/ros2#257]
Hello, thanks for all of your wonderful hardworking!

I tried to build ROS2 on my raspberry pi3 (Ubuntu Mate 16.04),
and I find the project is rely on "libgtest-dev", which is not written in the tutorial.

I think it will be helpful to put this in the tutorial:
* sudo apt-get install libgtest-dev

**Comment by wjwwood** [comment]
@shengwen1997 I'm going to close this for now, feel free to update it with a comment later and I can reopen it if necessary.
