### ISSUE TITLE
M_PI not defined in ros2/demos/pendulum_control/src/pendulum_teleop.cpp

### ISSUE THREAD

**Issue by Harin55** [ros2/ros2#263]
Hello again,

with alpha7 and building the entire sources on a upgraded Debian the build brakes because of an undefined use of `M_PI` in src/ros2/demos/pendulum_control/src/pendulum_teleop.cpp.
I add `#include <math.h>` and it runs like a charm.

**Comment by wjwwood** [comment]
Thanks for the report @Harin55, can you open a pull request? That way you get attribution for the fix. The code is located here:

https://github.com/ros2/demos/blob/27e765778afba76173824c9700a77ae093f50dc3/pendulum_control/src/pendulum_teleop.cpp#L29

**Comment by Harin55** [comment]
done
