### ISSUE TITLE
ROS 1 bridge not in Linux binary distribution

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#266]
@geoffviola I reverted your wiki change here:

https://github.com/ros2/ros2/wiki/Linux-Install-Binary/_compare/419c58fb171c6f66baa7d5fd8c861c5afc43b8bb...ae967707b9f9651a88ae377eb412444c1ffadb93

The dynamic_bridge is supposed to be in the Linux binary package, but that broke when we changed to Xenial (kinetic) from Trusty (indigo). Thanks for catching the problem for us though, we're looking into it.

**Comment by geoffviola** [comment]
I guess it was a little rash to delete the whole thing without review. My intention was to delete it since it didn't reflect the current alpha, but I can see it act as a TODO. Thanks for the update.

**Comment by wjwwood** [comment]
Well, it's not a TODO so much as what should be. I consider the current state to be a bug. We'll fix the binary.

**Comment by wjwwood** [comment]
Ok, I updated the binaries and posted them here:

https://github.com/ros2/ros2/releases/tag/release-alpha7

The binaries with `-1` added to the name have the dynamic bridge.

**Comment by geoffviola** [comment]
thanks

**Comment by wjwwood** [comment]
Sure, no problem. Thanks for pointing it out to us.

**Comment by dirk-thomas** [comment]
The released `ros1_bridge` binaries with OpenSplice still don't work. There are linked against the wrong type support: see ros2/ros1_bridge#30
