### ISSUE TITLE
[windows] hardcoded filepath for release.bat in opensplice

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ros2#268]
I couldn't get the talker to run as the setup.bat failed beforehand. Reason for this was the hardcoded filepath `c:\dev\opensplice\HDE...` for opensplice. AFAIK, there is no check whether the OSPL_HOME variable was already set.

quick fix solution:

```
if "%OSPL_HOME%" == "" (
    set OSPL_HOME=C:\dev\opensplice\HDE\x86_64.win64
    echo OSPL_HOME variable not set. Assuming %OSPL_HOME%
)
```

**Comment by Karsten1987** [comment]
I've just seen [this](https://github.com/ros2/rmw_opensplice/blob/master/opensplice_cmake_module/env_hook/opensplice.bat.in#L1) which seems to fix that. However, the latest windows release suffers still from the problem.

**Comment by dirk-thomas** [comment]
The proposed patch looks good to me. Please create a pull request with it.

**Comment by dirk-thomas** [comment]
The proposed patch looks good to me. Please create a pull request with it.

For Connext we do a [similar check](https://github.com/ros2/rmw_connext/blob/master/connext_cmake_module/env_hook/connext.bat.in). Maybe warn about the difference?

**Comment by Karsten1987** [comment]
I think the problem may only occur on the release side. 
the first line of release.bat of the windows release: `set "OSPL_HOME=C:/dev/opensplice/HDE/x86_64.win64"` 

where are the values set in the first place?

**Comment by dirk-thomas** [comment]
The file is expanded from CMake (https://github.com/ros2/rmw_opensplice/blob/919206678d6028edb56d5c99aa99434bd58edba4/opensplice_cmake_module/CMakeLists.txt#L16) using [configure_file](https://cmake.org/cmake/help/v3.5/command/configure_file.html),

**Comment by dhood** [comment]
closed by https://github.com/ros2/rmw_opensplice/pull/219
