### ISSUE TITLE
[linux] cam2image__rmw_fastrtps aborts

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ros2#270]
```
karsten@karsten-bosch:~$ cam2image__rmw_fastrtps_cpp 
Publishing image #1
vector overcomes the maximum length
terminate called after throwing an instance of 'std::runtime_error'
  what():  vector overcomes the maximum length
Aborted
```

should this issue rather be reopened for the rtps repo?

**Comment by wjwwood** [comment]
That's an exception, and I think it is expected unless you're using master. There are issues on the fastrtps rmw implementation about this:

https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/issues/36

**Comment by dirk-thomas** [comment]
This should be solved with the Alpha 8.
