### ISSUE TITLE
Implementation of parameters in rcl / rclcpp

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#28]
AC:

- [x] user accessible API
- [ ] demo application using parameters
  - [x] get
  - [x] set
  - [x] list
  - [ ] on_update
  - [ ] on_change
  - [ ] on_create
  - [ ] on_delete

**Comment by gerkey** [comment]
We need to schedule a design review for this API, in particular to discuss the class structure of the parameter API (e.g., moving some of its functionality out of Node).
