### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by CharlieViescas** [ros2/ros2#280]
New on ROS!!
Executing comand 

src/ament/ament_tools/scripts/ament.py build --build-tests --symlink-install

found an error:
 
 File "src/ament/ament_tools/scripts/ament.py", line 56, in <module>
    from osrf_pycommon.cli_utils import verb_pattern  # noqa
  File "/Users/CharlieViescas/ros2_ws/src/ament/osrf_pycommon/osrf_pycommon/cli_utils/verb_pattern.py", line 17, in <module>
    import pkg_resources
ImportError: No module named 'pkg_resources'

How can I fix it?

**Comment by tfoote** [comment]
pkg_resources is a module provided by python setuptools. Make sure your setuptools is installed an up to date. https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

If you're new to ROS, ROS2 is not recommended for use at the moment. It's under heavy development and not considered stable. I'd recommend getting started over here: http://wiki.ros.org/ROS/Tutorials
