### ISSUE TITLE
Beta 1 on the 16th of December

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#281]
- [x] Composition 
  - [x] Using class loader, ~~pluginlib~~, ament index, C++ only with intention that interface is less language specific where possible ros2/demos#84 @dirk-thomas @wjwwood
  - [x] add examples @codebot
  - [x] ~~convert old examples to tutorials with narratives showing composition-friendly patterns, etc. @dhood with help from friends~~ We ended up not including the tutorials, but now have examples of both composition and write-your-own-main in ros2/examples.
- [x] Lifecycle management  @Karsten1987 @tfoote 
  - [x] merge the state machine implementation in C
  - [x] default values from lifecycle messages to avoid duplication in rcl
  - [x] refactor lifecycle node and ~~subscriptions~~ (subscriptions still outstanding: https://github.com/ros2/rclcpp/pull/292) using refactored rclcpp
  - [x] demo package
- [x] QoS demos: unreliable comms, illustrated by wifi out-and-back @dhood 
  - [x] tutorial narrative
  - [x] using ros 2 to bridge multiple ros 1 systems
- [x] rclcpp architecture improvements @wjwwood 
  - [x] everything but parameters
  - [x] parameters
- [ ] Design documents for open questions/discussions @wjwwood (and everyone else)
  - [ ] Node-to-participant mapping design
  - [ ] Uniqueness of node names design
  - [x] namespaces of topics and services
  - [ ] Async vs sync publishing
  - [ ] Service provider: content-oriented or host-oriented
  - [ ] How to communicate remappings (cmd args, launch file, param file, etc.)
- [x] simple examples / tutorials / cookbook @mikaelarguedas @codebot
- [x] update patch for services over ros12 bridge to work with newly improved bridge

**Deferred goals:**
- [ ] rclcpp namespace improvements and cleanup
- [ ] callbacks for changes in liveliness
- [ ] extend TakeWithMessageInfo() to include the source timestamp for latency estimation

**Stretch goals:**
- [ ] Creating coherent list for external contributors of separable self-contained non-critical path items
- [ ] `rostopic list`, `rostopic echo` and friends @mikaelarguedas and @vmayoral
- [x] rclpy
  - [x] waitset + real spin function
  - [x] timers
  - [x] services
- [ ] Setting parameters
  - [ ] C parameters
  - [ ] Python parameters
- [ ] Bulk deb packages using FastRTPS: core and demos (which require opencv etc)
- [ ] reconsidering type support to avoid the need for separate libraries of X for each type support @dirk-thomas
  - [x] "meta" typesupport for C++ ros2/rosidl#182
  - [ ] "meta" typesupport for C
  - [ ] invert dependency direction between `rosidl_typesupport_*` and rmw implementations in order to implement one-rmw-impl. optimization
  - [ ] "meta" rmw

**Comment by gbiggs** [comment]
I have some time to work on rostopic, if that's helpful. I spoke with @wjwwood at ROSCon and he asked me to start a topic on Discourse to discuss the options for implementing it, in light of the distributed nature of ROS2.

I can also contribute to the life cycle stuff, although it sounds like that's already covered by people with time to do it.

**Comment by vmayoral** [comment]
@mikaelarguedas refer to http://discourse.ros.org/t/rostopic-implementation-discussion/674/2?u=vmayoral.

**Comment by dirk-thomas** [comment]
:ship: https://github.com/ros2/ros2/releases/tag/release-beta1
