### ISSUE TITLE
Clean up cmake output

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#29]
Currently there are tonnes of debug messages being output to the console, which is good while developing, but it's also starting to make it more difficult to find important information. We should go through the ament cmake code and find as many places as possible to replace `message()` with some macro that we can enable and disable with a CMake argument, maybe something like `AMENT_VERBOSE` or something like that.

**Comment by dirk-thomas** [comment]
I have removed a lot of debug messages in various repositories. The output should be much less verbose now.

I will mark this closed for now. If there is anything specific remaining which you think should be removed please comment / reopen.
