### ISSUE TITLE
keeping track of disabled tests

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#290]
We have a lot of disabled tests that we sometimes forget to reenable when feature is implemented. (e.g https://github.com/ros2/examples/pull/131 or https://github.com/ros2/demos/pull/83 thanks @dhood for flushing them out)
The goal here is to mark them all as skipped so that they show up as such in CI:
- [x] expand `ament_add_*test` macros to take a skip flag (https://github.com/ros2/rcl/pull/90 and https://github.com/ament/ament_cmake/pull/80)
- [x] generate result files so that they show up in Jenkins (https://github.com/ament/ament_cmake/pull/80)
- [x] make ament test result report skipped tests (https://github.com/ament/ament_tools/pull/125)
- [x] go through the codebase to flag all the disabled tests as `skipped`
- [x] modify `ament test_result` to detect skipped Gtest (they don't set the skip flag in the JUnit root xml node) https://github.com/ament/ament_tools/pull/126
- [x] [C tests don't use any framework](https://github.com/ros2/rosidl/blob/master/rosidl_generator_c/test/test_interfaces.c) and don't generate any result file, (so failing tests are not reported on jenkins or with `ament test_results`) fixed by https://github.com/ros2/rosidl/pull/185

**Comment by mikaelarguedas** [comment]
Rationale:
- provide a clear list of all the tests that we don't expect to pass
- give visibility of the features/configurations that are not expected to work in the current state
- provide insight for external contributors on where to look at if they want to improve the feature parity (xPlatforms/xRMWs/xClientLibraries)

**Comment by mikaelarguedas** [comment]
@dhood assigning this to you given that you took over labeling the skipped tests

**Comment by dhood** [comment]
I have gone through the codebase and the only remaining unlabeled skipped tests I could find have been labeled in https://github.com/ros2/demos/pull/114 and https://github.com/ros2/rcl/pull/109

For documentation purposes: the skipped tests are not reported as an enumerated list in the test report, but can be seen if you click through test results with >0 skipped tests, e.g.: http://ci.ros2.org/view/nightly/job/nightly_win_rel/338/testReport/(root)/test_communication/
