### ISSUE TITLE
change the "overlay workspace" path in the ament tutorial

### ISSUE THREAD

**Issue by dhood** [ros2/ros2#292]
both the catkin overlay tutorial and the ament overlay tutorial use `~/overlay_ws` . To avoid users accidentally mixing their workspaces I will change [the ament tutorial](https://github.com/ros2/ros2/wiki/Ament-Tutorial#create-an-overlay) to use '~/ros2_overlay_ws` instead unless anyone objects

**Comment by mikaelarguedas** [comment]
+1

**Comment by wjwwood** [comment]
+1

**Comment by dhood** [comment]
thank you both! done now
