### ISSUE TITLE
Add tests for the ignore_local_publications flag

### ISSUE THREAD

**Issue by dhood** [ros2/ros2#293]
see https://github.com/ros2/ros2/issues/291

This isn't supported in `rmw_fastrtps_cpp` https://github.com/ros2/rmw_fastrtps/issues/76 but is in [`rmw_connext_cpp`](https://github.com/ros2/rmw_connext/blob/master/rosidl_typesupport_connext_cpp/resource/msg__type_support.cpp.em#L280-L294)

**Comment by clalancette** [comment]
I believe that this was implemented with https://github.com/ros2/rmw_implementation/pull/192, so closing.
