### ISSUE TITLE
Update packages to use QA tools

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#3]
AC:

- [x] Example packages running QA tools like linters
- [x] update c/c++ linter configurations for 1 of these
  - [x] cppcheck
  - uncrustify - separated: #14
  - cpplint - separated: #12
  - clang_format - separated: #13
- [x] update existing packages to use the existing tools, as an automated test
- [x] documentation about how to use tools

----

**Comment by dirk-thomas** [comment]
ament/ament_lint#2 implements the necessary CMake infrastructure to register default linters with minimal code.

**Comment by dirk-thomas** [comment]
ros2/rosidl#5 updates two packages to use the new functionality as well as register its nosetests.

**Comment by wjwwood** [comment]
Connects to ros2/rosidl#5

**Comment by dirk-thomas** [comment]
The linter packages now also use other linters as far as possible: https://github.com/ament/ament_lint/commit/9c9fd1e06f950ad3f1a235f029b35b112b9d1ca2

**Comment by dirk-thomas** [comment]
Do you consider this (https://github.com/ament/ament_lint/blob/docs/ament_clang_format/doc/index.rst) to be sufficient to describe how to use the linters? I just want to get some first feedback before writing N if these.

**Comment by dirk-thomas** [comment]
The configuration for `cppcheck` is pretty standard and looks reasonable to me. It currently does not generate a failing test.

**Comment by dirk-thomas** [comment]
The documentation for the linter packages is in: ament/ament_lint#9
