### ISSUE TITLE
revisit type support identifiers

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#30]
After the refactoring to support C as well as Windows the type support identifiers are not working as they were before.

E.g. for Connext XTypes a string comparison is necesssary (ros2/rmw_connext#2). For other type supports the check is not being performed anymore.

**Comment by wjwwood** [comment]
Yeah, this is my fault, I wasn't aware that the identifier check was being done in this manner (not using `strcmp`). Hopefully this kind of thing will happen less often once we get some CI. Ideally when we revisit this we'll have some automated test which ensures it is still working.

**Comment by dirk-thomas** [comment]
The two PRs address the Connext XTypes only. I still have to look for a similar solution for the other type supports.

**Comment by dirk-thomas** [comment]
Two more PRs to readd typesupport checking to static connext and opensplice.

Ready to be reviewed.

**Comment by wjwwood** [comment]
Are there any more outstanding PR's that need to be made for this? If not I think it's good to move to 'done'.
