### ISSUE TITLE
Control shared/static linking via BUILD_SHARED_LIBS and ament_cmake_ros

### ISSUE THREAD

**Issue by esteve** [ros2/ros2#306]
Just an issue to aggregate all the connected PRs so that it shows up on the waffle board

**Comment by dirk-thomas** [comment]
The following CI jobs cover:

* ament/gtest_vendor#4
* ament/gmock_vendor#3
* ros2/rmw#98
* ros2/rcl#115

---

* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2415)](http://ci.ros2.org/job/ci_linux/2415/)
* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1868)](http://ci.ros2.org/job/ci_osx/1868/)
* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2536)](http://ci.ros2.org/job/ci_windows/2536/)

**Comment by dirk-thomas** [comment]
@esteve Waiting for updates / responses on the following PRs:

* ros2/rosidl#183
* ros2/rosidl_typesupport#10
* ros2/rmw_fastrtps#87

**Comment by dirk-thomas** [comment]
* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2457)](http://ci.ros2.org/job/ci_linux/2457/)
* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1910)](http://ci.ros2.org/job/ci_osx/1910/)
* [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2575)](http://ci.ros2.org/job/ci_windows/2575/)

**Comment by esteve** [comment]
@dirk-thomas I assume you didn't pass `BUILD_SHARED_LIBS` to the CI build (i.e. the build is using the default `SHARED` value), right? If that's the case, it seems the code in https://github.com/ros2/rosidl_typesupport/pull/10 doesn't read the `BUILD_SHARED_LIBS` variable as expected. Should `ament_cmake_ros` be added as an export dependency and added to https://github.com/ros2/rosidl_typesupport/blob/master/rosidl_typesupport_c/rosidl_typesupport_c-extras.cmake.in and https://github.com/ros2/rosidl_typesupport/blob/master/rosidl_typesupport_cpp/rosidl_typesupport_cpp-extras.cmake.in ?

**Comment by dirk-thomas** [comment]
I am not sure if exporting `ament_cmake_ros` is a good idea. In that case a package might not directly depend on `ament_cmake_ros` but implicitly use it through the typesupport dependencies. I would think that users will get confused why their by default statically linked libraries are suddenly linked shared.

**Comment by esteve** [comment]
@dirk-thomas that's a good point, I hadn't thought about that. I've pushed https://github.com/ros2/rosidl_typesupport/pull/10/commits/853357e532322b64040f7b636855dcc0c4bfa3f9 with a workaround, I don't know if it'd suffice, but that logic should only take effect if the user deliberately chooses to build libraries as static by setting `BUILD_SHARED_LIBS` to `OFF` / `FALSE` explicitly.

**Comment by dirk-thomas** [comment]
Please see https://github.com/ros2/rosidl_typesupport/pull/10#issuecomment-295814568 for the latest comment on this.

**Comment by dirk-thomas** [comment]
Any news on this?

**Comment by esteve** [comment]
@dirk-thomas see https://github.com/ros2/rosidl/pull/183#issuecomment-307049531

**Comment by mikaelarguedas** [comment]
@esteve I'm going to put this in backlog due to the low activity and the fact that we are not planning on allocating time to this in the next cycle. We will still happily review and test changes to the referenced PRs

**Comment by esteve** [comment]
@mikaelarguedas the last missing piece of this is https://github.com/ros2/rosidl/issues/183, I proposed a solution but I don't know if that's the correct one (https://github.com/ros2/rosidl/pull/183#issuecomment-307049531). I'll gladly work on it, but @dirk-thomas seemed to have his doubts about the proposed solution in https://github.com/ros2/rosidl/pull/183#issuecomment-307163340

I can go ahead and implemented what I proposed (adding `ament_cmake_ros` to message packages) if it has a chance of being considered for merging. But if there's any other proposal, I can implement that either.

**Comment by dirk-thomas** [comment]
I am closing this in favor of #468 which aggregates the PRs which are currently being worked on.
