### ISSUE TITLE
Windows isolated build results in "input line is too long"

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ros2#323]
I just compiled my workspace under windows 10, wanted to setup my environment and ran into the following error. Did anybody encounter this already?

```
c:\dev\ros2>call install_isolated\local_setup.bat
The input line is too long.
The syntax of the command is incorrect.
```

connects to ament/ament_package#58

**Comment by dirk-thomas** [comment]
That is a common limitation on Windows. Can you please post the line in question.

**Comment by mikaelarguedas** [comment]
Unfortunately that's a known issue. I started to look into using powershell for everything. That'll allow us to overcome any limitation due to cmd. It won't solve the maximum `PATH` length though (AFAIK)

**Comment by Karsten1987** [comment]
https://support.microsoft.com/en-us/help/830473/command-prompt-cmd.-exe-command-line-string-limitation

**Comment by Karsten1987** [comment]
I don't have the line in question, but I am almost certain it's the `PATH` variable, which contains more than 8192 characters.

**Comment by mikaelarguedas** [comment]
Yeah I think that's the issue too. Quick hack is to not build in isolation, this way you add a single folder to your PATH rather than N (where N number of packages)

**Comment by Karsten1987** [comment]
So i can confirm that building in non-isolated prevents that long `PATH` variable to be set. This may be important when building the binary packages for Windows.

**Comment by mikaelarguedas** [comment]
this should be fixed once we move away from batch in favor of powershell so I'm going to connect theses issues together
