### ISSUE TITLE
Implement Namespacing

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ros2#327]
I open this issue here for keeping track about connecting PRs and status updates regarding namespacing.

The implementation is w.r.t. the design page: http://design.ros2.org/articles/topic_and_service_names.html

Namespacing has to be implemented in each rmw implementation for each communication method.

<>                   | connext_static | connext_dynamic | fastrtps | opensplice (optional)
--------------|----------------|------------------|---------|---------------------
publisher        |            PR221        |     TBD                  |    PR100   |         TBD                            
subscriber      |           PR221         |     TBD                  |    PR100   |        TBD
service            |           PR221         |     TBD                  |    PR100   |        TBD
client              |           PR221        |     TBD                  |    PR100   |        TBD

I further plan on writing a general function inside rmw, which concatenates the original topic name with the prefixes for the communication method. The list of prefixes can be found here: http://design.ros2.org/articles/topic_and_service_names.html#ros-specific-namespace-prefix

connected PRs:

- demo: https://github.com/ros2/demos/pull/122
- rcl (for tests): https://github.com/ros2/rcl/pull/135
- connext: https://github.com/ros2/rmw_connext/pull/221
- fastrtps: https://github.com/ros2/rmw_fastrtps/pull/100

**Comment by Karsten1987** [comment]
linux: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2413)](http://ci.ros2.org/job/ci_linux/2413/)
osx: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1862)](http://ci.ros2.org/job/ci_osx/1862/)
windwos: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2532)](http://ci.ros2.org/job/ci_windows/2532/)

**Comment by Karsten1987** [comment]
Ok, so I believe this is up for review!

**Comment by dirk-thomas** [comment]
Is the new feature / functionality covered by any test atm?

**Comment by Karsten1987** [comment]
I just updated the initial description of this PR and referenced the `rcl` PR with it. I had forgotten this one. 
The namespace feature set is not so much covered by this one single test, however given that all existing pub/sub/srv/client system tests are working, I believed it is tested within these tests.

**Comment by wjwwood** [comment]
@Karsten1987 I fixed all of your "connects to ..." comments as they were broken.

**Comment by Karsten1987** [comment]
linux: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2583)](http://ci.ros2.org/job/ci_linux/2583/)
osx: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2051)](http://ci.ros2.org/job/ci_osx/2051/)
windows: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2706)](http://ci.ros2.org/job/ci_windows/2706/)

**Comment by Karsten1987** [comment]
I had to modify "get_topic_names_and_types" inside `rmw_fastrtps` in order to make that test pass for fastrtps. While doing, I also modified `rmw_connext` to behavior equivalently. 
When running tools like `rostopic_list` the output corresponds to the fully qualified domain name:

```
rq/my/namespace/test_namespace_client_serverRequest [example_interfaces::srv::dds_::AddTwoInts_Request_]
rr/my/namespace/test_namespace_client_serverReply [example_interfaces::srv::dds_::AddTwoInts_Response_]
rt/parameter_events [rcl_interfaces/ParameterEvent]
```

I will open another issue to refactor `get_topic_names_and_types` in order to give a list of publishers, subscribers, services and clients, because I think this exceeds the scope of this PR. 

I am running CI again to check if this has further consequences for other tests.
Linux: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2586)](http://ci.ros2.org/job/ci_linux/2586/)
osx: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2054)](http://ci.ros2.org/job/ci_osx/2054/)
windows: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2712)](http://ci.ros2.org/job/ci_windows/2712/)

One more note, as I developed locally on my machine, I've seen that fastrtps and connext indeed to talk to each other via services. So I wonder, why we deactivated tests for this.

**Comment by Karsten1987** [comment]
So there is definitely some flakiness involved, but I would say this is ready w.r.t upcoming refactor of `get_topic_names_and_types`.

**Comment by wjwwood** [comment]
@Karsten1987 I'm running one more "repeated nightly" job to gauge the flakey-ness. @dirk-thomas is also looking into an issue with flakey tests related to https://github.com/ros2/rcl/pull/120 which might address your pr's. My theory is that these flakey tests are just exacerbated by the use of partitions making things take a different amount of time, exposing existing race conditions.

**Comment by wjwwood** [comment]
Using this job (nightly settings for these prs):

http://ci.ros2.org/job/ci_linux/2608/testReport/

And comparing it to this nightly:

http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/655/testReport/

I figured out that these tests were unique to the first job, but found them in other recent nightlies:

- `projectroot.rosidl_generator_py.test_requester_replier__Primitives__rclpy__rmw_fastrtps_cpp`
  - http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/649/testReport/
- `projectroot.test_composition__rmw_fastrtps_cpp`
  - (paired with `composition.test_composition__rmw_fastrtps_cpp.xunit.missing_result`)
  - http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/650/testReport/
- `test_requester_replier__Primitives__rclpy__rmw_fastrtps_cpp_.test_requester_replier`
  - http://ci.ros2.org/view/nightly/job/nightly_linux_repeated/651/testReport/

So, based on that I don't see any new flakey tests.

I'll go ahead and merge this, and continue work on the final set of prs for this feature.
