### ISSUE TITLE
Compare OSX unit test results with Linux

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#33]
Depends on ros2/ros2#21

AC:

- [ ] either equal test counts or
- [ ] known differences
- [x] cppcheck missing
- [x] uncrustify missing (http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_osx/ws/workspace/build/rcl/Testing/Temporary/LastTest.log/*view*/)
- [x] PEP8 test failing but not on Linux (due to newer version of PEP8): https://github.com/ament/ament_lint/commit/9a51c71c3e15c2fab2c63e567118e7574cc417ed
- [x] nosetests error about indentation in osrf_pycommon, not failing on Linux, may be specific to the flake version being used?

**Comment by dirk-thomas** [comment]
* cppcheck missing
* PEP8 test failing but not on Linux

**Comment by wjwwood** [comment]
ros2/ros2#31

**Comment by gerkey** [comment]
Can be closed with a lower test count if we can show that the missing tests are due to the lack of Connext, because of ros2/ros2#31.

**Comment by wjwwood** [comment]
Linux (without Connext) currently has 408 tests:

http://54.183.26.131:8080/job/ros2_batch_ci_linux/50/testReport/

OS X has 401 tests:

http://54.183.26.131:8080/job/ros2_batch_ci_osx/93/testReport/

I'm looking at the differences.

**Comment by wjwwood** [comment]
Actually after running an up-to-date build of OS X it also has 408 now:

http://54.183.26.131:8080/job/ros2_batch_ci_osx/94/testReport/
