### ISSUE TITLE
change repo/branch for urdfdom_headers

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ros2#331]
The current branch of the urdfdom_headers is set to `math_h`. https://github.com/ros2/ros2/blob/master/ros2.repos#L181

This is due to an open PR on the ROS(1) orga: https://github.com/ros/urdfdom_headers/pull/34
Once this gets resolved (either accepted or closed), I'll take appropriate action to change our current ROS2 branch or change the repos file for the ros1 orga.

**Comment by mikaelarguedas** [comment]
@Karsten1987 are you following up on the upstream PR for this ?

**Comment by Karsten1987** [comment]
closed in https://github.com/ros2/ros2/pull/347
