### ISSUE TITLE
DDS Security support

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#339]
meta ticket to aggregate PRs

**Comment by mikaelarguedas** [comment]
first security tests on all platforms :crossed_fingers: (code will still need to be cleaned up a bit before review)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2643)](http://ci.ros2.org/job/ci_linux/2643/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=200)](http://ci.ros2.org/job/ci_linux-aarch64/200/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2101)](http://ci.ros2.org/job/ci_osx/2101/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2764)](http://ci.ros2.org/job/ci_windows/2764/)

**Comment by mikaelarguedas** [comment]
Placing this in review, I'll comment on individual PRs to point to where I'm looking for advice. Most of it should be pretty digestible, only the system_tests one will be a bit painful to review

**Comment by dirk-thomas** [comment]
Overall the PRs look good. I made a few small comments.

One thing I am concerned about is how deeply the security feature is embedded into the API. Imo it would be preferred if the codebase could be build without using anything security related. Yes, it can be "not used" and an rmw provider can simply return errors but I was more thinking about not being part of the API when not being used. In the DDS spec that is basically achieved by making the security specific stuff part of the the dynamic QoS flags. (Anyway this is not an argument to delay merging this as is. It is more trying to formulate the vision I think this should be going to in the future to avoid this tight coupling.)

**Comment by mikaelarguedas** [comment]
> Yes, it can be "not used" and an rmw provider can simply return errors but I was more thinking about not being part of the API when not being used.

That is a good point. I think we can revisit this once we want to provide an extensible / pluggable option system to node participant / creation. I will not target this in this set of PRs but that's definitely something that we should keep in mind in the future.

**Comment by mikaelarguedas** [comment]
another round of CI now that every branch has been approved and rebased:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2735)](http://ci.ros2.org/job/ci_linux/2735/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=271)](http://ci.ros2.org/job/ci_linux-aarch64/271/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2200)](http://ci.ros2.org/job/ci_osx/2200/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2865)](http://ci.ros2.org/job/ci_windows/2865/)

**Comment by mikaelarguedas** [comment]
:green_apple: :green_book: :green_heart: :green_heart: 
Merging

**Comment by wjwwood** [comment]
@mikaelarguedas, so sorry to say some new nightlies are now unstable and it looks related to the security changes 😧:

http://ci.ros2.org/job/nightly_win_rel/463/testReport/

**Comment by mikaelarguedas** [comment]
:confounded: Forgot to deploy the changes to CI so the job were not reconfigured to pass -DSECURITY=ON. I'll add an option so that the security tests are ran only if this option is passed. Thanks for letting me know

**Comment by mikaelarguedas** [comment]
Deployed. I noticed that the packaging jobs don't use a the same default arguments so they won't use the -DSECURITY options just yet. I'll open a follow up PR

**Comment by dirk-thomas** [comment]
The current cmake flags don't work when passing some flags behind them: http://ci.ros2.org/job/ci_osx/2204/console

**Comment by mikaelarguedas** [comment]
Reported on the appropriate issue [here](https://github.com/ros2/ci/issues/51#issuecomment-308776348)

**Comment by mikaelarguedas** [comment]
Evey PR landed :tada: . Closing this
