### ISSUE TITLE
Cartographer support

### ISSUE THREAD

**Issue by clalancette** [ros2/ros2#342]
This is a meta-ticket for Cartographer support in ROS2.

**Comment by mikaelarguedas** [comment]
@clalancette Can this ticket be closed ?

**Comment by mikaelarguedas** [comment]
Yeah I don't think we should keep a ticket open for every package we want to improve. Specific issues about what to improve is more relevant IMO. (it's also to cleanup the waffleboard because my screen is getting too small for this ticket)

**Comment by mikaelarguedas** [comment]
> (like ros2/teleop_twist_joy#3, etc)

This is not related to cartographer and will be useful for any demo using teleop of any robot

**Comment by clalancette** [comment]
Heh, OK.  Closing it out, then.

**Comment by YuehChuan** [comment]
HI, wonder is there some details  about how to  make ROS2  on Cartographer? TQ!

**Comment by clalancette** [comment]
@YuehChuan We're still in the process of writing the documentation for it.  Once that is done, it should be available in the https://github.com/ros2/turtlebot2_demo repository (or, at least, linked to from there).

**Comment by mikaelarguedas** [comment]
Hi @YuehChuan, we will give instructions of how to build and run the cartographer demo on [this repository](https://github.com/ros2/turtlebot2_demo). The instructions will be available in the next week or 2

**Comment by YuehChuan** [comment]
@clalancette , @mikaelarguedas ,Thanks for the info! I just notice the reply now. Now I'm compiling ros2 beta2 on raspberry pi3.
