### ISSUE TITLE
dealing with crashes due to misuse of rmw_subscriptions_t

### ISSUE THREAD

**Issue by BrannonKing** [ros2/ros2#352]
From the file rmw/types.h, we have this tidbit:

```cpp
 /* An array of void * pointers representing type-erased middleware-specific subscriptions.
 * The number of non-null entries may be smaller than the allocated size of the array.
 * The number of subscriptions represented may be smaller than the allocated size of the array.
 * The creator of this struct is responsible for allocating and deallocating the array.
 */
typedef struct RMW_PUBLIC_TYPE rmw_subscriptions_t
...
```
From that description, I don't believe one can assume that the non-null entries are consecutive. This is not implemented correctly in these files:
rmw_opensplice_cpp/src/rmw_wait.cpp
rmw_opensplice_cpp/src/rmw_take.cpp
rmw_connext_cpp/src/functions.cpp
rmw_connext_shared_cpp/shared_functions.hpp
rmw_connext_dynamic_cpp/src/functions.cpp
rmw_fastrtps_cpp/src/functions.cpp
rmw_coredx_cpp/src/functions.hpp

To find the issue, search for the text "subscriber info handle is null" or "subscriber_count;". A correct implementation would skip nulls (aka, continue) rather than throw an exception when a null subscriber is encountered. rmw_fastrtps simply assumes that they are never null.

**Comment by clalancette** [comment]
All of this has been substantially rewritten since 2017, so I'm going to close this out.  Do feel free to reopen if you see a specific problem still.
