### ISSUE TITLE
include debug libraries for OpenCV

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#353]
In the archive https://github.com/ros2/ros2/releases/download/release-alpha1/opencv-2.4.11-win-vs2015-x64.zip

Once the debug libraries are being used the workaround from ros2/vision_opencv#6 can be reverted.

**Comment by mikaelarguedas** [comment]
This has the potential of fixing the `cam2image` and `showimage` test faillures on windows debug (they consistently fail on all the machines)

**Comment by mikaelarguedas** [comment]
I can confirm that both the `image_geometry` and the `image_tools` tests pass once openCV debug libraries installed:
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=test_windows_debug&build=3)](http://ci.ros2.org/view/All/job/test_windows_debug/3)

Though not sure what the best way to release them alongside the optimized libraries is yet

**Comment by dirk-thomas** [comment]
The debug libraries should be shipped along side the release libraries with a debug suffix. The CMake module should then export both of them using the proper keywords (`optimized` / `debug`). For FastRTPS we are doing something similar: https://github.com/ros2/rmw_fastrtps/blob/c0f148ee03156860492b220c66358b8af519b095/fastrtps_cmake_module/cmake/Modules/FindFastRTPS.cmake#L45-L92

**Comment by mikaelarguedas** [comment]
Yes I agree with that :+1: thanks for the pointer, I just haven't looked into it in enough details to decide if it's simpler to modify their generated INSTALL target VS solution or if we should make our own CMake logic to override their generated CMake files.

**Comment by mikaelarguedas** [comment]
Ok actually You can build their "INSTALLATION" target in both Release and Debug mode. the artifact is [here](https://github.com/ros2/ros2/releases/download/release-beta2/opencv-2.4.13.2-vc14.VS2015.zip). It has been deployed on icecube. I just launched
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=test_windows_debug&build=6)](http://ci.ros2.org/view/All/job/test_windows_debug/6) to test the new artifact. 
If it passes I'll propagate it to all windows machines for the nightlies. And update the installation instructions accordingly if all is green tomorrow

**Comment by mikaelarguedas** [comment]
All windows nodes now have the new opencv and the installation instructions have been updated accordingly on the wiki. Closing this
