### ISSUE TITLE
fix flaky lifecycle tests

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ros2#354]
top level issue tackling the failing flaky tests on linux.

Connected PRs:
 * rcl: ros2/rcl#139
 * rclcpp: ros2/rclcpp#327

CI jobs 
`ament_test_args:  --only rcl_lifecycle rclcpp_lifecycle --retest-until-fail 20 --ctest-args -LE linter -`:
[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2634)](http://ci.ros2.org/job/ci_linux/2634/)
[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2090)](http://ci.ros2.org/job/ci_osx/2090/)
[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2748)](http://ci.ros2.org/job/ci_windows/2748/)

**Comment by mikaelarguedas** [comment]
Looks like one of the tests started failing along the way: http://ci.ros2.org/job/ci_windows/2747/#showFailuresLink

**Comment by Karsten1987** [comment]
this should be fixed by now.

**Comment by Karsten1987** [comment]
I am going to merge in order to proceed with https://github.com/ros2/rclcpp/issues/329
