### ISSUE TITLE
Use CMAKE_X_STANDARD and check for compiler ID rather than platform

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#362]
- [x] ament_index: https://github.com/ament/ament_index/commit/d05f2645c77f296e291bb6aad3d83d3cd182729f
 - [x] common_interfaces: https://github.com/ros2/common_interfaces/commit/cfb32325ff9935b87765a14ef1ae0dc319265497
 - [x] demos: https://github.com/ros2/demos/commit/d127266a115bb2c169bd34821cfe175fe839dce1
 - [x] example_interfaces: https://github.com/ros2/example_interfaces/commit/9f769ea67da0d00d6659cbf74112c9dbc2e04a02
 - [x] examples: https://github.com/ros2/examples/commit/24bc602dca905313a4162e1f7bbdab5fc84a9731
 - [x] geometry2: https://github.com/ros2/geometry2/commit/c0d4f6971a64e2c8adba8cdde7ae87e402bd3b1d
 - [x] rcl: https://github.com/ros2/rcl/compare/compile_options
 - [x] rclcpp: https://github.com/ros2/rclcpp/commit/473c9244461cae9500f4df47caeb6b57d8af9c3f
 - [x] rcl_interfaces: https://github.com/ros2/rcl_interfaces/commit/6b5d60716943da7b3a0d07ad0f93d7c5dc429e5c
 - [x] realtime_support: https://github.com/ros2/realtime_support/commit/27396392e609f1c5942ea5532de892daf396259e
 - [x] rmw: https://github.com/ros2/rmw/compare/compile_options
 - [x] rmw_fastrtps: https://github.com/ros2/rmw_fastrtps/commit/98780e46238f34c857ca5abbf3c8a72409bf4577
 - [x] rmw_opensplice: https://github.com/ros2/rmw_opensplice/commit/2255e2f663eaf423d4c9412a769d7b0568faa242
 - [x] rmw_implementation: https://github.com/ros2/rmw_implementation/commit/94bb75b61a5817e8247e5db5a4e2e7d7b3df2d9f
 - [x] rmw_connext: https://github.com/ros2/rmw_connext/commit/6c692ad08b39236c0b6ff6c8b0b934fb9c126f98
 - [x] robot_model: https://github.com/ros2/robot_model/commit/7a1db8747520550db7fc142a762bd86c6b217da8
 - [x] robot_state_publisher: https://github.com/ros2/robot_state_publisher/commit/8cd758043b6285927947e69b8681c47674cefe04
 - [x] ros1_bridge: https://github.com/ros2/ros1_bridge/commit/d8cfc28770bf9af2766709c450262bb8c055c1b6
 - [x] rosidl: https://github.com/ros2/rosidl/issues/221
 - [x] rosidl_typesupport: https://github.com/ros2/rosidl_typesupport/commit/91da499ed264e54986f37e09d96b3cf405d52f79
 - [x] system_tests: https://github.com/ros2/system_tests/commit/122abd8213dffd40d98fdb0e32a0054d104954b6
 - [x] urdfdom: https://github.com/ros2/urdfdom/commit/01037f82ac0a2a594f62353c546ee371b0e0f607

tb2_demo repos:
 - [x] cartographer_ros: https://github.com/ros2/cartographer_ros/commit/823086c67c14f6b191ed9d86705c2e7e0f394eb6
 - [x] navigation: https://github.com/ros2/navigation/commit/819cb104209bf2a29f109dbfcb9d9f59f7e4f6e7
 - [x] pcl_conversions: https://github.com/ros2/pcl_conversions/commit/e0c4a9ca5833c4e4bddf7e6a0a84441da5ea2371
 - [x] ros_astra_camera: https://github.com/ros2/ros_astra_camera/commit/5774c91ee2309ae58ff33246a98297ae08e5b824
 - [x] teleop_twist_joy: https://github.com/ros2/teleop_twist_joy/commit/361f6b4f9c94328ac61dce9b7064215e91eb26e2
 - [x] turtlebot2_demo: https://github.com/ros2/turtlebot2_demo/commit/78a9c00d93cbbde819be18d7159e1031aca03d8d
- [x] vision_opencv: https://github.com/ros2/vision_opencv/commit/f6adc4735987529b2d2b1de5ba8b026d36b96690

First round of CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2753)](http://ci.ros2.org/job/ci_linux/2753/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=287)](http://ci.ros2.org/job/ci_linux-aarch64/287/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2224)](http://ci.ros2.org/job/ci_osx/2224/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2881)](http://ci.ros2.org/job/ci_windows/2881/)

* Turtlebot repo Linux  [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_turtlebot-demo_linux&build=46)](http://ci.ros2.org/job/ci_turtlebot-demo_linux/46/)
* Turtlebot repo Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_turtlebot-demo_linux-aarch64&build=67)](http://ci.ros2.org/job/ci_turtlebot-demo_linux-aarch64/67/)

**Comment by mikaelarguedas** [comment]
@ros2/team CI is green for all the packages in the ros2.repos. CI on turtlebot repos almost done
No outstanding change except migrating every repo using a "std" flag to using CMAKE_X_STANDARD. Note that you can still find `-std=??` flags in the codebase when passing flags explicitely to specific targets.
We will need https://github.com/ros2/rcutils/pull/26 and https://github.com/ros2/rcl/pull/141 to be updated to finish the migration

**Comment by dirk-thomas** [comment]
I reviewed the first block of changes and they all lgtm. I assume you will squash all changes into a single commit on the default branch? :+1:

**Comment by mikaelarguedas** [comment]
yep, seems more convenient for everybody than opening PRs for all of them

**Comment by mikaelarguedas** [comment]
:green_heart: :green_apple: :green_heart: on the :robot: repos file as well

**Comment by dirk-thomas** [comment]
The generators can set the `C_STANDARD` on the target using this: http://docs.w3cub.com/cmake~3.5/prop_tgt/c_standard/#prop_tgt:C_STANDARD

**Comment by mikaelarguedas** [comment]
Cool! I'll do that then!

**Comment by wjwwood** [comment]
Belated, but the second block looks good.

**Comment by mikaelarguedas** [comment]
:+1: thanks. I'll push those and open a PR for the rosidl one that may have a slightly different change

**Comment by mikaelarguedas** [comment]
Ok all the commits landed. Not that all fils  that were not explicitely passing astandard glag to the compiler have not been modified. This issue trackd only replacing any `-std=c??` flags with setting the appropriate CMake standard variable
