### ISSUE TITLE
Create zero initialization methods for messages

### ISSUE THREAD

**Issue by tfoote** [ros2/ros2#367]
In porting efforts we've run into several bugs where the zero initialized behavior is relied upon, causing bugs. Having a zero initialization method as a way to make porting less fragile would be valuable. And likely can be used in other cases when the optimization of using uninitialized constructors are not as important.

This is capturing the suggestion from @clalancette and @mikaelarguedas in ros2/geometry2#25

**Comment by mikaelarguedas** [comment]
This should be eligible for the "hitlist". If not implementing these method, at least warn users and reflect on the design documents that the messages are not zero-initialized by default. (e.g. [this](http://design.ros2.org/articles/generated_interfaces_cpp.html) suggests that default constructors do initialize the fields )

@Karsten1987 FYI

**Comment by dirk-thomas** [comment]
@clalancette will look into this and come up with a design doc / proposal.

**Comment by clalancette** [comment]
Closing this in favor of #393
