### ISSUE TITLE
Each package needs its own visibility control macros

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#37]
Reusing the macros from another package does not work since they will affect how symbols from recursive headers are treated.

E.g. ros2/rosidl_dds#12 was not working since it used the ROSIDL macros from the rosidl_generator_c package.

**Comment by gerkey** [comment]
This is a pattern that we expect to have to follow for every C/C++ library for every package.  So, if possible, identify shortcuts or ways to reuse code.  At the very least, we should have documentation that explains how to add this to a new package.
