### ISSUE TITLE
setup documentation for beta 2

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#370]
This is an aggregate issue to collect things that need to be done for the docs in beta 2.

- [x] move the existing docs from S3 to github pages (@nuclearsandwich's suggestion, but I agree)
- get clean documentation generation from packages which already have docs from beta 1:
  - [x] rcutils https://github.com/ros2/rcutils/pull/38 (new but in the same basket imo)
  - [x] rmw https://github.com/ros2/rmw/pull/112
  - [x] rcl https://github.com/ros2/rcl/pull/147
  - [x] rclcpp https://github.com/ros2/rclcpp/pull/341
- [ ] figure out how to run the new documentation script, but integrate the custom doxygen output from the packages listed above

I'll keep updating this as I do things.

**Comment by wjwwood** [comment]
I fixed up the docs on all the repos that I think have substantial docs. They're in review if anyone has time.

**Comment by nuclearsandwich** [comment]
We didn't end up getting any of the new documentation scripts wired up and instead built documentation manually. Docs are live at https://docs.ros2.org/beta2
