### ISSUE TITLE
ros2:command not find

### ISSUE THREAD

**Issue by Yingzhong262526** [ros2/ros2#374]
Hi:
  Everyone!When I want to learn  [the demo](https://github.com/ros2/ros2/wiki/tf2),I run 
ros2 run tf2_ros static_transform_publisher 1 2 3 0.5 0.1 -1.0 foo bar 
before I call the enviroment using 
~ ./ros2_ws/install/setup.bash
in the ubuntu 16.04 terminal ,but there is a error:
ros2:command not find
can someone help me ?

**Comment by clalancette** [comment]
What version of ROS2 are you using?  The 'ros2' command is new with the not-yet-released beta2; you'll need to track master to get it.

**Comment by Yingzhong262526** [comment]
@clalancette: 
Thank you !I do as you,Now it can find the "ros2"command!

**Comment by dirk-thomas** [comment]
@Yingzhong262526 If the problem is solved for you can you please close the ticket. Thanks.
