### ISSUE TITLE
ros2 version alpha 6 install error

### ISSUE THREAD

**Issue by sagniknitr** [ros2/ros2#398]
## Bug report

**Required Info:**

- Operating System:
  - <Ubuntu 14.04 -->
- Installation type:
  - <source  -->
- Version:
  - <alpha 6>

#### Steps to reproduce issue

ROS2 installation procedure

Build the prototype using the bootstrap script from ament_tools

Note: to build the ROS 1 bridge, read the ros1_bridge instructions.

More info on working with an ament workspace can be found in this tutorial.

cd ~/ros2_ws/
**src/ament/ament_tools/scripts/ament.py build --build-tests --symlink-install** < error occurs in this command
![screenshot from 2017-09-11 17 53 08](https://user-images.githubusercontent.com/17951883/30274326-96acf6f8-971a-11e7-9508-7db0626d3fb2.png)

**Comment by allenh1** [comment]
Have you tried with Beta 2? Alpha 6 was quite a while ago.

**Comment by wjwwood** [comment]
As @allenh1 said, alpha6 is old, and we're not going to be supporting them. Please try the latest release.

Also, please do not post pictures of text. We cannot search, copy&paste, or comment on a picture of text.
