### ISSUE TITLE
Basic multiprocess launcher with test awareness

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#4]
AC:

- [x] use Python `asyncio`
  - [x] file format for encoding processes to be launched (plain python fine)
  - [x] output to different destinations: console, log file
- [x] support multiple error handlers
  - [x] ability to launch and tear down processes (local only)
  - [x] a way designate tests in the file format
- [x] separate launcher executable (`launch`) from launch file containing the process information
  - [x] identify launch files by full path
- [x] support nesting launch files
- [x] example with multiple tests in a single file
  - [x] module level setup / teardown with async launcher
  - [x] test function running launcher and adding coroutine for the test
- [x] ability to integrate with ament
- ~~collect test results (or pass in test results directory)~~ I don't think the launcher needs to know about it

The following bullets should be separated into a new ticket since they require external functionally to exist before they can be implemented:

- [ ] launch API: locate launch files in `share/pkgname/launch`
- [ ] launch executable: identify launch file by package name and launch file name

Future features after clarifying API needs:
- [ ] support registering global callbacks

**Comment by dirk-thomas** [comment]
Example test provided in ros2/examples#7.
