### ISSUE TITLE
Audit build caching

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#40]
It seems that repeat builds of the ROS 2 stack with `ament build` will result in rebuilding or even regenerating code in parts of the system.

See: https://github.com/ament/ament_tools/pull/32#issuecomment-93581112

**Comment by dirk-thomas** [comment]
The first item to address is that templated message files are always overwritten. The above four PRs change that so that the generated files are only overwritten when their content actually changes. Otherwise they are not touched.

**Comment by dirk-thomas** [comment]
I can't find any unnecessary operations in the log of a repeated build anymore.

@esteve @tfoote @wjwwood Please run a repeated build (with the above PRs checked out / merged) and review the build log. Then either confirm that this can be closed or comment with specific parts from the build log which should be skipped.

**Comment by tfoote** [comment]
These individually looks reasonable. However there's a lot of repeated code snippets for the write file if changed which would be much better to consolidate into a function. (11 instances)

**Comment by dirk-thomas** [comment]
@tfoote I agree that refactoring the functionality would be desired but consider that for a separate PR.

**Comment by tfoote** [comment]
separate is fine by me ticketed: #44 to not forget.

**Comment by dirk-thomas** [comment]
Closing for now.
