### ISSUE TITLE
store node name in participant user_data

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#438]
Currently the rmw impl. of Connext and FastRPTS set the RTPS participant name to the node name. But this is an extension to the DDS spec. OpenSplice does not provide to set this and instead places the node name into the `user_data` of the participant. Each approach on its own works but is not compatible with each other.

Therefore the idea is to populate the `user_data` in Connext and FastRTPS to achieve cross vendor compatibility.

**Comment by dirk-thomas** [comment]
All referenced PR are ready for review now.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3884)](http://ci.ros2.org/job/ci_linux/3884/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1003)](http://ci.ros2.org/job/ci_linux-aarch64/1003/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3210)](http://ci.ros2.org/job/ci_osx/3210/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3976)](http://ci.ros2.org/job/ci_windows/3976/)

**Comment by dirk-thomas** [comment]
And with `test_get_node_names__rmw_fastrtps_cpp` fixed (the node needs to add itself to the list of "discovered" node names...):

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3886)](http://ci.ros2.org/job/ci_linux/3886/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1005)](http://ci.ros2.org/job/ci_linux-aarch64/1005/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3212)](http://ci.ros2.org/job/ci_osx/3212/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3978)](http://ci.ros2.org/job/ci_windows/3978/)

**Comment by richiware** [comment]
Commit bfb448e19bff253293e8f28ee8c3d3d78d882be2 should resolve the failing tests of FastRTPS

**Comment by dirk-thomas** [comment]
@richiprosima was able to address the problem serializing the `userData` in FastRTPS: https://github.com/eProsima/Fast-RTPS/commit/bfb448e19bff253293e8f28ee8c3d3d78d882be2

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3914)](http://ci.ros2.org/job/ci_linux/3914/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1033)](http://ci.ros2.org/job/ci_linux-aarch64/1033/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3238)](http://ci.ros2.org/job/ci_osx/3238/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4009)](http://ci.ros2.org/job/ci_windows/4009/)

**Comment by dirk-thomas** [comment]
Waiting for feedback from @richiprosima about the communication problems between FastRTPS and OpenSplice when using `userData`. OpenSplice is rejecting the data coming from FastRTPS:

```
Report      : WARNING
Description : plist(vendor 1.15): parameter length 37 mod 4 != 0
Thread      : dq.builtins 7f0896a1f700
Internals   : 6.7.170523OSS///ddsi2/q_plist.c/2477/0/1517388334.601583782/108
```

**Comment by richiware** [comment]
I've pushed a possible solution in branch [hotfix/2538](https://github.com/eProsima/Fast-RTPS/tree/hotfix/2538). Can you test it against Opensplice?

**Comment by dirk-thomas** [comment]
@richiware Thank you for the patch. It looks like it made it work on OS X: http://ci.ros2.org/job/ci_osx/3280/ I will run CI for all platform once we have more unit tests on this but I am confident the patch is valid across platforms.

**Comment by richiware** [comment]
@dirk-thomas  Did it work in all platforms?

**Comment by dirk-thomas** [comment]
> Did it work in all platforms?

Yes, it did:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3955)](http://ci.ros2.org/job/ci_linux/3955/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1074)](http://ci.ros2.org/job/ci_linux-aarch64/1074/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3289)](http://ci.ros2.org/job/ci_osx/3289/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4057)](http://ci.ros2.org/job/ci_windows/4057/)

**Comment by mikaelarguedas** [comment]
this will break wire compatibility so I'm marking it as targeted for Bouncy so that we make a decision (and merge the implementation?) by the next release

**Comment by dirk-thomas** [comment]
I don't think we should delay the decision and/or the merging if this patch. Please bring up any concerns why this should not be done or if there is anything which should be changed. Otherwise please review it as-is to merge the change afterwards.

**Comment by mikaelarguedas** [comment]
My recollection is that we didn't settle on it. If it's the case and is ready for review, please label it as "in review"

**Comment by dhood** [comment]
we were waiting on tests as I remember for why it's back in progress

**Comment by dirk-thomas** [comment]
I am looking for feedback / review on the proposed changes now even though tests need to be added before the changed can be merged.

I just want to avoid late feedback on the actual idea how to store the node name.

**Comment by dirk-thomas** [comment]
A set of builds only running the tests of `test_rclcpp` but incl. OpenSplice:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4159)](http://ci.ros2.org/job/ci_linux/4159/) (see "test_node_name" in e.g. https://ci.ros2.org/job/ci_linux/4159/testReport/test_rclcpp.build.test_rclcpp/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1240)](http://ci.ros2.org/job/ci_linux-aarch64/1240/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3451)](http://ci.ros2.org/job/ci_osx/3451/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4265)](http://ci.ros2.org/job/ci_windows/4265/)

A set of builds running all tests with FastRTPS and Connext:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4160)](http://ci.ros2.org/job/ci_linux/4160/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1241)](http://ci.ros2.org/job/ci_linux-aarch64/1241/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3452)](http://ci.ros2.org/job/ci_osx/3452/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4265)](http://ci.ros2.org/job/ci_windows/4265/)

Ready for review - specifically the newly referenced PR with the test.
