### ISSUE TITLE
removed note about ASIO not found on macOS

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#443]
@0wu I removed the note you added about turning on building of dependencies within fast-rtps when asio is not found on macOS:

https://github.com/ros2/ros2/wiki/OSX-Development-Setup/_compare/2af42dc2bde5bb6b700683c9435c7fadd55616d6...a8369e7f20d5bb4e361be66de51e7107c8bdcbbe

That should be covered by installing asio from Homebrew. If that's not working then it's likely a bug in the asio installed by Homebrew or in Fast-RTPS's build. Can you confirm that asio is installed by homebrew and linked?

**Comment by mikaelarguedas** [comment]
@0wu I'm going to close this due to inactivity, please feel free to comment here if you still face the issue and we can reopen it
