### ISSUE TITLE
Cloning wiki, adding/modifying content locally and pushing changes

### ISSUE THREAD

**Issue by fkromer** [ros2/ros2#446]
How can one get permission to be able to push additions/changes to the wiki (cloned via `git clone https://github.com/ros2/ros2.wiki.git`)?

**Comment by wjwwood** [comment]
@fkromer You have to have write permissions on the repository. Why do you need to do it with a checkout and not through the web interface?

**Comment by fkromer** [comment]
@wjwwood I would like to add .png diagrams (cannot be hyper linked). As far as I know it is not possible to add files to the wiki repository over the web interface.

**Comment by wjwwood** [comment]
You can add images to the wiki which are hosted elsewhere. Why can it not be hyperlinked?

**Comment by wjwwood** [comment]
I suppose I could make you a contributor on this repository to let you do that, but I need to check with the team before I do that. Just trying to figure out if there is a work around for now.

**Comment by fkromer** [comment]
If it is not straightforward to grant permissions it's fine to hyper link images from else where as well. I just wanted to avoid that additional burden w.r.t. work flow.

**Comment by wjwwood** [comment]
Unfortunately it doesn't allow us to control access at that level of granularity. I think we would prefer to keep the people with write access in the organization low, but we could add you, at least temporarily, to just this repository. @ros2/team what do you think?

It's too bad that GitHub neither let's you push to the wiki's git repo (despite being allowed to create/modify things via the web interface) nor does it let us grant you that permission separately from write access to the repository itself.  @nuclearsandwich is that all correct or are we missing something?

**Comment by nuclearsandwich** [comment]
> It's too bad that GitHub neither let's you push to the wiki's git repo (despite being allowed to create/modify things via the web interface) nor does it let us grant you that permission separately from write access to the repository itself. @nuclearsandwich is that all correct or are we missing something?

That jives with my understanding as well. To add images to wikis, I usually upload them to an issue comment, copy the url then never submit the comment 😈

**Comment by fkromer** [comment]
If it is not straightforward to grant permissions it's fine to hyper link images from else where as well. I just wanted to avoid that additional burden w.r.t. work flow.

**Comment by Karsten1987** [comment]
I've used imgur in the past to upload the pictures and then hyperlink them into the tutorials. Worked pretty well for me.

**Comment by wjwwood** [comment]
It sounds like there is a decent workaround (it's what we do) to use imgur or ~~abuse~~ use GitHub's comment image hosting and linking to that.

I'll close this for now, if it becomes an extreme burden, let us know and I can reopen this.
