### ISSUE TITLE
can autoware support ros2? or how ?

### ISSUE THREAD

**Issue by xu48169172** [ros2/ros2#448]
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by sloretz** [comment]
Hi @xu48169172 , I think a question about what Autoware supports is more likely to be answered correctly if asked on the [CPFL/Autoware repository](https://github.com/CPFL/Autoware).
