### ISSUE TITLE
Create an REP 3 like document for ROS 2 releases

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#459]
This could be either an REP in the existing `rep` repo, a design doc on `design.ros2.org` or a ROS 2 wiki page.

**Comment by mikaelarguedas** [comment]
PR here ready for review: https://github.com/ros-infrastructure/rep/pull/169

**Comment by mikaelarguedas** [comment]
ros-infrastructure/rep#169 has merged
