### ISSUE TITLE
ros2-package-ardent-release-opensplice-AMD64.zip release file from 02-09 is not a valid .zip file

### ISSUE THREAD

**Issue by Ipiano** [ros2/ros2#467]
## Bug report
When installing ROS2 on windows, I downloaded the ros2-package-ardent-release-opensplice-AMD64.zip archive released on 02-09, but was unable to unzip it completely or open it in windows explorer. I tried to use both the builtin windows zip utility and 7zip for windows.

**Required Info:**

- Operating System:
Windows 10

- Installation type:
Binaries

- Version or commit hash:
d1e484d
ROS 2 Ardent Apalone - 2018-02-09

- DDS implementation:
OpenSplice

- Client library (if applicable):
N/A

#### Steps to reproduce issue
Go to https://github.com/ros2/ros2/releases/tag/release-ardent-20180209
Download ros2-ardent-package-windows-opensplice-AMD64.zip
Attempt to unzip or open the archive with windows zip utility or 7zip

#### Expected behavior
Archive can be opened/unzipped fully

#### Actual behavior
Windows zip utility returns error 
"Cannot open file
[path\to\zip] is invalid"

7zip unzips partially, and fails with errors
"Unexpected end of data"
"CRC Failed: ros2-windows/bin/opengl32sw.dll"

**Comment by nuclearsandwich** [comment]
Thanks for the report. It does look like there was an issue with the archive (it was incomplete). I downloaded it again from our packaging host and re-uploaded it. Please check that it works now and re-open the issue if it doesn't.
