### ISSUE TITLE
Problem in the dynamic link library C:\dev\ros2\fastrtps-1.5.dll

### ISSUE THREAD

**Issue by cosmicog** [ros2/ros2#497]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - Binaries
- Version or commit hash:
  - ROS 2 Ardent Apalone - 2018-03-07, `ros2-ardent-package-windows-fastrtps-AMD64.zip`
- DDS implementation:
  - Fast-RTPS (I think so, also I have OpenSplice installed and `OSPL_HOME` is set)
- Client library (if applicable):
  - `rclcpp`

#### Steps to reproduce issue
I had Visual Studio 2017 and latest Visual C++ Installed, so I skipped installing 2015 for seeing the issues and trying later. Other steps were same here [installing-prerequisites](https://github.com/ros2/ros2/wiki/Windows-Install-Binary#installing-prerequisites) except I had OpenSplice installed and `OSPL_HOME` is set. Tried by deleting this too.
Just called it from terminal for seeing the error.
```
>C:\dev\ros2\Lib\demo_nodes_cpp\talker.exe
```

#### Result

![fastrtps](https://user-images.githubusercontent.com/9158844/40756397-128fe8d6-648c-11e8-8933-72f3aa39922f.png)

**Comment by sloretz** [comment]
Text in image for people searching: `The ordinal 4689 could not be located in the dynamic link library C:\dev\ros2\bin\fastrtps-1.5.dll.`

**Comment by sloretz** [comment]
@cosmicog thanks for reporting. Would you mind checking if the same issue happens using the latest nightly? https://ci.ros2.org/view/packaging/job/packaging_windows/1021/artifact/ws/ros2-package-windows-AMD64.zip

**Comment by dirk-thomas** [comment]
Can you please try this again with the recent Bouncy release and comment if the problem still exists.

**Comment by cosmicog** [comment]
With the latest build 1057
```
The ordinal 4601 could not be located in the dynamic link library C:\dev\ros2\bin\fastrtps-1.5.dll.
```
I don't have an experience with windows libraries. Do you think it might be related only to my pc? I was thinking about fresh install. My computer can't install updates since months.

**Comment by cosmicog** [comment]
With the latest build on ci.ros.org and the release on github, it gave:
```
The ordinal 4615 could not be located in the dynamic link library C:\dev\ros2\bin\fastrtps-1.5.dll.
```
this time. Do you think the problem may related to my computer? I didn't get any updates since months. I will try on another desktop and try to give feedback today.

**Comment by cosmicog** [comment]
Finally listener heard `Hello World`s. I needed to fix hard-coded python path to `C:\Python37` , and it still gives `failed to create process` if I run `ros2` command. But this issue is resolved for me.

**Comment by dirk-thomas** [comment]
@cosmicog Since you opened the ticket you should be able to close it when it is resolved. For any other problem (`failed to create process`) please create a new ticket with enough information and context.
