### ISSUE TITLE
Setup Batch CI for OSX

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#5]
- [x] Create OSX Jenkins Slave
- [x] Setup a job to run based on the wiki instructions
 - [x] preinstall some system dependencies
 - [x] job clones and builds
- [x] Build and run tests, tracking the test results with Jenkins

----

**Comment by wjwwood** [comment]
The slave is up and running, I'm working on the job contents now and giving one more go at Connext on OS X.

**Comment by wjwwood** [comment]
Once this pull request is merged:

https://github.com/ament/ament_tools/pull/21

I can remove the line in the job which uses that branch and this should be good to close afterwards.

**Comment by wjwwood** [comment]
This is done, so I'm closing, speak up if you think there is something that is yet outstanding.

Here is the job: http://54.183.26.131:8080/job/ros2_batch_ci_osx/

**Comment by dirk-thomas** [comment]
Is the job logic stored somewhere?

**Comment by wjwwood** [comment]
I ticked it: https://github.com/ros2/ros2/issues/25
