### ISSUE TITLE
FastRTPS and OpenSplice don't talk on Empty messages 

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ros2#501]
This is a continuation of the issue described in here: https://github.com/ros2/ros2/issues/476#issuecomment-389006954

I exclude this into its own issue as the underlying PRs for removing partitions were merged.

**Comment by dirk-thomas** [comment]
I tried this locally as well as ran a set of CI builds with FastRTPS and OpenSplice for this case:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4737)](http://ci.ros2.org/job/ci_linux/4737/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1605)](http://ci.ros2.org/job/ci_linux-aarch64/1605/) unrelated test failures
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3925)](http://ci.ros2.org/job/ci_osx/3925/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4797)](http://ci.ros2.org/job/ci_windows/4797/) (specific [test](https://ci.ros2.org/job/ci_windows/4797/testReport/(root)/projectroot/test_publisher_subscriber__Empty__rclcpp__rmw_opensplice_cpp__rmw_fastrtps_cpp/))

All of them pass the specific test described in this ticket. Therefore I would assume the problem doesn't exist anymore in the current code base (or is at worst flaky). So I suggest to close this ticket until a reproducible problem can be described.

**Comment by dirk-thomas** [comment]
> Do you mean that the reproducible example linked in this issue: #476 (comment) was working for you ?

Yes.
