### ISSUE TITLE
Use Fast-RTPS 1.6.0 for Bouncy

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#506]
A release candidate to Fast-RTPS 1.6.0 has been pushed upstream.

Connects to #493 

Running ci on it to check if it plays well with the latest state of the ROS2 codebase:
### Release:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4624)](http://ci.ros2.org/job/ci_linux/4624/) (test failure unrelated)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1524)](http://ci.ros2.org/job/ci_linux-aarch64/1524/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3826)](http://ci.ros2.org/job/ci_osx/3826/) (test failure unrelated)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4702)](http://ci.ros2.org/job/ci_windows/4702/) (**New warnings from Fast-RTPS code**)

### Debug
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4625)](http://ci.ros2.org/job/ci_linux/4625/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1525)](http://ci.ros2.org/job/ci_linux-aarch64/1525/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3825)](http://ci.ros2.org/job/ci_osx/3825/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4703)](http://ci.ros2.org/job/ci_windows/4703/)  (**New warnings from Fast-RTPS code**, test failures unrelated)

### Xenial jobs
Xenial Release: Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4626)](http://ci.ros2.org/job/ci_linux/4626/) (test failure unrelated)

Xenial Debug: Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4627)](http://ci.ros2.org/job/ci_linux/4627/)

### Release:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4635)](http://ci.ros2.org/job/ci_linux/4635/) (test failure unrelated)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1533)](http://ci.ros2.org/job/ci_linux-aarch64/1533/) (test failure unrelated)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3832)](http://ci.ros2.org/job/ci_osx/3832/) (test failure unrelated)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4711)](http://ci.ros2.org/job/ci_windows/4711/) (**New warnings from Fast-RTPS code**)

### Debug
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4636)](http://ci.ros2.org/job/ci_linux/4636/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1534)](http://ci.ros2.org/job/ci_linux-aarch64/1534/) (test failure unrelated)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3824)](http://ci.ros2.org/job/ci_osx/3824/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4712)](http://ci.ros2.org/job/ci_windows/4712/)

@richiware FYI: I'll post a summary of the things that come up as a follow-up comment. The only regression CI pointed out so far are the new warnings on Windows

**Comment by mikaelarguedas** [comment]
@richiware Most failures are not related to the Fast-RTPS changes.
The only outstanding difference is the [new warnings on Windows](https://ci.ros2.org/job/ci_windows/4702/warnings43Result/new/).
Can you please let us know when this is addressed and we will retest it on CI.

Thanks!

**Comment by mikaelarguedas** [comment]
New round of CI with new Fast-RTPS 1.6.0 and Fast-CDR 1.07 (both now pushed to the master banch upstream):

## Fast-RTPS + Opensplice

### Release:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4673)](http://ci.ros2.org/job/ci_linux/4673/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1561)](http://ci.ros2.org/job/ci_linux-aarch64/1561/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3867)](http://ci.ros2.org/job/ci_osx/3867/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4748)](http://ci.ros2.org/job/ci_windows/4748/)

Debug:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4672)](http://ci.ros2.org/job/ci_linux/4672/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1560)](http://ci.ros2.org/job/ci_linux-aarch64/1560/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3866)](http://ci.ros2.org/job/ci_osx/3866/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4747)](http://ci.ros2.org/job/ci_windows/4747/)

**Comment by richiware** [comment]
@mikaelarguedas What is the status of this issue? Did you detect something in new FastRTPS release?

**Comment by mikaelarguedas** [comment]
@richiware everything is good, no issue detected in the new Fast-RTPS and Fast-CDR releases.

Thanks !
