### ISSUE TITLE
[WiKi]colcon build doesn't support --build-tests

### ISSUE THREAD

**Issue by minggangw** [ros2/ros2#513]
As the wiki has replaced `ament_tools` with `colcon`, the section of [Linux-Development-Setup](https://github.com/ros2/ros2/wiki/Linux-Development-Setup) has the following instructions about how to build ROS 2 by `colcon`

>Optionally install all packages into a combined directory (rather than each package in a separate subdirectory). On Windows due to limitations of the length of environment variables you should use this option when building workspaces with many (~ >> 100 packages).

>colcon build --build-tests --symlink-install --merge-install

It turns out that `colcon` does not have a argument of `--build-tests`.

**Comment by mikaelarguedas** [comment]
yes colcon [builds the tests by default](https://colcon.readthedocs.io/en/released/migration/ament_tools.html) and doesnt have this option. I [updated the wiki](https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/af7ac35a3478ef82c3fa4243d40aef5fa12c8ad3...87029a4095149b06ec74fb55e2f81ecd695d9585) to remove the `--build-tests` that shouldn't be there.

Thanks for reporting!

The wiki can be edited by anyone with a github account. Feel free to contribute fixes directly there.
