### ISSUE TITLE
unable to build python_d for 3.6.5 on Windows 10 with SDK version 10.0.17134.0

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#518]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10, Windows SDK 10.0.17134.0
- Installation type:
  - from source

#### Steps to reproduce issue

Follow https://github.com/ros2/ros2/wiki/Windows-Development-Setup#extra-stuff-for-debug-mode.

#### Expected behavior

Python 3.6.5 builds and produces a `python_d.exe` we can use.

#### Actual behavior

Doesn't build.

#### Additional information

The work around I listed no longer works (I think the SDK version is too new now), and so I tried the new workaround I mention in the wiki page which is to use the "Retarget Solution" option in Visual Studio, but that ends up producing an error like `Architecture not specified" as a `#error` in a core header and also fails to compile.

**Comment by mikaelarguedas** [comment]
How unconvenient...
Looking at the last [windows nightly](https://ci.ros2.org/view/nightly/job/nightly_win_deb/923) it looks like the machines have Python3.6.5 and SDK 10.0.17134.0.

Not sure when python was upgraded for the last time on these machines; from the logbook : @clalancette @nuclearsandwich  @mjcarroll maybe?

**Comment by nuclearsandwich** [comment]
I was the one who updated the buildfarm hosts to python 3.6.5 in May and rebuilt the debug install as described briefly here: https://gist.github.com/nuclearsandwich/bf0fdd305c9ecc1be45c476a5161180a#python-365-debug-build

I don't think it's been updated since then. Is it not possible to build python debug with the older SDK on current machines?

**Comment by mikaelarguedas** [comment]
Buildfarm machines are now running Python 3.7 and the debug version built flawlessly, closing
