### ISSUE TITLE
Update maintainer tags before bouncy release

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#519]
Connects to #510 

Now that we have email notifications for bin/dev jobs, all packages released in Bouncy should have maintainers updated to not send emails to original maintainers if they're not involved in the maintenance of the ROS 2 version of the package.

Actions to take:
1) Someone from the team should be listed as a maintainer and previous maintainer(s) listed as author
2) Someone from the team should be listed as a maintainer and previous maintainer(s) listed as author
3) Non Open Robotics maintainer should be removed and listed as authors

@ros2/team Please place your name in front of the package you are updating to make sure we don't collide

List of packages affected:

1) No maintainers currently at Open Robotics:

 - [x] demos/pendulum_control (https://github.com/ros2/demos/pull/263)
 - [x] demos/pendulum_msgs (https://github.com/ros2/demos/pull/263)
 - [x] rclpy/rclpy @wjwwood (https://github.com/ros2/rclpy/pull/196)
 - [x] rmw_connext/rmw_connext_shared_cpp @dirk-thomas ros2/rmw_connext@4dd79c52a5a293ff2c7589b6420c6160f064ce3e
 - [x] rmw_fastrtps/rmw_fastrtps_cpp @dirk-thomas ros2/rmw_fastrtps@c9d8d46cb60f5850ee1a407119b5d3b93c95152f
 - [x] rmw_fastrtps/fastrtps_cmake_module @dirk-thomas ros2/rmw_fastrtps@c9d8d46cb60f5850ee1a407119b5d3b93c95152f
 - [x] rosidl_typesupport_connext/rosidl_typesupport_connext_c @dirk-thomas ros2/rosidl_typesupport_connext@53de87245f2d1a8ef2bf63d4844c62e27c4337d6

2) Forked packages that we release and don't haven an open robotics maintainer:
 - [x] geometry2/tf2_eigen @nuclearsandwich https://github.com/ros2/geometry2/pull/61
 - [x] orocos_kinematics_dynamics/orocos_kdl https://github.com/ros2/orocos_kinematics_dynamics/pull/7
 - [x] urdfdom https://github.com/ros2/urdfdom/pull/12
 - [x] vision_opencv/image_geometry https://github.com/ros-perception/vision_opencv/pull/230

3) Released packages with other maintainers listed
 - [x] ros-perception/laser_geometry
 - [x] ros-planning/navigation_msgs/map_msgs

**Comment by wjwwood** [comment]
For `map_msgs` and `laser_geometry` they are aware and helping with ROS 2 maintenance.

- https://github.com/ros-planning/navigation_msgs/pull/4#issuecomment-394753011
- https://github.com/ros-perception/laser_geometry/pull/27#issuecomment-361465138

**Comment by mikaelarguedas** [comment]
All maintainers have been updated, closing...
