### ISSUE TITLE
Vendor typesupport depends on ament resources generated by vendor RMW packages

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/ros2#528]
Vendor typesupport is only built into interface packages when the corresponding vendor RMW implementations are present to provide specific ament index resources. This introduces an unintentional build time dependency on vendor RMW packages for any interface package that needs to use the vendor typesupport packages the specific mechanisms of which are [detailed in this comment](https://github.com/ros-infrastructure/bloom/pull/477#issuecomment-401193128 ).

One possible solution via [@dirk-thomas in another thread:](https://github.com/ros-infrastructure/bloom/pull/477#issuecomment-401194367)
>  Maybe a cleaner approach would be to not query the rmw impl. and derive their typesupports from them but instead just query the available typesupport directly

**Comment by dirk-thomas** [comment]
This was resolved in ros2/rosidl_typesupport#62.
