### ISSUE TITLE
Port image transport

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#531]
* Port image_transport functionality ros-perception/image_common#84
* This includes several dependencies

Please feel free to update the list with more information as needed.

Core Functionality:
- [x] Port `message_filters` to ROS2 (C++): https://github.com/ros2/message_filters/pull/5
- [x] Port `image_transport` to ROS2 (C++): https://github.com/ros-perception/image_common/pull/84
  - [x] Port `raw_image_transport`: https://github.com/ros-perception/image_common/pull/84
- [x] Port `image_transport_plugins` to ROS2:
  - [x] `compressed_depth_transport`: https://github.com/ros-perception/image_transport_plugins/pull/27
  - [x] `compressed_image_transport`: https://github.com/ros-perception/image_transport_plugins/pull/27
  - [x] `theora_image_transport`: https://github.com/ros-perception/image_transport_plugins/pull/28

Additional Functionality:
- [x] Port `message_filters` (Python): https://github.com/ros2/message_filters/pull/7
- [ ] Support dynamic reconfigure in image transport plugins
- [ ] Lazy subscribers in ROS2 (requires rmw changes)

**Comment by wjwwood** [comment]
I switched this to "in progress" since it doesn't seem to have associated pr's and is still an ongoing task (AFAIK).

**Comment by dirk-thomas** [comment]
@mjcarroll Please update this ticket with the current status.

**Comment by mjcarroll** [comment]
I think since we've implemented all of the "core" features, we can close this and transfer any of the remaining enhancements as issues on the `image_common` repository.
