### ISSUE TITLE
rosbag

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#533]
- [ ] Finish up design document draft: https://github.com/ros2/design/pull/160
- [x] Python CLI: https://github.com/ros2/rosbag2/issues/2
- [x] rosbag API: https://github.com/ros2/rosbag2/issues/3
- [x] rosbag storage API:  https://github.com/ros2/rosbag2/issues/4

More subtasks to come when design doc is merged.

**Comment by dirk-thomas** [comment]
@Karsten1987 Can this be closed?

**Comment by Karsten1987** [comment]
the design doc is still not merged, but I am okay to close this.
