### ISSUE TITLE
ROS 2 package index

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#534]
* Browse / search through metadata of ROS 2 packages (similar to http://rosindex.github.io)

Please feel free to update the list with more information as needed.

**Comment by tfoote** [comment]
Ongoing PRs: https://github.com/ros2/rosindex/pull/8 https://github.com/ros2/rosindex/pull/7 https://github.com/ros2/rosindex/pull/6

**Comment by tfoote** [comment]
Testing site up at: https://ros-infrastructure.github.io/index.ros.org/
