### ISSUE TITLE
`ros1_bridge` not included in Bouncy release on Windows

### ISSUE THREAD

**Issue by calvertdw** [ros2/ros2#547]
## Bug report

From https://github.com/ros2/ros1_bridge/blob/master/README.md:

> The bridge provided with the prebuilt ROS 2 binaries includes support for common ROS interfaces (messages/services), such as the interface packages listed in the ros2/common_interfaces repository and tf2_msgs.

- Operating System:
  - Windows 10 build 1803
- Installation type:
  - binary
- Version or commit hash:
  - bouncy
- DDS implementation:
  - all 3 installed

#### Steps to reproduce issue
```
λ local_setup.bat
λ ros2 run ros1_bridge dynamic_bridge -- --help
Package 'ros1_bridge' not found
```

#### Additional information

Rviz 2 launches fine, so it seems my install is good.

**Comment by gavanderhoorn** [comment]
Afaik the bridge is not included as it needs a proper ROS1 installation to be present, and that is not possible on Windows.

**Comment by calvertdw** [comment]
Haha of course 😅
