### ISSUE TITLE
reverting wiki change to macOS binary installation instructions

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#549]
@routiful FYI

I reverted this because these libraries and tools you added to the pip install should not be required to run things from the binary.

I guess you meant to be able to build things on top of the binary (or ran into some other issue), but that is covered in the "development setup" for macOS:

https://github.com/ros2/ros2/wiki/OSX-Development-Setup

Let me know if you think your changes should be put back for some other reason.

Thanks!

**Comment by routiful** [comment]
Oops, I didn't know that. Thanks :)
