### ISSUE TITLE
7zip unzip for ROS 2 bouncy patch 1 works fine

### ISSUE THREAD

**Issue by calvertdw** [ros2/ros2#551]
From https://github.com/ros2/ros2/wiki/Windows-Install-Binary:

> Note: There seems to be an issue where extracting the zip file with 7zip causes RViz to crash on startup. Extract the zip file using the Windows explorer to prevent this.

I cannot find the original issue, but as of right now, with latest 7zip I can launch rviz2 fine. Can we remove the disclaimer?

- Operating System:
  - Windows 10 1803
- Installation type:
  - zip
- Version or commit hash:
  - bouncy patch 1
- DDS implementation:
  - all

**Comment by sloretz** [comment]
Thanks for testing @calvertdw !

@greimela-si do you remember if there an issue somewhere with more info about the crash when extracting with 7zip?

**Comment by greimela-si** [comment]
@sloretz Yes, we tracked the issue over at rviz: https://github.com/ros2/rviz/issues/208.
And another issue regarding this crash has been created at the ci repo: https://github.com/ros2/ci/issues/126

**Comment by calvertdw** [comment]
I guess removing that doc goes on this list of things to do when ardent support is dropped.

**Comment by calvertdw** [comment]
I added the clause "ardent and earlier" to the Wiki. https://github.com/ros2/ros2/wiki/Windows-Install-Binary/f6a452d914d30ada2019a0d9dcc04aa2757c4b83

**Comment by mikaelarguedas** [comment]
thanks :+1:
