### ISSUE TITLE
Wiki update suggestion 

### ISSUE THREAD

**Issue by billchenxi** [ros2/ros2#555]
#### Feature description

First of all, thank you! 

Since ROS2 is still kind in the phase of development, so a lot of users might want to install ROS2 and ROS1 parallel on the computer.

**Comment by sloretz** [comment]
Hi @billchenxi , I'm not sure if I understand. Is the suggestion to add a wiki page showing how to install ROS1 and ROS2 side by side?

**Comment by mikaelarguedas** [comment]
Thanks @billchenxi for reaching out.

ROS 1 and ROs 2 are side by side installable.

Do you have a specific change in mind to make on the wiki ?

**Comment by mikaelarguedas** [comment]
Closing due to no response.

@billchenxi feel free to comment here with more information and we can reopen
