### ISSUE TITLE
Question about wiki edit to add cmake dependency at beginning of instructions

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/ros2#566]
@filiperinaldi I see that you edited the ros2 installation instructions at https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/6fcc79c4ade3119dc6b1bebb51ec4f0cdb434c86...32ae0a4138e2a1898133ec3a147f62f7f45c17d7

CMake like other dependencies is being installed when invoking `rosdep install` at https://github.com/ros2/ros2/wiki/Linux-Development-Setup#install-dependencies-using-rosdep.

Can you clarify in what context you needed cmake to be listed explicitly before that ?

**Comment by clalancette** [comment]
This has been open quite a long time and no response, so I'm going to close this out.
