### ISSUE TITLE
[demo] ROS 2 baremetal embedded

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#57]
The purpose of the demo is to show ROS 2.0 being used to communicate to/from a mainstream "modern" microcontroller. 

Goals:

- [x] Pub data from MC (e.g., a sensor of some sort)
- [x] Sub to teleop from PC to MC (e.g., make a LED blink or a servo move)

Demonstration setup:

- [x] setup 1: a STM32 running bare-metal
- [ ] setup 2: a STM32 running NuttX or some other RTOS

Required capabilities

- [x] run some RTPS on a microcontroller
- [ ] a way to hook said RTPS into rmw

**Comment by gerkey** [comment]
Plan is to support the rmw API on top of freertps, to allow rclcpp programs to build for the baremetal platforms.  Doing so brings extra work in terms of supplying various OS calls that rclcpp and friends need, but which aren't currently available in our setup.

Whether or not that gets done, write documentation for how to build, deploy, and run the demo.  Will support STM32f[4|7] on the discovery board.
