### ISSUE TITLE
[demo] Real-time node

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#58]
The purpose of this demo is to show that ROS 2.0 can be used in a real-time system. It will demonstrate setting up two nodes which can be run separately, but if launched locally can have realtime behavior. This will include demonstrations of non-blocking interactions with non real-time threads.

Goals:

- [ ] Node using real-time process to run a PID control loop
- [ ] Demonstrate using life cycle to control memory allocation
- [ ] Demonstrate external pub/sub does not affect real-time thread

Demonstration setup:

- [x] RT Preempt or Xenomi Linux machine
- [x] Inverted Pendulum simulator (closed form simulation, torque commands in, encode positions out)
- [x] Sensor node: get encoder data from simulator and publish
- [ ] Controller node: subscribe to sensor node, calculate desired output torque from PID, publish to motor
- [x] Motor node: subscribe to output from controller node, set torque in simulation
- [x] instrumentation of jitter using rttest (send out stream of diagnostics to non-realtime): aim for 2-3% jitter in kilohertz update loop.
- [ ] adjustable control loop frequency
- [ ] adjustable pendulum parameters (mass, length, desired angle)
- [ ] adjust interference such as random sleeps or extra pagefaults (optional)
- [ ] GUI for displaying simulator, live plotting statistics, and clickable sliders (if time permits)

Required capabilities
- [x] Ability to select a realtime thread
 - [x] preempt priority
 - [x] does not block
 - [x] does not allocate when sending or receiving messages
- [ ] realtime safe intra-process pub/sub
  - [x] check if the DDS implementations will fulfill our requirements
- [ ] parameter API
- [x] implement a real-time safe executor for rclcpp (if for some reason that doesn't work, consider a separate rclc, or separate rclcpp_rt, or different modifications / extensions to rclcpp)

**Comment by jacquelinekay** [comment]
do we need to implement an "rcl_realtime" library for this demo, or patch `rclcpp` to be realtime-safe, or implement `rclc` to be realtime-safe?

similar question for `rmw`

**Comment by wjwwood** [comment]
Ideally we'd have one library this is capable of both, with either no changes or only configuration changes to achieve real-time. However, if that's not possible then we'll have to consider what our options are. If we have to provide an entirely separate library for real-time, then it's hard to say how that's better than just having good integration with something like OROCOS.

**Comment by jacquelinekay** [comment]
Cool. From what I've learned today, I think it's reasonable to have one library which can be configured for realtime-safe behavior. [This example for RT Preempt](https://rt.wiki.kernel.org/index.php/Threaded_RT-application_with_memory_locking_and_stack_handling_example) shows how to preallocate the stack and lock the memory for a process so that starting new threads and dynamic memory allocation will not result in pagefaults. After that, the challenge is figuring out how much memory to preallocate.

Not sure how many platforms this solution will work on, but I think it will work fine for the demo...
