### ISSUE TITLE
wiki change: rviz dependencies

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#580]
@lbegani I reverted this change:

https://github.com/ros2/ros2/wiki/Linux-Development-Setup/_compare/4a1d315337cb05cd12640860d4557efcfa593e24

Because that should be covered by `rosdep` in this section:

https://github.com/ros2/ros2/wiki/Linux-Development-Setup#install-dependencies-using-rosdep

If you think that's not sufficient, then we likely need to add something to the `package.xml` in one of the rviz packages.

**Comment by lbegani** [comment]
Thanks @wjwwood . Should I update `rosdep` section? I am not sure about the right place, got the error during compilation of ros2 on ubuntu16.04 . The error should be reproducible by following setup steps on a clean ubuntu16.04.
