### ISSUE TITLE
ROS2 Performance Testing

### ISSUE THREAD

**Issue by mjcarroll** [ros2/ros2#582]
Create a suite of performance tests for ROS2 as well as integrate performance testing into continuous integration or nightly testing.

- [x] Write performance tests
  - [ ] Interprocess (multiple rmw implementations)
  - [ ] Intraprocess/Composition
  - [ ] Ping-pong
  - [ ] Burst
- [ ] Identify a couple of EC2 instance types to test on
- [ ] Establish performance benchmarks on those instance types
- [x] Integrate performance test results into Jenkins (ros2/performance_test#2)

**Comment by dirk-thomas** [comment]
It would be good to also test the performance of the intra process comm (C++ only).

**Comment by chapulina** [comment]
Not sure if there are still plans to create a new performance test suite, but we've been working into integrating https://github.com/ApexAI/performance_test/ into the ROS2 buildfarm. @cottsay has been leading that effort.

Here's the current implementation: http://build.ros2.org/view/Eci/job/Eci__nightly-performance_ubuntu_bionic_amd64/

It's a work in progress and feedback is appreciated.

**Comment by rotu** [comment]
@chapulina, @cottsay, cc: @joespeed What happened to the implementation on the ros2 build server?

**Comment by chapulina** [comment]
The performance tests were put behind an authentication wall while they're being worked on. We want to prevent users from looking at the unfinished tests and taking the wrong conclusions. See this issue: https://github.com/ros2/buildfarm_perf_tests/issues/21

**Comment by mjcarroll** [comment]
This issue has largely been covered and there are now nightly performance tests: 

Eloquent Nightly Performance: http://build.ros2.org/view/Eci/job/Eci__nightly-performance_ubuntu_bionic_amd64/plot/
Foxy Nightly Performance: http://build.ros2.org/view/Fci/job/Fci__nightly-performance_ubuntu_focal_amd64/plot/

I'm going to close this in favor of tracking enhancements here: https://github.com/ros2/buildfarm_perf_tests
