### ISSUE TITLE
Improve MISRA Compliance

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#591]
- Add job on ci.ros2.org (or possibly build.ros2.org) to run PCLint over select packages to check for MISRA (and other static checker) violations on demand
- Write guide for how to document and suppress known violations (things we won't fix but will notify potential MISRA users about)
- Redo the audit of violations for core C packages:
  - `rcutils`
  - `rmw`
  - `rosidl`
  - `rcl`
- Audit core C++ packages:
  - `rclcpp`

**Comment by clalancette** [comment]
I don't think we are going to work on this, so I'm going to close this out.  Feel free to reopen if you think otherwise.
