### ISSUE TITLE
Setup Batch CI for Windows

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#6]
AC:

- [x] Create Windowns Jenkins Slave
- [x] Setup a job to run William's wiki instructions
 - [x] preinstall system dependencies
 - [x] job clones and builds

----

Loop in @j-rivero

**Comment by tfoote** [comment]
Current test environment Windows 8.1 Visual Studion 2013

**Comment by tfoote** [comment]
It looks like we might be better off trying out appveyor. I'm experimenting here: https://ci.appveyor.com/project/tfoote/ros2-batch-ci

**Comment by tfoote** [comment]
Notes on setting up the slave: https://gist.github.com/tfoote/caaa9a5c31246ec5a06a

Job running on windows: http://54.183.26.131:8080/job/ros2_batch_ci_windows/

It's using the windows branch of ros2/examples ros2.repos and pulling the outstanding windows branches.

**Comment by tfoote** [comment]
There's one outstanding issue blocking building on windows: https://github.com/ros2/rosidl/issues/8

**Comment by dirk-thomas** [comment]
I think this should be reopened because the current job is neither building nor running any tests yet.

**Comment by wjwwood** [comment]
That probably should have been in the AC,  I guess it needs to do the same collecting and reporting with Jenkins like the Linux batch job.

**Comment by wjwwood** [comment]
@tfoote Make sure to update `setuptools`, otherwise the scripts for things like `ament_copyright` won't get installed.

**Comment by tfoote** [comment]
Created #24 to capture this

**Comment by wjwwood** [comment]
Actually, they're still not getting installed. I'll look at it with @dirk-thomas tomorrow.

**Comment by dirk-thomas** [comment]
The windows slave lacks `flake8`: search for `ImportError` in http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_windows/84/consoleFull

**Comment by wjwwood** [comment]
I installed flake8, added a note to the internal wiki, and updated the configuration so that it should (hopefully) ignore the return code of the last two commands and mark it unstable.
