### ISSUE TITLE
Determine if DDS can do pub/sub within a process in real time

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#62]
Both research and test it.

osrf/ros_dds#26
osrf/ros_dds#27
osrf/ros_dds#28

**Comment by wjwwood** [comment]
Both research and test it.

**Comment by tfoote** [comment]
We want to know if we can build realtime safe ROS intraprocess communications on top of DDS message passing. (It may depend on DDS implementation)

**Comment by jacquelinekay** [comment]
- [x] Complete simple intra-process pub/sub over example (https://github.com/osrf/ros_dds/blob/large_message_rt/realtime/dds_intraproc.cpp)
- [ ] complete instrumentation of example and show plots with results verifying real-time performance (or not)

**Comment by jacquelinekay** [comment]
test library:
https://github.com/jacquelinekay/rttest/pull/1

examples:
https://github.com/osrf/ros_dds/pull/27
https://github.com/osrf/ros_dds/pull/26
https://github.com/osrf/ros_dds/pull/28
