### ISSUE TITLE
Is ROS2 using sdf as the robot default description language?

### ISSUE THREAD

**Issue by zapplelove** [ros2/ros2#634]
My Robot is an Parallel Robot, so I can't use urdf to describe the robot and can't use ros_control pack.

**Comment by dirk-thomas** [comment]
There is no difference in ROS 2 and ROS 1 regarding the robot description format. The coexistence of URDF and SDF has been a long standing issue in ROS.

Since this is not related to ROS 2 but ROS in general I will go ahead and close this ticket.
