### ISSUE TITLE
Implement ROS 2 Graph API

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#64]

**Comment by wjwwood** [comment]
@dirk-thomas can this be closed? Originally I think it was meant to be used as a prerequisite of ros2/ros1_bridge#3, but since we did at least what was required for that I think we might need to close this. Obviously it isn't "done" but I think our normal, high level planning (alpha roadmaps) will capture the task better than this issue.

**Comment by dirk-thomas** [comment]
Sounds good to me.
