### ISSUE TITLE
ROS2 crystal could not find convertPointCloudToPointCloud2() method in sensor_msgs package.

### ISSUE THREAD

**Issue by vandanamandlik** [ros2/ros2#641]
- Operating System:  Ubuntu 18.04
- I am working on laser_assembler porting to ROS2 in that convertPointCloudToPointCloud2() method is used but its missing in ROS2.

**Comment by mjcarroll** [comment]
@vandanamandlik I'm going to close this issue here, because I have opened an issue on the relevant repository.  I believe that this should be a good first issue/PR, as it follows a process that we've used on a few other similar files.

https://github.com/ros2/common_interfaces/issues/66

**Comment by vandanamandlik** [comment]
OK
