### ISSUE TITLE
VCS tool is unreliable, consider repo

### ISSUE THREAD

**Issue by ThyMYthOS** [ros2/ros2#642]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - Source
- Version or commit hash:
  - Clemmys
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue

Probably cannot be reproduced reliably:
```
> vcs import src < ros2.repos
...
=== src\eProsima/Fast-CDR (git) ===
Could not determine remotes: fatal: not a git repository (or any of the parent directories): .git
...

```

#### Expected behavior

All repositories are cloned and checked out to the right version. If a failure occurs the command fails and a error summary is output at the end.

#### Actual behavior

Some repositories are not cloned (e.g. observed for FastCDR). The error can only be detected by scrolling through hundrets of lines of output.

----
## Feature request

Please consider using [repo](https://source.android.com/setup/develop) instead. It is used for the same purpose as `vcs` for Android and therefor the tool is much more mature.

**Comment by dirk-thomas** [comment]
Please post now information, what version of `vcs` you are using, how frequently you are seeing the problem, etc.

> Please consider using repo instead. It is used for the same purpose as `vcs` for Android ...

First of all `vcs` is not limited to `git` so it doesn't seem that `repo` covers the same feature set but only a subset. So it isn't an adequate replacement for all the use cases (as far as I can tell from briefly looking at the docs of `repo`).

> It is used for the same purpose as `vcs` for Android and therefor the tool is much more mature.

I don't follow the rational why the usage in Android would imply any less or more maturity especially with the combination of reporting this issue for Windows.

**Comment by dirk-thomas** [comment]
I will go ahead and close this ticket since this is not something which seems feasible (see my previous comment).
