### ISSUE TITLE
Create a simple ROS 1/2 bridge

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#65]
Just a single type and topic to demonstrate feasibility.

**Comment by dirk-thomas** [comment]
I have created a new repository for the ROS 1 bridge: https://github.com/ros2/ros1_bridge

The current prototype provides unidirectional communication of a single specific topic between the ROS versions. The repo contains a README with instructions how to build this "dual-homed" package and how to run the bridge as well as the talker and listener endpoints.

**Comment by wjwwood** [comment]
This is in the review column, are we supposed to be reviewing this for completion? +1 if that's the case.
