### ISSUE TITLE
ROS2 build fails on Mac onqt_gui_cpp

### ISSUE THREAD

**Issue by maximosipov** [ros2/ros2#650]
## Bug report

**Required Info:**

- Operating System:
  - Mac OS X Mojave 10.14.2
- Installation type:
  - Build from source
- Version or commit hash:
  - latest repos
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
```
colcon build --symlink-install --packages-select qt_gui_cpp
```

#### Expected behavior
Successful build

#### Actual behavior
```
Starting >>> qt_gui_cpp
--- stderr: qt_gui_cpp                             
sip: Usage: sip [-h] [-V] [-a file] [-b file] [-B tag] [-c dir] [-d file] [-D] [-e] [-f] [-g] [-I dir] [-j #] [-k] [-m file] [-o] [-p module] [-P] [-r] [-s suffix] [-t tag] [-w] [-x feature] [-X id:file] [-y file] [-z file] [@file] [file]
Traceback (most recent call last):
  File "/Users/maxim/Projects/robots/ros2/install/python_qt_binding/share/python_qt_binding/cmake/sip_configure.py", line 109, in <module>
    subprocess.check_call(cmd)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/Cellar/sip/4.19.8_8/bin/sip', '-c', '/Users/maxim/Projects/robots/ros2/build/qt_gui_cpp/sip/qt_gui_cpp_sip', '-b', '/Users/maxim/Projects/robots/ros2/build/qt_gui_cpp/sip/qt_gui_cpp_sip/pyqtscripting.sbf', '-I', '/usr/local/share/sip/PyQt5', '-w', '-n', 'PyQt5.sip', '-t', 'WS_MACX', '-t', 'Qt_5_11_2', 'qt_gui_cpp.sip']' returned non-zero exit status 1.
make[2]: *** [sip/qt_gui_cpp_sip/Makefile] Error 1
make[1]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< qt_gui_cpp	[ Exited with code 2 ]

Summary: 0 packages finished [3.44s]
  1 package failed: qt_gui_cpp
  1 package had stderr output: qt_gui_cpp
The file /Users/maxim/Projects/robots/ros2/None does not exist.
```

#### Additional information

```
sip -V
4.19.8
```

**Comment by maximosipov** [comment]
It looks like the build fails because of -n option and old sip version provided by brew:
```
-n <NAME>
New in version 4.19.9.
```

**Comment by dirk-thomas** [comment]
The CI system (e.g. https://ci.ros2.org/view/nightly/job/nightly_osx_debug/1140/consoleFull) uses the same `sip` version: 4.19.8 and the build passes there. So the difference might be somewhere else.

@mlautman @brawner Any idea what might be causing this?

**Comment by brawner** [comment]
It's difficult to tell what the issue is because the actual error of the sip command was swallowed. This error comes from the file ```sip_configure.py``` which uses subprocess to call sip. You can see the command it tries to call. So it might just be good to try running the following command directly from the terminal to see what the issue is.


```
cd /Users/maxim/Projects/robots/ros2/qt_gui_core/qt_gui_cpp/src/qt_gui_cpp_sip

/usr/local/Cellar/sip/4.19.8_8/bin/sip -c /Users/maxim/Projects/robots/ros2/build/qt_gui_cpp/sip/qt_gui_cpp_sip -b /Users/maxim/Projects/robots/ros2/build/qt_gui_cpp/sip/qt_gui_cpp_sip/pyqtscripting.sbf -I /usr/local/share/sip/PyQt5 -w -n PyQt5.sip -t WS_MACX -t Qt_5_11_2 qt_gui_cpp.sip
```

**Comment by maximosipov** [comment]
The output as follows:
```
~/Projects/robots/ros2/src/ros-visualization/qt_gui_core/qt_gui_cpp/src/qt_gui_cpp_sip$ /usr/local/Cellar/sip/4.19.8_8/bin/sip -c /Users/maxim/Projects/robots/ros2/build/qt_gui_cpp/sip/qt_gui_cpp_sip -b /Users/maxim/Projects/robots/ros2/build/qt_gui_cpp/sip/qt_gui_cpp_sip/pyqtscripting.sbf -I /usr/local/share/sip/PyQt5 -w -n PyQt5.sip -t WS_MACX -t Qt_5_11_2 qt_gui_cpp.sip
sip: Usage: sip [-h] [-V] [-a file] [-b file] [-B tag] [-c dir] [-d file] [-D] [-e] [-f] [-g] [-I dir] [-j #] [-k] [-m file] [-o] [-p module] [-P] [-r] [-s suffix] [-t tag] [-w] [-x feature] [-X id:file] [-y file] [-z file] [@file] [file]
```

Removing the -n command line option fixes the problem:
```
~/Projects/robots/ros2/src/ros-visualization/qt_gui_core/qt_gui_cpp/src/qt_gui_cpp_sip$ /usr/local/Cellar/sip/4.19.8_8/bin/sip -c /Users/maxim/Projects/robots/ros2/build/qt_gui_cpp/sip/qt_gui_cpp_sip -b /Users/maxim/Projects/robots/ros2/build/qt_gui_cpp/sip/qt_gui_cpp_sip/pyqtscripting.sbf -I /usr/local/share/sip/PyQt5 -w -t WS_MACX -t Qt_5_11_2 qt_gui_cpp.sip
sip: Deprecation warning: qt_gui_cpp.sip:1: %Module version number should be specified using the 'version' argument
```

**Comment by brawner** [comment]
Sorry, I guess I missed your previous comment. I have run into this issue before because the PyQt5 sip flags expect a later version. How did you install PyQt5?

https://github.com/ros-visualization/python_qt_binding/blob/8c12af6f2e377b1bc17781795abfbbac86a350ae/cmake/sip_configure.py#L55

**Comment by maximosipov** [comment]
Just using python3 -m pip install --user pyqt5. Python was installed by brew as pyenv python versions  are not supported by brew sip installation.

**Comment by brawner** [comment]
In order to build rqt, it's recommended to install both by homebrew. Sip is a dependency of Pyqt5 and has version dependencies like the one you pointed out. Remove Pyqt5 with pip and then install pyqt with homebrew.

```
brew install pyqt5
```

https://index.ros.org/doc/ros2/Tutorials/RQt-Source-Install-MacOS/

Alternatively, you can upgrade sip. I had trouble installing sip with pip because it wouldn't put the sip executable in a findable place. You can install sip by source

https://www.riverbankcomputing.com/software/sip/download

**Comment by dirk-thomas** [comment]
The mismatch between `sip` and `pyqt5` describes why the arguments generated by one aren't supported by the other. I will go ahead and close the ticket since it seems there is nothing to be done here.

Please feel free to continue commenting.
