### ISSUE TITLE
ROS2 Crash in Windows

### ISSUE THREAD

**Issue by 43970117** [ros2/ros2#652]
ROS2 crash in Windows
The crash stack:
E0129 15:00:36.606562 52528 loghelper.cpp:24] *** Aborted at 1548745236 (unix time) try "date -d @1548745236" if you are using GNU date ***
E0129 15:00:36.756268 52528 loghelper.cpp:24]     @     0x7ff939a6d4cb raise
E0129 15:00:36.757266 52528 loghelper.cpp:24]     @     0x7ff939a6e561 abort
E0129 15:00:36.757266 52528 loghelper.cpp:24]     @     0x7ff939a6dc2f terminate
E0129 15:00:36.933893 52528 loghelper.cpp:24]     @     0x7ff72b0f9117 __scrt_unhandled_exception_filter
E0129 15:00:36.935889 52528 loghelper.cpp:24]     @     0x7ff93986bcf0 UnhandledExceptionFilter
E0129 15:00:36.937893 52528 loghelper.cpp:24]     @     0x7ff93c923167 memset
E0129 15:00:36.938880 52528 loghelper.cpp:24]     @     0x7ff93c90b5e6 __C_specific_handler
E0129 15:00:36.938880 52528 loghelper.cpp:24]     @     0x7ff93c91f7dd __chkstk
E0129 15:00:36.938880 52528 loghelper.cpp:24]     @     0x7ff93c88d856 RtlWalkFrameChain
E0129 15:00:36.939878 52528 loghelper.cpp:24]     @     0x7ff93c88be9a RtlRaiseException
E0129 15:00:36.939878 52528 loghelper.cpp:24]     @     0x7ff9397ba388 RaiseException
E0129 15:00:36.940899 52528 loghelper.cpp:24]     @     0x7ff9295a42cd _CxxThrowException
E0129 15:00:36.943876 52528 loghelper.cpp:24]     @     0x7ff9137d4170 private: char const * __ptr64 __cdecl eprosima::fastcdr::Cdr::readString(unsigned int & __ptr64) __ptr64
E0129 15:00:36.943876 52528 loghelper.cpp:24]     @     0x7ff9137d29c1 public: class eprosima::fastcdr::Cdr & __ptr64 __cdecl eprosima::fastcdr::Cdr::deserialize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > & __ptr64) __ptr64
E0129 15:00:36.945886 52528 loghelper.cpp:24]     @     0x7ff9137b3770 bool __cdecl rcl_interfaces::msg::typesupport_fastrtps_cpp::cdr_deserialize(class eprosima::fastcdr::Cdr & __ptr64,struct rcl_interfaces::msg::ParameterEvent_<class std::allocator<void> > & __ptr64)
E0129 15:00:36.946883 52528 loghelper.cpp:24]     @     0x7ff91637fd54 rmw_destroy_wait_set
E0129 15:00:36.947881 52528 loghelper.cpp:24]     @     0x7ff910153eeb public: virtual bool __cdecl rmw_fastrtps_shared_cpp::TypeSupport::deserialize(struct eprosima::fastrtps::rtps::SerializedPayload_t * __ptr64,void * __ptr64) __ptr64
E0129 15:00:36.951875 52528 loghelper.cpp:24]     @     0x7ff8ec2e489e public: virtual __cdecl eprosima::fastrtps::SubscriberListener::~SubscriberListener(void) __ptr64
E0129 15:00:36.951875 52528 loghelper.cpp:24]     @     0x7ff910151766 int __cdecl rmw_fastrtps_shared_cpp::__rmw_take_with_info(char const * __ptr64,struct rmw_subscription_t const * __ptr64,void * __ptr64,bool * __ptr64,struct rmw_message_info_t * __ptr64)
E0129 15:00:36.951875 52528 loghelper.cpp:24]     @     0x7ff91637f14f rmw_take_with_info
E0129 15:00:36.953840 52528 loghelper.cpp:24]     @     0x7ff9223c6619 rmw_take_with_info
E0129 15:00:36.954864 52528 loghelper.cpp:24]     @     0x7ff91febf0cb rcl_take
E0129 15:00:36.956832 52528 loghelper.cpp:24]     @     0x7ff906d7e6b2 protected: static void __cdecl rclcpp::executor::Executor::execute_subscription(class std::shared_ptr<class rclcpp::SubscriptionBase>)
E0129 15:00:36.957829 52528 loghelper.cpp:24]     @     0x7ff906d7d553 protected: void __cdecl rclcpp::executor::Executor::execute_any_executable(struct rclcpp::executor::AnyExecutable & __ptr64) __ptr64
E0129 15:00:36.957829 52528 loghelper.cpp:24]     @     0x7ff906d83ad0 protected: void __cdecl rclcpp::executors::MultiThreadedExecutor::run(unsigned __int64) __ptr64
E0129 15:00:36.958853 52528 loghelper.cpp:24]     @     0x7ff906d83440 public: virtual __cdecl rclcpp::executors::MultiThreadedExecutor::~MultiThreadedExecutor(void) __ptr64
E0129 15:00:36.958853 52528 loghelper.cpp:24]     @     0x7ff906d82f89 public: virtual __cdecl rclcpp::executors::MultiThreadedExecutor::~MultiThreadedExecutor(void) __ptr64
E0129 15:00:36.958853 52528 loghelper.cpp:24]     @     0x7ff939a1c4ce _o_ceil
E0129 15:00:36.960845 52528 loghelper.cpp:24]     @     0x7ff93b3e3034 BaseThreadInitThunk
E0129 15:00:36.961818 52528 loghelper.cpp:24]     @     0x7ff93c8f3691 RtlUserThreadStart

- Operating System:
  - Windows 10
- Installation type:
  - from source 
- Version or commit hash:
  eProsima/Fast-CDR:
    type: git
    url: https://github.com/eProsima/Fast-CDR.git
    version: v1.0.8
  eProsima/Fast-RTPS:
    type: git
    url: https://github.com/eProsima/Fast-RTPS.git
    version: b48ce9d2fba6fc94e756da01c58b72f2ad848238

  ros2/rclcpp:
    type: git
    url: https://github.com/ros2/rclcpp.git
    version: 0.6.2

  ros2/rmw:
    type: git
    url: https://github.com/ros2/rmw.git
    version: 0.6.1

  ros2/rmw_fastrtps:
    type: git
    url: https://github.com/ros2/rmw_fastrtps.git
    version: 0.6.1
  ros2/rmw_implementation:
    type: git
    url: https://github.com/ros2/rmw_implementation.git
    version: 0.6.1

- DDS implementation:
  - Fast-RTPS
  - rclcpp client library 
  - 

#### Steps to reproduce issue
always happened
#### Additional information
After a simple check, Cdr::readString throws the exception: eprosima::fastcdr::exception::NotEnoughMemoryException

----

**Comment by sloretz** [comment]
@43970117 What command is being run when it crashes? What steps were used to build the software?

**Comment by 43970117** [comment]
The steps followed is https://index.ros.org/doc/ros2/Installation/Windows-Development-Setup/. The crash is not caused by a command. It always happens after the application has run for many hours.

**Comment by sloretz** [comment]
> It always happens after the application has run for many hours.

Which application? Would you mind providing steps to reproduce? While the issue contains a back trace It does not say what executable it came from.

**Comment by 43970117** [comment]
This application is not a simple executable, It involves many Linux nodes and one Windows nodes, they work together for vehicle control.

**Comment by tfoote** [comment]
If you're running a large complex application and it's running out of memory as the exception `eprosima::fastcdr::exception::NotEnoughMemoryException` it's likely not a bug in the middleware. 

If you can reproduce the problem with a small example program we can help you. There are good explanations of how to isolate a bug at: https://stackoverflow.com/help/mcve and http://sscce.org/

**Comment by 43970117** [comment]
This issue is due to different ROS2 version in different platforms
