### ISSUE TITLE
[ROS2 QA] Enable symbol visibility for all RMW and RCL packages

### ISSUE THREAD

**Issue by thomas-moulard** [ros2/ros2#663]
Enable symbol visibility for all RMW and RCL packages

See doc here: https://gcc.gnu.org/wiki/Visibility

Owner: @bhatsach / @ros2/aws-robotics

## Exit Criteria

* Symbol visibility enabled for all RMW and RCL packages (ensuring the set of macros - see https://gcc.gnu.org/wiki/Visibility is defined, `CMakeLists.txt` is updated accordingly)
* All RMW and RCL are compiling with `-Wvisibility=hidden` enabled by default when using GCC and Clang on Linux and Mac OS X.

## Progress Tracking

- [x] [Discourse: Set symbol visibility to hidden for RMW and RCL packages](https://discourse.ros.org/t/set-symbol-visibility-to-hidden-for-rmw-and-rcl-packages/7981/)
- [ ] PRs
  - [ ] https://github.com/ros2/rcl/pull/391
  - [ ] https://github.com/ros2/rclcpp/pull/638

Connects to ros2/ros2#662

**Comment by emersonknapp** [comment]
@thomas-moulard is this done?

**Comment by thomas-moulard** [comment]
Partially only - we can close for now as we don't have the bandwidth to do that currently.
