### ISSUE TITLE
ROS 2 Threat Model

### ISSUE THREAD

**Issue by thomas-moulard** [ros2/ros2#672]
As a ROS 2 developer, I should have access to best practices to build a secure robotic product built using ROS 2.

Owner: @thomas-moulard 

## Exit Criteria

* A ROS 2 threat model document is contributed back to the community.

**Comment by thomas-moulard** [comment]
Sent PR for review: https://github.com/ros2/design/pull/218

**Comment by tfoote** [comment]
The first draft has been merged and the article is rendered at: http://design.ros2.org/articles/ros2_threat_model.html Please open new PRs for further discussion.

**Comment by thomas-moulard** [comment]
Follow-up PR: https://github.com/ros2/design/pull/229

**Comment by thomas-moulard** [comment]
@ryanewel Ryan, would you mind linking your PRs here as we open those follow-up PRs?

**Comment by ryanewel** [comment]
Yep,
Combine assets and business goals: https://github.com/ros2/design/pull/227
Consider XRCE attacks: https://github.com/ros2/design/pull/231

**Comment by thomas-moulard** [comment]
All PRs have been merged.
