### ISSUE TITLE
Refactor for real-time code safety

### ISSUE THREAD

**Issue by jacquelinekay** [ros2/ros2#68]
Current status:

- [x] Find an alternative to `malloc` and `free` calls in `Executor::wait_for_work`: `MemoryStrategy` https://github.com/ros2/rclcpp/pull/56
- [x] add message introspection functions to check if message has fixed size: https://github.com/ros2/rosidl/pull/33 
- [ ] add message introspection functions to check if message has *bounded* size (backlog, optional?): https://github.com/ros2/rosidl/pull/30
- [x] add `MessageMemoryStrategy` to swap out message memory allocation in subscribers (and clients and services): https://github.com/ros2/rclcpp/pull/64
- [ ] Abstract away runtime allocations made by `std::vector`, `std::map`, `std::string` ~~https://github.com/ros2/rclcpp/pull/65~~. We need a static string manager for error codes, logging, etc.
- [x] Pass timeout parameter to `rmw_wait` and expose it to the Executor interface, configure nonblocking, finite blocking and indefinite blocking options: `wait_for_work`: https://github.com/ros2/ros2/issues/73
- [x] consider changing the multiple timer threads with guard conditions structure in `rclcpp`: https://github.com/ros2/rclcpp/issues/6

**Comment by jacquelinekay** [comment]
To be revisited after William submits in review work to refactor `rmw_connext` and `rmw_opensplice`

**Comment by jacquelinekay** [comment]
bash script to reproduce the markdown table:

https://gist.github.com/jacquelinekay/292d010fbdfe67254ad7

Not sure which repo this belongs in.

**Comment by adolfo-rt** [comment]
These results report usage of non real-time safe calls, anywhere. What really matters is if (and how) they are used in the real-time code path. For instance, if a `std::vector` is pre-allocated in the non-rt path, and used without resizing in the rt path, then nothing's wrong.

**Comment by jacquelinekay** [comment]
- [ ] Find an alternative to `malloc` and `free` calls in `Executor::wait_for_work`
- [ ] Pass timeout parameter to `rmw_wait` and expose it to the Executor interface, to avoid up to `
- [ ]
