### ISSUE TITLE
Problems transferring messages between ROS2 and CycloneDDS

### ISSUE THREAD

**Issue by th3g3ntl3m3m** [ros2/ros2#686]
I'm trying to send messages using CycloneDDS, as well as using ROS2. During the transfer, problems arise, all the pre-steps and actions and what happened as a result are presented in [this topic](https://github.com/eclipse-cyclonedds/cyclonedds/issues/143). But the essence is such that the transfer from CycloneDDS to ROS2 passes without problems, but the interaction of ROS2 and the DDS library is not very good and therefore the message is not displayed.

I also attach a log file with the result of tracing. When sending a message between ROS2 and CycloneDDS.
[cyclonedds.log](https://github.com/ros2/ros2/files/3062339/cyclonedds.log)

**Comment by clalancette** [comment]
This is a very old issue, and the linked issue on CycloneDDS has been closed.  I'm going to close this out, but do feel free to reopen if you are still having trouble.
