### ISSUE TITLE
[ROS 2 QA] Contribute back a colcon plugin to analyze ASAN/TSAN results.

### ISSUE THREAD

**Issue by thomas-moulard** [ros2/ros2#692]
Exit Criteria: as a user, I can easily visualize ASAN/TSAN output on Jenkins as well as on my local developer workstation.

Owners: @cevans87  @prajakta-gokhale @thomas-moulard @xabxx

**Comment by prajakta-gokhale** [comment]
The plugin is in [colcon/colcon-sanitizer-reports](https://github.com/colcon/colcon-sanitizer-reports). It is being added to Jenkins CI via https://github.com/ros2/ci/pull/287.

**Comment by clalancette** [comment]
Given that this was implemented, I'm going to close this out.
