### ISSUE TITLE
Error message when calling `local_setup.bat` in windows

### ISSUE THREAD

**Issue by ivanpauno** [ros2/ros2#709]
## Bug report

**Required Info:**

- Operating System:
  - Windows server 2019 datacenter
- Installation type:
  - from source
- Version or commit hash:
  - current master
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
Follow the [from source installation tutorial](https://github.com/ros2/ros2_documentation/blob/master/source/Installation/Dashing/Windows-Development-Setup.rst) and call `local_setup.bat`.

#### Expected behavior
Don't see an error.

#### Actual behavior
I see this:
```
not found: "C:\dev\ros2\install\share/rttest/local_setup.bat"
not found: "C:\dev\ros2\install\share/tlsf/local_setup.bat"
not found: "C:\dev\ros2\install\share/tlsf_cpp/local_setup.bat"
not found: "C:\dev\ros2\install\share/pendulum_control/local_setup.bat"
```

#### Additional information

This seems to be bad handling of paths (not multi platform handling of them).
Probably just a correction of the `CMakeLists.txt` files in each of the packages.

**Comment by dirk-thomas** [comment]
The mix of forward / backward slashes has nothing to do with the error message. All four packages are unsupported on Windows and exit CMake early without installing any file - also no `local_setup.bat`.
