### ISSUE TITLE
ROS 2 Dashing Patch Release 1

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/ros2#723]
This issue will track the broad status of the first Dashing patch release. The date for this patch release is not currently set and will be determined by a critical mass of desired changes ready to be released.

We're going to try something new for this patch release and are using a GitHub Project board which should be publicly visible: [Dashing Patch Release 1](https://github.com/orgs/ros2/projects/6)

As with prior releases, if you want to contribute fixes please open pull requests targeting the latest development branch and mention to the reviewer that you'd like the pull request to be considered for backporting into Dashing.

**Comment by clalancette** [comment]
Patch release one is [out](https://discourse.ros.org/t/patch-release-and-package-sync-for-ros-2-dashing-diademata/9536), so closing this out.
