### ISSUE TITLE
Failed to start  dynamic_bridge node from ros1_bridge package

### ISSUE THREAD

**Issue by ZakariaChekakta** [ros2/ros2#727]
>

## Bug report
- Operating System:
 Ubuntu 18.04
- Installation type:
 binaries
- Version:
Dashing

#### Steps to reproduce issue
Follow From binaries install instructions from
https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Install-Debians/

#### Expected behavior
When we run
$ros2 run ros1_bridge dynamic_bridge, 
It should start communication between ROS 1 and ROS 2
#### Actual behavior
we get:
No executable found
#### Additionenal information
Example 1: run the bridge and the example talker and listener (https://github.com/ros2/ros1_bridge)

**Comment by dirk-thomas** [comment]
Delicate of ros2-gbp/ros1_bridge-release#4. A fixed package is already in the testing repo and will be in the main repo with the next sync.
