### ISSUE TITLE
Cannot build dashing from source with visual studio 2019

### ISSUE THREAD

**Issue by EpicZa** [ros2/ros2#741]
WIndows 10
Source
Dashing
Fast & Connext

tinyxml2
gtestvendor
tinydir_vendor
poco_vendor
fastcdr
osrf_testing_tools

Are giving "RuntimeError: Unknown / unsupported VS version ''"

Visual Studio 2019 Community, x64 admin prompt.

Repulled the source for dashing will not build with 2019.

**Comment by mjcarroll** [comment]
Have you followed the instructions to insure that you have the required CMake version?  There are some versions of CMake (including one in the prereleased VS2019) that didn't support generating VS2019 targets.

You can check your cmake version with `cmake --version` on the command line.

The output of `where cmake` would also be helpful for diagnosing.

**Comment by EpicZa** [comment]
C:\ros2>cmake --version
cmake version 3.14.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).

C:\ros2>where cmake
C:\Program Files\CMake\bin\cmake.exe

I deselected c++ cmake in the visual studio log installer, and just updated from 12 to 14. Still getting the error.

**Comment by EpicZa** [comment]
> Have you followed the instructions to insure that you have the required CMake version? There are some versions of CMake (including one in the prereleased VS2019) that didn't support generating VS2019 targets.
> 
> You can check your cmake version with `cmake --version` on the command line.
> 
> The output of `where cmake` would also be helpful for diagnosing.

Which versions are supported / not supported, and where is this listed?

**Comment by sloretz** [comment]
> Which versions are supported / not supported, and where is this listed

@EpicZa http://www.ros.org/reps/rep-2000.html#dashing-diademata-may-2019-may-2021

The minimum CMake version on Windows 10 is listed as 3.14.4

**Comment by mjcarroll** [comment]
@EpicZa were you able to resolve this with a newer version of CMake?

**Comment by dirk-thomas** [comment]
I will go ahead and close the ticket for now assuming the previous feedback resolved the problem. If not please feel free to comment on the closed ticket and it can be reopened.

**Comment by EpicZa** [comment]
@mjcarroll  I unfortunately no longer work on ROS stuff. 3.14.5 > 3.14.4 though, unless it needed an exact match? 

If I get a second this weekend, I'll test a version above 3.14.5.
