### ISSUE TITLE
Plans for making an SROS2 like an SROS

### ISSUE THREAD

**Issue by akshaysarvesh25** [ros2/ros2#769]
#### Feature description
Utilizing ROS2 on a normal network might be less secure. Any plans for making it a more secure middleware?

**Comment by gavanderhoorn** [comment]
> making an SROS2

Hey, that's [actually a good idea](https://github.com/ros2/sros2)!

:smile:

**Comment by clalancette** [comment]
As @gavanderhoorn mentioned, we do have support for it in the guise of SROS2.  So I'll close this out for now.

**Comment by akshaysarvesh25** [comment]
Thank you for the info. I was not aware of it.
