### ISSUE TITLE
Support zero-copy in ROS2

### ISSUE THREAD

**Issue by Karsten1987** [ros2/ros2#785]
top level GitHub ticket for connecting PRs related to the development for enabling zero-copy message transport in ROS2.

For me details, refer to the [design doc PR](https://github.com/ros2/design/pull/256)

**Comment by Karsten1987** [comment]
An initial round of CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8296)](http://ci.ros2.org/job/ci_linux/8296/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4249)](http://ci.ros2.org/job/ci_linux-aarch64/4249/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6765)](http://ci.ros2.org/job/ci_osx/6765/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8189)](http://ci.ros2.org/job/ci_windows/8189/)

**Comment by Karsten1987** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8334)](http://ci.ros2.org/job/ci_linux/8334/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4274)](http://ci.ros2.org/job/ci_linux-aarch64/4274/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6795)](http://ci.ros2.org/job/ci_osx/6795/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8232)](http://ci.ros2.org/job/ci_windows/8232/)

**Comment by Karsten1987** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8432)](http://ci.ros2.org/job/ci_linux/8432/)  // unrelated test failures
* Linux-aarch64 [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4346)](https://ci.ros2.org/job/ci_linux-aarch64/4346/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6860)](http://ci.ros2.org/job/ci_osx/6860/)  // unrelated test failures
* Windows -- waiting for free executor

**Comment by dirk-thomas** [comment]
@Karsten1987 Please create a corresponding PR for CycloneDDS asap since it is currently failing to build: e.g. [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8483)](https://ci.ros2.org/job/ci_linux/8483/)

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros2-create-shared-message-from-roscon-2014/12736/2
