### ISSUE TITLE
Include rmw_cyclonedds into ros2 repo for nightly jobs?

### ISSUE THREAD

**Issue by ruffsl** [ros2/ros2#786]
With rmw_cyclonedds_cpp released into dashing, is there a particular reason for the the omission of https://github.com/ros2/rmw_cyclonedds from the ros2.repos file? It would be nice to have the rmw implementation easily available in the nightly archive job for testing and CI: https://github.com/osrf/docker_images/issues/324

**Comment by dirk-thomas** [comment]
Before being added to the `ros2.repos` file an option would need to be added to our CI jobs on ci.ros2.org to enable/disable CycloneDDS. The same options already exist for the other RMW implementation we are building.

**Comment by ruffsl** [comment]
Would one just open a PR mimicking the occurrences of fastrpts, or would there be more to it?
https://github.com/ros2/ci/search?q=fastrtps&unscoped_q=fastrtps

In comparison, it looks like opensplice neccetates more boilerplate.

**Comment by dirk-thomas** [comment]
Each RMW impl. unfortunately needs their own little customization - but yes, the change necessary for CycloneDDS should be very similar.

**Comment by dirk-thomas** [comment]
One more thing: it should also be added to [rmw_implementation](https://github.com/ros2/rmw_implementation/blob/4790322697cf290b0af76b2fc00d4955658103f5/rmw_implementation/package.xml#L14-L21).

**Comment by ruffsl** [comment]
Should we also add it to the list of rosdep ignored packages in the install wiki? Or save that for release?

**Comment by dirk-thomas** [comment]
> Should we also add it to the list of rosdep ignored packages in the install wiki?

Can you point to the exact instructions you are referring to.

**Comment by ruffsl** [comment]
Oh, it's been updated to suggest apt installing the desktop meta package instead of globing over ros-: https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Install-Debians/#install-ros-2-packages

The install from source still lists some basic `--skip-keys` though: 
https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Development-Setup/#install-dependencies-using-rosdep

**Comment by dirk-thomas** [comment]
I am not sure if it is necessary to add any of the CycloneDDS package names to the `--skip-keys`. I would be good to double check and only add them if really necessary.

**Comment by ruffsl** [comment]
Was there a reason fast rtps was included in the `--skip-keys` given it should already exist in the workspace after vcs import from the ros2.repos file here, thus accounted for by `--ignore-src` arg. I could understand the skipping of opensplice or rti-connext-dds, to avoid installing external DDS debs.

**Comment by dirk-thomas** [comment]
All referenced PRs have landed by now. Closing.
