### ISSUE TITLE
cannot use ros2 topic echo /initialpose in order to monitor the position of a robot

### ISSUE THREAD

**Issue by mhallak** [ros2/ros2#815]
## Bug report

**Required Info:**

- Operating System: 
  - Ubuntu 18.04 
- Installation type: 
  - Binary 
- Version or commit hash: 
  - dashing 
- DDS implementation: 
  - Fast-RTPS 
- Client library (if applicable): 
  - N/A 

#### Steps to reproduce issue

```
$ ros2 topic echo /initialpose
Cannot echo topic '/initialpose', as it contains more than one type: [geometry_msgs/msg/PoseWithCovarianceStamped, std_msgs/msg/String]

```

#### Expected behavior
To be able to echo the topic

#### Actual behavior
I couldn't find a way to see what values are reported in the topic

#### Additional information
`$ ros2 topic list | grep init`
`/initialpose
`

**Comment by dirk-thomas** [comment]
Cross post of https://answers.ros.org/question/336263/ros2-topic-initialpose-doesnt-echo/
