### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by gerkey** [ros2/ros2#82]
Plan for initial release:

* Version everything (drop in package.xml files)
* Tag everything.
* Build binary archives on all three platforms (Trusty, OSX Yosemite, and Windows 8)
* Push archives to somewhere for download.
* Entry point is https://github.com/ros2/ros2.  If convenient, put the binary archives there as releases.  Give an entry point in the top-level README.md; put content in there and/or the wiki and/or the release notes.
* Need a code name!
 * Also, a party!
* No logo for this version.
* Include development roadmap.

**Comment by dirk-thomas** [comment]
The RC1 state is captures in: https://gist.githubusercontent.com/dirk-thomas/25906bd5af20e64d311c/raw/3862fe75eb1d25c0ae85e96e045a9ac930cec387/ros2-rc1.repos

Currently packaging:
* http://ci.ros2.org/view/packaging/job/ros2_packaging_linux/20/
* http://ci.ros2.org/view/packaging/job/ros2_packaging_osx/8/
* http://ci.ros2.org/view/packaging/job/ros2_packaging_windows/9/
