### ISSUE TITLE
vcs import src < ros2.repos

### ISSUE THREAD

**Issue by Furansujin** [ros2/ros2#842]
**when I make this command line:** 

vcs import src < ros2.repos

**I have this error :** 

Input data is not valid yaml format: unacceptable character #xdcef: special characters are not allowed in "<stdin>", position 0

**Comment by nuclearsandwich** [comment]
From the information available my first thought is that your ros2.repos file is either not intact or has errors.

How did you retrieve that repos file?

**Comment by fujitatomoya** [comment]
i do not have any problems with https://github.com/ros2/ros2/commit/3b420a7cf4a39c0127eba0b88962bb7f104adbb1

**Comment by nuclearsandwich** [comment]
@Furansujin I am going to close this issue until we can get more information. We can re-open it if you're still having trouble and can provide more details.

**Comment by Eddie-717314-Huang** [comment]
I have same issue: vcs import src < ros2.repos 
stty: stdin isn't a terminal
Video Contact Sheet *NIX v1.13.4, (c) 2007-2019 Toni Corvera
Unable to locate DejaVu Sans font. Falling back to helvetica.
File "import" doesn't exist
File "src" doesn't exist
stty: stdin isn't a terminal

need some help here, thanks

**Comment by clalancette** [comment]
It looks like you have another program installed with the name "vcs", which is conflicting with what we expect.  I'll suggest removing that or renaming it, and then following the ROS installation instructions again.

In the future, please ask questions like this on https://answers.ros.org, which is our central Question-and-Answer site.
