### ISSUE TITLE
Replace usage of typedef with using

### ISSUE THREAD

**Issue by esteve** [ros2/ros2#85]

**Comment by wjwwood** [comment]
+1 to all pr's (forgot I reviewed them this morning), with a passing CI job.

**Comment by dirk-thomas** [comment]
+ to all PRs

**Comment by esteve** [comment]
Latest CI jobs:

http://ci.ros2.org/job/ros2_batch_ci_linux/
http://ci.ros2.org/job/ros2_batch_ci_osx/
http://ci.ros2.org/job/ros2_batch_ci_windows/
