### ISSUE TITLE
In ros2 service 'type' argument doesn't exists

### ISSUE THREAD

**Issue by iamrajee** [ros2/ros2#851]
![Screenshot from 2020-01-10 11-11-41](https://user-images.githubusercontent.com/25712145/72128879-5444da00-339a-11ea-9ac7-057a142b0f7e.png)

===== Other Details =====

**SYSTEM** = Ubuntu 18.04
**LD_LIBRARY_PATH**=/opt/ros/dashing/opt/yaml_cpp_vendor/lib:/opt/ros/dashing/opt/rviz_ogre_vendor/lib:/usr/lib:/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0:/opt/ros/dashing/lib
**AMENT_PREFIX_PATH**=/opt/ros/dashing
**OSPL_URI**=file:///opt/ros/dashing/share/opensplice_cmake_module/config/ros_ospl.xml
**PWD**=/home/rajendra/ros2_ws_moveit
**ROS_DOMAIN_ID**=27
**ROS_VERSION**=2
**ROS_PYTHON_VERSION**=3
**PYTHONPATH**=/opt/ros/dashing/lib/python3.6/site-packages
**ROS_DISTRO**=dashing

**Comment by dirk-thomas** [comment]
The `ros2 service type` command is only available in Eloquent - not in Dashing. See note on the tutorials overview page: https://index.ros.org/doc/ros2/Tutorials/

---

In the future please do not post screenshots but copy-n-paste the text since the content in the image isn't searchable.
