### ISSUE TITLE
Unable to import tf2_ros

### ISSUE THREAD

**Issue by iamrajee** [ros2/ros2#853]
**I'm getting below error while running rqt_tf_tree:**

RosPluginProvider.load(rqt_tf_tree/RosTfTree) exception raised in __builtin__.__import__(rqt_tf_tree.tf_tree, [RosTfTree]):
Traceback (most recent call last):
  File "/opt/ros/dashing/lib/python3.6/site-packages/rqt_gui/ros_plugin_provider.py", line 81, in load
    attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
  File "/opt/ros/dashing/lib/python3.6/site-packages/rqt_tf_tree/tf_tree.py", line 38, in <module>
    import tf2_ros
ModuleNotFoundError: No module named 'tf2_ros'

===== **Other Details** =====

**SYSTEM** = Ubuntu 18.04
**LD_LIBRARY_PATH**=/opt/ros/dashing/opt/yaml_cpp_vendor/lib:/opt/ros/dashing/opt/rviz_ogre_vendor/lib:/usr/lib:/opt/rti.com/rti_connext_dds-5.3.1/lib/x64Linux3gcc5.4.0:/opt/ros/dashing/lib
**AMENT_PREFIX_PATH**=/opt/ros/dashing
**OSPL_URI**=file:///opt/ros/dashing/share/opensplice_cmake_module/config/ros_ospl.xml
**PWD**=/home/rajendra/ros2_ws_moveit
**ROS_DOMAIN_ID**=27
**ROS_VERSION**=2
**ROS_PYTHON_VERSION**=3
**PYTHONPATH**=/opt/ros/dashing/lib/python3.6/site-packages
**ROS_DISTRO**=dashing

**Comment by dirk-thomas** [comment]
`rqt_tf_tree` depends on `tf2_ros` and needs its Python API. But that has only been ported for Eloquent. Therefore `rqt_tf_tree` can't work (and should have never been released into Dashing).

ros/rosdistro#23485 removes it from Dashing.
