### ISSUE TITLE
$COLCON_PREFIX_PATH not showing installation path

### ISSUE THREAD

**Issue by suab321321** [ros2/ros2#855]
`source /opt/ros/dashing/setup.bash` is not loading the `env` varible `COLCON_PREFIX_PATH` with its installation path

**Required Info:**

- Operating System:
  `Ubuntu 18.04` 
- Installation type:
  `binaries`
- Version or commit hash:
  `dashing`
- DDS implementation:
  `default`

**Comment by dirk-thomas** [comment]
The Debian packages are not built with `colcon` and therefore they don't have that environment variable set.

Why are you expecting it / what are you needing it to be set for?

**Comment by suab321321** [comment]
when building rclnodejs the env variable COLCON_PREFIX_PATH needs to be setup for its full installation using npm install.
In crystal version sourcing the setup.bash loaded the env variable COLCON_PREFIX_PATH but in dashing version it is not happening.

**Comment by dirk-thomas** [comment]
`rclnodejs` should simply not rely on the presence of the `COLCON_PREFIX_PATH` environment variable. In the case of Debian packages `colcon` is not involved hence this variable doesn't exist. Instead the package could check the `AMENT_PREFIX_PATH` which is defined in both cases - from binary as well as from source.

Since this is not in problem in ROS 2 but only in the `rclnodejs` package I will go ahead and close this ticket. Please fill a ticket in that repository instead (and cross reference this ticket for future readers to find the new follow up ticket).

**Comment by suab321321** [comment]
@dirk-thomas but sir rclnodejs uses COLCON_PREFIX_PATH but in crystal version COLCON_PREFIX_PATH was getting loaded successfully.o
One version is able to do it and other is not.Is this not problem in dashing version?

**Comment by dirk-thomas** [comment]
While it was set in Crystal it was never meant to be used by package and as of Dashing it is not available anymore.

**Comment by suab321321** [comment]
okay @dirk-thomas :)

**Comment by minggangw** [comment]
Hi @suab321321 the rclnodejs has adoptedd `AMENT_PREFIX_PATH` since v0.10.2 (currently v0.11.1) please see https://github.com/RobotWebTools/rclnodejs/commit/e40a6631f030af64324e1a6e6d2f00c1de7cdc1c, so would you please verify it with the latest version?

**Comment by suab321321** [comment]
@minggangw develop branch of rclnodejs is using COLCON_PREFIX_PATH for installing it.
see this
![Screenshot from 2020-01-19 09-34-59](https://user-images.githubusercontent.com/52123334/72674653-1da84700-3a9f-11ea-9f15-bac28403c747.png)

**Comment by minggangw** [comment]
It seems that you are running rclnodejs@0.10.0

**Comment by suab321321** [comment]
I m runnig develop branch of rclnodejs wasnt that suppose to be latest @minggangw ?

**Comment by minggangw** [comment]
Please reference https://github.com/RobotWebTools/rclnodejs#match-with-ros-20-stable-releases

**Comment by suab321321** [comment]
@minggangw yes its working now AMENT_PREFIX_PATH is working for 0.10.3.Thank you for your help.
