### ISSUE TITLE
Eloquent Patch Release 2

### ISSUE THREAD

**Issue by mjcarroll** [ros2/ros2#859]
This issue will track the broad status of the next Eloquent patch release. The date for this patch release is not currently set and will be determined by a critical mass of desired changes ready to be released.

We're going to use a GitHub Project board for this patch release again: [Eloquent Patch Release 2](https://github.com/orgs/ros2/projects/17)

As with prior releases, if you want to contribute fixes please open pull requests targeting the latest development branch and mention to the reviewer that you'd like the pull request to be considered for backporting into Eloquent.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-for-eloquent-sync-and-patch-release-2020-04-17/13562/1

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/final-eloquent-sync-and-patch-release-2020-12-04/17679/1
