### ISSUE TITLE
What's the relationship between the ros2.repos and rosdistro

### ISSUE THREAD

**Issue by seanyen** [ros2/ros2#874]
Is `ros2.repos` a snapshot of the `rosdistro`? How does `ros2.repos` get generated? Is it up to `ros_base` metapackage? And for a tool to consume the list of the upstream (or released) sources, should it be using `rosinstall_generator` or `ros2.repos`?

**Comment by dirk-thomas** [comment]
The `ros2.repos` file is independently / manually maintained from `rosdistro`. The set it contains doesn't specifically align with any ROS variant. We recommend that any tool should use the `rosinstall_generator` since the goal is to get rid of the `ros2.repos` file at some point.
