### ISSUE TITLE
remote nodes communicate with long time delaying

### ISSUE THREAD

**Issue by aitazhixin** [ros2/ros2#877]
When i test remote node communication, two PCs are connected by network cable. PC-A as publisher, and PC-B as subscriber. ROS2 msg type is sensor_msgs/msg/Image, and image size is 720 * 1280. Msg delay reaches from 80ms to 140ms. If publisher and subscriber run on the same PC, msg delay just 1ms or 12ms. Is there any idea to impove transportation of image sensor data in ROS2?

**Comment by claireyywang** [comment]
closing due to duplicate here https://github.com/ros2/rmw_fastrtps/issues/352
