### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by YoJn** [ros2/ros2#878]
## System: ubuntu18.04
- Install the ros2 version: Eloquent Elusor
- When I used colcon to compile the source package, I got the following problem

![error1](https://user-images.githubusercontent.com/41852511/76420365-f9048780-63dc-11ea-9bbc-fcfa5d8f6410.png)

- If the above picture is not clear, what I intercept below is the main part

![error2](https://user-images.githubusercontent.com/41852511/76420441-13d6fc00-63dd-11ea-91ac-26db8bf3f2ba.png)

- Looking forward to your answer! Thanks for your help !

**Comment by claireyywang** [comment]
Hi, what's your OS version? Are you following instructions here https://index.ros.org/doc/ros2/Installation/Eloquent/ ? Could you provide more specific steps for us to reproduce this error?

**Comment by YoJn** [comment]
@claireyywang Thanks your reply
- System environment: linux ubuntu18.04
- I installed it according to the link below
 > https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Development-Setup/

- There was a problem executing the following command
> colcon build --symlink-install
