### ISSUE TITLE
Build error Could NOT find TinyXML (missing TinyXML_LIBRARY)

### ISSUE THREAD

**Issue by mce16** [ros2/ros2#911]
## Bug report

**Required Info:**

- Operating System:
  - <!Windows 10 -->
- Installation type:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 
- Client library (if applicable):
  - <! N/A -->

#### Steps to reproduce issue

```

```

**Comment by clalancette** [comment]
No information in here, so closing.
