### ISSUE TITLE
Windows 10 Build error 

### ISSUE THREAD

**Issue by mce16** [ros2/ros2#912]
## Bug report

**Required Info:**

- Operating System:
  -Windows 10
- Installation type:
  - source
- Version or commit hash:
  -  dashing latest
- DDS implementation:
  - fast-rtps 
- Client library (if applicable):
  - N/A 
#### Steps to reproduce issue

``` colcon build --merge-install ``` 
```

```

#### Additional information

Using Visual Studio 2017 x64

Found tinyxml_vendor:  (D:/dev/ros2_dashing/install/share/tinyxml_vendor/cmake)
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find TinyXML (missing: TinyXML_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  D:/dev/ros2_dashing/install/share/tinyxml_vendor/cmake/Modules/FindTinyXML.cmake:71 (find_package_handle_standard_args)
  CMakeLists.txt:36 (find_package)

**Comment by clalancette** [comment]
It looks like you probably missed the steps to install the Chocolatey packages here: https://index.ros.org/doc/ros2/Installation/Dashing/Windows-Install-Binary/#dashing-windows-install-binary-installing-prerequisites .

In general, please ask these kind of questions at https://answers.ros.org.  That way we can have these answers in one place that is easily searchable.  Closing this for now, please reopen if you think this is still a bug.
