### ISSUE TITLE
Audit intra process comms for thread safety

### ISSUE THREAD

**Issue by wjwwood** [ros2/ros2#92]
At best implement tests which exercise the thread safety of the intra process manager class, but also audit the design considering the possible ways in which lighting may strike.

This is a follow on to https://github.com/ros2/ros2/issues/59

Related comments:

- https://github.com/ros2/rclcpp/pull/73#discussion_r37443374
- https://github.com/ros2/rclcpp/pull/73#discussion_r37456105

**Comment by jacquelinekay** [comment]
I made the demo single-threaded for now, to avoid possible lightning strikes (ros2/demos/pull/12).

**Comment by tfoote** [comment]
@gerkey to take a look.

**Comment by jacquelinekay** [comment]
@wjwwood, do you consider this ticket to be resolved by recent improvements to fix race conditions? I don't believe that we've fixed all multithreading issues, but I'm fine with closing this issue for now and ticketing new, more specific issues about thread safety in the future.

**Comment by wjwwood** [comment]
That's ok with me, this ticket was just there to remind us that I didn't consider thread-safety closely when originally writing it.
