### ISSUE TITLE
Debian Buster cannot install ROS2 through apt install.

### ISSUE THREAD

**Issue by JoveH-H** [ros2/ros2#936]
- Operating System:
  - Raspberry Pi OS (64 bit) / Debian buster
- Installation type:
  - apt install
- Version or commit hash:
  - Foxy master
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue
Install according to the instructions on the following website,https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Install-Debians/.

sudo apt install ros-foxy-desktop, but ros-foxy-desktop could not be located.

The same operation is normally installed on Ubuntu.

**Comment by clalancette** [comment]
As you can see from https://www.ros.org/reps/rep-2000.html#id32 , Debian Buster is Tier-3, which means it is community supported, and we don't build binaries for it.  So the only real option on Buster is to build from source.

I'm going to close this out, but feel free to keep commenting if you have more questions.
