### ISSUE TITLE
How can we achieve fault isolation in composition?

### ISSUE THREAD

**Issue by realdream** [ros2/ros2#945]
## Feature request
Fault isolation in composition
#### Feature description

Failure in a single component may cause the whole component container crash, any idea how to avoide this and achieve fault isolation along with high efficiency transmission?
#### Implementation considerations

is inter-process zero copy possible( shared memory e.g.)? by rmw or dds? will it have a big difference from intra-process on efficiency?

**Comment by dirk-thomas** [comment]
With `composition` multiple nodes are being executed in a single process. If anything causes e.g. a segfault the whole process will stop hence all nodes. There is intrinsically nothing to be done about it.

Some RMW implementation might offer a shared memory transport. That will still require serialization / deserialization though which isn't needed for intra-process communication which just passes pointers.

Assuming my comment answers your questions I will go ahead and close this ticket. In general we request questions to be asked on answers.ros.org.
