### ISSUE TITLE
[Meta-ticket]: Add pytest.ini to all packages which use pytest

### ISSUE THREAD

**Issue by clalancette** [ros2/ros2#951]
In the current state, if you run any of the pytest tests locally, you get warning messages like:

```
/home/ubuntu/.local/lib/python3.8/site-packages/_pytest/junitxml.py:417
  /home/ubuntu/.local/lib/python3.8/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)
```

We currently workaround this in CI by always adding a pytest.ini before starting tests (see https://github.com/ros2/ci/pull/471), but it would be nice to get rid of that and just have local and CI work the same.

This is a tracking bug for all of the places we need to change it.  Once I've opened the relevant PRs, I'll run one CI job for all of them here.

**Comment by clalancette** [comment]
We'll also likely have to backport these to Dashing and Eloquent to keep the warnings down there.

**Comment by clalancette** [comment]
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11206)](http://ci.ros2.org/job/ci_linux/11206/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6479)](http://ci.ros2.org/job/ci_linux-aarch64/6479/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9165)](http://ci.ros2.org/job/ci_osx/9165/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11123)](http://ci.ros2.org/job/ci_windows/11123/)

**Comment by clalancette** [comment]
The single failure in macOS and Windows is there in nightlies.  So I think these are good to start reviewing and merging.

**Comment by clalancette** [comment]
All right, with everything merged, let's see how a CI job does with the pytest.ini workaround removed:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11224)](http://ci.ros2.org/job/ci_linux/11224/)

**Comment by clalancette** [comment]
I totally missed the whole ament_lint repository, so the failure in the last job is because of that.  Here's another try, with that PR in place and the one to micro-ROS to see how we are doing:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11228)](http://ci.ros2.org/job/ci_linux/11228/)

**Comment by clalancette** [comment]
I was missing ament_cmake_ros as well.  Another try:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11235)](http://ci.ros2.org/job/ci_linux/11235/)

**Comment by clalancette** [comment]
Here's a regular CI, just to show that the linked PRs don't have regressions:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11257)](http://ci.ros2.org/job/ci_linux/11257/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6517)](http://ci.ros2.org/job/ci_linux-aarch64/6517/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9216)](http://ci.ros2.org/job/ci_osx/9216/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11166)](http://ci.ros2.org/job/ci_windows/11166/)

**Comment by clalancette** [comment]
All right, all failures in CI are also in nightlies.

**Comment by clalancette** [comment]
All right, these are all in now.  In theory, we could remove the pytest.ini workaround from CI; however, if we do that, we'll break CI for Dashing, Eloquent, and Foxy.  The obvious solution is to backport all of these changes to all of those active distributions, which would finally allow us to close https://github.com/ros2/ci/pull/471 , but is also a lot of churn (27*3 == 81 PRs to do this).

**Comment by dirk-thomas** [comment]
We could also just remove the CI workaround for Foxy and rolling to ensure we don't accidentally reintroduce a problem.

**Comment by clalancette** [comment]
> We could also just remove the CI workaround for Foxy and rolling to ensure we don't accidentally reintroduce a problem.

All right, since I've now done this in https://github.com/ros2/ci/pull/497, I'm going to close this tracking ticket.  Thanks for the feedback and reviews here.
