### ISSUE TITLE
replace deprecated CMake modules PythonInterp/PythonLibs with Python3

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/ros2#962]
Both CMake modules [FindPythonInterp](https://cmake.org/cmake/help/v3.18/module/FindPythonInterp.html) as well as [FindPythonLibs](https://cmake.org/cmake/help/v3.18/module/FindPythonLibs.html) are deprecated since CMake 3.12.

Foxy already targets a new enough CMake version and therefore Rolling will too we should switch to using [FindPython3](https://cmake.org/cmake/help/v3.18/module/FindPython3.html) instead.

The move will either significantly reduce the logic in the custom CMake module https://github.com/ros2/python_cmake_module/blob/c212c5e12b7c70baacc58684bb378c0fc8e1be86/cmake/Modules/FindPythonExtra.cmake or allow to remove it entirely.

**Comment by clalancette** [comment]
I'm going to close this one as we are tracking the work for this over in https://github.com/ros2/python_cmake_module/issues/6
