### ISSUE TITLE
ROS2 web bridge support for Foxy Fitzroy and Eloquent Elusor

### ISSUE THREAD

**Issue by aqieez** [ros2/ros2#991]
I notice the ROS2 web bridge is not yet supported by Foxy and Eloquent distribution. Is there already any plan for support updates?

**Comment by clalancette** [comment]
The web bridge is handled separately from the ROS 2 core.  I'm going to close this out, but I'll suggest that you open an issue with the particular repository that is handling the web bridge to see what their support plans are (this may be https://github.com/RobotWebTools/ros2-web-bridge, but I'm honestly not sure).
